import {
  blunderAuditCommand,
  calculateApcaLightnessContrast,
  discoverBlunderFiles,
  formatBlunderAuditReport,
  getApcaBadgeInfo,
  renderApcaContrastBadge,
  renderAsciiBlunderTable,
  type ApcaBadgeInfo,
  type ApcaContrastCompliance,
  type AuditedBlunder,
  type BlunderAuditCommandResult,
  type BlunderAuditSummary,
  type BlunderStatus,
  type RGBColor,
} from "../cli/commands/blunder-audit.ts";
import type { CommandContext, Flags } from "../cli/options.ts";
import {
  appendCompletedBlunderLogEntry,
  autoPromoteBlunder,
  CANONICAL_COMPLETED_BLUNDERS_FILE,
  DEFAULT_COMPLETED_BLUNDERS_FILE,
  generateBlunderRegressionTest,
  generateRegressionTestSuite,
  isBlunderEligibleForPromotion,
  LEGACY_COMPLETED_BLUNDERS_FILE,
  LEGACY_LOWER_COMPLETED_BLUNDERS_FILE,
  promoteResolvedBlunders,
  readCompletedBlundersLog,
  resolveCanonicalCompletedBlundersPath,
  resolveCompletedBlundersPath,
  TODO_COMPLETED_BLUNDERS_FILE,
  validateRegressionTest,
  writeCompletedBlundersLog,
  type AutoPromoteBlunderParams,
  type BlunderPromotionOptions,
  type BlunderPromotionResult,
  type GeneratedRegressionTest,
  type RegressionTestGeneratorOptions,
  type RegressionTestSuiteOptions,
} from "./blunders.ts";

export {
  appendCompletedBlunderLogEntry,
  autoPromoteBlunder,
  blunderAuditCommand,
  calculateApcaLightnessContrast,
  CANONICAL_COMPLETED_BLUNDERS_FILE,
  DEFAULT_COMPLETED_BLUNDERS_FILE,
  discoverBlunderFiles,
  formatBlunderAuditReport,
  generateBlunderRegressionTest,
  generateRegressionTestSuite,
  getApcaBadgeInfo,
  isBlunderEligibleForPromotion,
  LEGACY_COMPLETED_BLUNDERS_FILE,
  LEGACY_LOWER_COMPLETED_BLUNDERS_FILE,
  promoteResolvedBlunders,
  readCompletedBlundersLog,
  renderApcaContrastBadge,
  renderAsciiBlunderTable,
  resolveCanonicalCompletedBlundersPath,
  resolveCompletedBlundersPath,
  TODO_COMPLETED_BLUNDERS_FILE,
  validateRegressionTest,
  writeCompletedBlundersLog,
  type ApcaBadgeInfo,
  type ApcaContrastCompliance,
  type AuditedBlunder,
  type AutoPromoteBlunderParams,
  type BlunderAuditCommandResult,
  type BlunderAuditSummary,
  type BlunderPromotionOptions,
  type BlunderPromotionResult,
  type BlunderStatus,
  type GeneratedRegressionTest,
  type RGBColor,
  type RegressionTestGeneratorOptions,
  type RegressionTestSuiteOptions,
};

export function executeBlunderAudit(
  flags: Flags,
  context?: CommandContext,
): BlunderAuditCommandResult {
  return blunderAuditCommand(flags, context);
}
