export const ALLOWED_ROOT_FILES: ReadonlySet<string> = new Set([
  "package.json",
  "tsconfig.json",
  "AGENTS.md",
  "README.md",
  "GEMINI.md",
  "lefthook.yml",
  ".gitignore",
  "bun.lock",
  "bun.lockb",
  ".editorconfig",
  ".oxfmtrc.json",
  "eslint.config.js",
  ".prettierrc",
  "LICENSE",
  "bunfig.toml",
  ".capture.yaml",
]);

export const ALLOWED_ROOT_DIRS: ReadonlySet<string> = new Set([
  "olt",
  ".olt",
  ".capsules",
  "tests",
  "docs",
  "scratch",
  ".scratch",
  "coverage",
  ".coverage",
  "node_modules",
  ".git",
  ".github",
  ".tmp",
  ".locks",
  "scripts",
]);
