export {
  findRepositoryRoot,
  scanMisplacedCapsulesDirectories,
  verifyStrictRepositoryCapsuleRoot,
  type CapsuleRootAuditResult,
} from "./capsule-root.ts";
export {
  verifyUnifiedEvidenceLocation,
  type EvidenceLocationAuditResult,
} from "./evidence-location.ts";
export {
  DOCTOR_SUPERVISOR_CODE_CONTAMINATION,
  CODE_EDIT_TOOLS,
  GRAPH_MUTATION_COMMANDS,
  VALIDATION_COMMANDS,
  TERMINAL_PULSE_OUTCOMES,
  isMindRole,
  isCoordinatorRole,
  isOrchestratorRole,
  isImplementerRole,
  isValidatorRole,
  isTier3Role,
  isFullTestSuiteCommand,
  isSourceCodeFile,
  inferRole,
  deduplicateFindings,
  auditCrossTierSpawning,
  auditCoordinatorConfinement,
  auditSupervisorCodeContamination,
  auditOrchestratorConfinement,
  auditImplementerConfinement,
  auditPulseTerminationConfinement,
  auditTierConfinement,
  summarizeTierConfinement,
  assertSupervisorRoleConfinement,
  type TierViolationType,
  type TierViolationSeverity,
  type TierConfinementFinding,
  type TierConfinementSummary,
  type GitDiffRecord,
} from "./tier-confinement/index.ts";
export {
  checkPlanningDag,
  checkAstPurity,
  scanFileForAstPurity,
  checkAntiMockMutation,
  checkAntiBatchingIsolation,
  checkDualChannelUi,
  checkCognitiveValidatorCommandLock,
  checkCommandLockIntegrity,
  checkRoleBoundaryInterlock,
  checkPushbackQuotas,
  checkRepositoryHygiene,
  purgeOrphanedScratch,
  checkGitIndexIntegrity,
  autoHealGitState,
  cleanseDanglingLocks,
  isProcessAlive,
  recoverStaleLeases,
  checkPolicyDoctor,
  auditPolicyDoctor,
  autoHealCapsule,
  quarantineTornTail,
  checkMailboxHealth,
  checkMailboxDiskActivity,
  autoHealMailboxState,
  healCorruptedCursor,
  pruneOrphanedMailboxes,
  checkWorktreeHealth,
  autoHealWorktreeState,
  MIN_ADVERSARIAL_PROBES,
  MANDATORY_COGNITIVE_PUSHBACKS,
  type PlanningDagCheckOptions,
  type AstPurityCheckOptions,
  type AntiMockMutationCheckOptions,
  type CounterfactualCheckRecord,
  type AntiBatchingIsolationOptions,
  type DualChannelUiCheckOptions,
  type CognitiveValidatorCommandLockOptions,
  type RoleBoundaryInterlockOptions,
  type PushbackQuotasCheckOptions,
  type RepositoryHygieneOptions,
  type GitIndexCheckOptions,
  type AutoHealGitStateOptions,
  type LockCleanerOptions,
  type PolicyDoctorOptions,
  type AutoHealOptions,
  type MailboxHealthOptions,
  type DoctorWorktreeHealthReport,
  type WorktreeHealthOptions,
  type DoctorSeverity,
  type DoctorDiagnosticFinding,
  type DoctorCheckEngineResult,
  type DoctorAutoHealResult,
  type RepositoryHygieneFinding,
  type RepositoryHygieneResult,
  type AstPurityFinding,
  type GitIndexIntegrityReport,
} from "./engines.ts";
