export type {
  AggregatedDefect,
  DefectCategory,
  DefectEntry,
  DefectHypothesis,
  DefectKeyOptions,
  DefectOccurrence,
  DefectRecordInput,
  DefectRemediationAction,
  DefectResolutionProof,
  DefectSeverity,
  DefectStatus,
  HistoricalOccurrence,
  LiveDeduplicationOptions,
  ParseDefectLogOptions,
} from "./defects/index.ts";
export {
  aggregateDefectEntries,
  categorizeDefect,
  computeDefectDedupKey,
  computeDefectDiscriminator,
  createDefectContentHash,
  createFnv1aHash,
  createSha256Hash,
  deduplicateDefectLog,
  deserializeDefectRecord,
  isRecord,
  mergeDuplicateDefect,
  mergeStatus,
  normalizeObservationSignature,
  normalizeText,
  parseAndDeduplicateDefectJsonl,
  parseDefectLog,
  parseIsoMs,
  pickHigherSeverity,
  resolveDefect,
  resolveDefectRecord,
  serializeAggregatedDefectLog,
  serializeDefectLog,
  SEVERITY_WEIGHTS,
  toAggregatedDefect,
  validateResolutionProof,
  verifyResolutionProofEmpirical,
  withinDeduplicationWindow,
} from "./defects/index.ts";
