export const DEFAULT_TEST_WALL_TIMEOUT_MS = 60_000;
export const DEFAULT_TEST_IDLE_TIMEOUT_MS = 30_000;
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 1_000;
export const DEFAULT_STALL_PROGRESS_THRESHOLD_MS = 60_000;
export const DEFAULT_GRACE_PERIOD_MS = 1_000;
export const DEFAULT_DIAGNOSTIC_TAIL_BYTES = 64 * 1024;

export const EXIT_STATUS_SIGKILL_TIMEOUT = "SIGKILL_TIMEOUT";
export const EXIT_STATUS_SIGTERM_TIMEOUT = "SIGTERM_TIMEOUT";
export const EXIT_STATUS_SIGKILL_MANUAL = "SIGKILL_MANUAL";
export const EXIT_STATUS_EXIT_FAILURE = "EXIT_FAILURE";
export const EXIT_STATUS_EXIT_SUCCESS = "EXIT_SUCCESS";

export const ERROR_CLASS_STALL_TIMEOUT = "STALL_TIMEOUT";
export const ERROR_CLASS_WALL_TIMEOUT = "WALL_TIMEOUT";
export const ERROR_CLASS_IDLE_TIMEOUT = "IDLE_TIMEOUT";
export const ERROR_CLASS_PROCESS_HANG = "PROCESS_HANG";
export const ERROR_CLASS_ZOMBIE_PROCESS = "ZOMBIE_PROCESS";
