/**
 * Product and vendor names that must never NAME anything: no type, field, enum member, constant,
 * function, variable or file may be called after one. A vendor is a VALUE recorded inside a generic
 * category — `category: "browser-automation", tool: "<whatever ran>"` — because a type named after
 * one product quietly makes that product the schema's favourite and leaves every rival tool
 * describing itself in a shape built for somebody else.
 *
 * Names deliberately left out of this list, each for a stated reason:
 *
 * - `bun` and `git`: the harness IS written in one and DOES execute the other. They are its own
 *   substrate rather than instances of a category it offers, and the identifiers naming them
 *   (`Bun`, `GIT_CONFIG_GLOBAL`) are those products' own required spellings.
 * - `node`, `edge`, `chrome`, `cursor`, `webkit`, `rollup`, `parcel`, `linear`: each is an ordinary
 *   word of this domain first — graph nodes and edges, UI chrome, a text cursor, a vendor-prefixed
 *   DOM property, a rolled-up metric, a parcel of work. Matching them would report noise, and a
 *   check that reports noise is a check nobody keeps.
 */
export const VENDOR_NAMES: readonly string[] = [
  "ansible",
  "anthropic",
  "antigravity",
  "babel",
  "bard",
  "bitbucket",
  "cargo",
  "cassandra",
  "chatgpt",
  "chromium",
  "claude",
  "cloudflare",
  "codex",
  "cohere",
  "copilot",
  "cypress",
  "deepseek",
  "deno",
  "docker",
  "dotnet",
  "elasticsearch",
  "emacs",
  "esbuild",
  "eslint",
  "firefox",
  "gecko",
  "gemini",
  "github",
  "gitlab",
  "gofmt",
  "golang",
  "gpt",
  "gradle",
  "grok",
  "grunt",
  "gulp",
  "haiku",
  "heroku",
  "homebrew",
  "intellij",
  "jasmine",
  "jest",
  "jetbrains",
  "junit",
  "karma",
  "kubernetes",
  "langchain",
  "llama",
  "maven",
  "mercurial",
  "mistral",
  "mocha",
  "mongodb",
  "mysql",
  "neovim",
  "netlify",
  "nightwatch",
  "npm",
  "nuget",
  "ollama",
  "openai",
  "opus",
  "oxfmt",
  "oxlint",
  "perplexity",
  "playwright",
  "pnpm",
  "poetry",
  "postgres",
  "postgresql",
  "prettier",
  "prisma",
  "puppeteer",
  "pylint",
  "pytest",
  "python",
  "qwen",
  "railway",
  "redis",
  "ripgrep",
  "rspec",
  "rubocop",
  "safari",
  "selenium",
  "snowpack",
  "sonnet",
  "sqlite",
  "stylelint",
  "subversion",
  "terraform",
  "testcafe",
  "tslint",
  "turbopack",
  "typescript",
  "vercel",
  "vite",
  "vitest",
  "vscode",
  "webdriver",
  "webpack",
  "windsurf",
  "xcode",
  "yarn",
];
