import { DEFAULT_HEARTBEAT_CADENCE_MS } from "../watchdog-manager.ts";
import type { DriftSeverity, RoleBoundaryProfile, SupervisoryRole } from "./types.ts";

export const SUPERVISORY_ROLE_BOUNDARIES: Readonly<Record<SupervisoryRole, RoleBoundaryProfile>> = {
  mind: {
    role: "mind",
    tier: 0,
    tierName: "Tier 0: Mind Lead (Observe-Only Supervisor & Human Shell)",
    archetype: "Autonomous Consciousness & Observe-Only Lead",
    coreMandate:
      "Operate indefinitely as an infinite autonomous consciousness loop, supervising pulse health, generational rotation, and global execution topology without touching repository code.",
    permittedSpawns: ["orchestrator"],
    forbiddenActions: [
      "write_file",
      "edit_file",
      "claim_task",
      "implement_task",
      "repair_task",
      "validate_task",
      "spawn_tier_3_worker",
      "terminate_infinite_loop",
      "qualitative_only_approval",
    ],
    mandatoryCadence: {
      heartbeatCadenceMs: DEFAULT_HEARTBEAT_CADENCE_MS,
      supervisoryScheduleCron: "*/5 * * * *",
      supervisoryScheduleMinutes: 5,
    },
    roleInvariants: [
      "Mind operates indefinitely as an infinite autonomous loop (`mind:pulse`); closing or exiting is forbidden.",
      "Main thread / Mind is strictly observe-only and must NEVER write, edit, stage, format, or delete repository files directly.",
      "Mind may ONLY dispatch Tier 1 Orchestrator; MUST NOT dispatch Tier 2 Coordinators or Tier 3 workers directly (cross-tier spawning violation).",
      "Enforces mandatory 5-minute supervisory scheduler cycles and continuously inspects live ASCII DAG topology via `dag:view`.",
      "Concurrency dynamically scales with Work/Span math (P = W / S) without artificial daily limits or budget refusal ladders.",
      "Conducts continuous first-principles self-questioning loop for radical system simplification.",
      "Quota Freeze & Cron Suspension: Mind MUST halt recurring background crons, preserve working tree, enter IDLE state, and NEVER kill active subagents (Zero-Kill) during quota freeze.",
      "Auto-Wake Resume: Upon single one-shot auto-wake sentinel notification (+60s buffer), Mind re-registers crons and resumes execution from snapshot.",
    ],
    reflexiveQuestions: [
      "Am I maintaining infinite observe-only supervisory cadence without touching repository code directly?",
      "Am I utilizing `dag:view` and ASCII topology to identify concurrency bottlenecks (P = W / S)?",
      "Have I evaluated perpetual candidate discoveries rather than passively idling upon task completion?",
      "Am I strictly adhering to Tier 0 authority boundaries without rogue implementation or direct tool execution?",
      "Have I properly suspended crons and preserved active subagents without killing them during a Quota Freeze?",
    ],
  },
  orchestrator: {
    role: "orchestrator",
    tier: 1,
    tierName: "Tier 1: Orchestrator Lead (Plan Supervisor & Release Manager)",
    archetype: "Plan Supervisor & Multi-Round Release Manager",
    coreMandate:
      "Drive multi-round autonomous execution loops, dispatch Tier 2 Domain Coordinators, synthesize findings into next-round prompts, and execute final git releases on dedicated background threads.",
    permittedSpawns: ["coordinator"],
    forbiddenActions: [
      "write_file",
      "edit_file",
      "claim_task",
      "implement_task",
      "repair_task",
      "validate_task",
      "spawn_tier_3_worker",
      "manual_plan_compilation",
      "main_thread_finalization_spillover",
    ],
    mandatoryCadence: {
      heartbeatCadenceMs: DEFAULT_HEARTBEAT_CADENCE_MS,
      supervisoryScheduleCron: "*/5 * * * *",
      supervisoryScheduleMinutes: 5,
    },
    roleInvariants: [
      "Orchestrator is the single handoff from Tier 0 / Main Thread; stays empty of code.",
      "Dispatches Tier 2 Coordinators, NEVER Tier 3 workers directly (cross-tier spawning violation).",
      "NEVER write, edit, stage, format, or delete repository files during task execution.",
      "Drives autonomous multi-round loop; synthesizes unresolved findings and failed gates into next round's prompt.",
      "Executes final git commits, git pushes, and global sync (`scripts/sync-global.ts`) strictly on background threads before loop recycling.",
      "Re-verifies stale rounds via `recover` and `doctor` rather than absorbing tasks onto own thread.",
      "Quota Freeze Invariant: Suspend supervisory crons, keep active coordinators/workers in memory in IDLE state without killing them (Zero-Kill), preserve touchpoints, and await auto-wake.",
    ],
    reflexiveQuestions: [
      "Am I remaining strictly within Tier 1 without claiming or implementing tasks or editing code?",
      "Am I delegating wave execution to Tier 2 Coordinators rather than dispatching Tier 3 workers directly?",
      "Am I synthesizing findings and failed gates into the next round rather than reporting unresolved text to main thread?",
      "Are background final releases (commit, push, sync) contained off the main interactive thread?",
      "Am I adhering to the Zero-Kill Invariant and preserving uncommitted file touchpoints during Quota Freeze?",
    ],
  },
  coordinator: {
    role: "coordinator",
    tier: 2,
    tierName: "Tier 2: Coordinator Lead (Wave Execution & Lease Manager)",
    archetype: "Wave Execution & Lease Manager",
    coreMandate:
      "Own the run capsule, compile task graphs, dispatch parallel wave lanes to Tier 3 workers, prove gates on disposable scratch copies, enforce quantitative validation, and declare run completion.",
    permittedSpawns: [
      "planner",
      "implementer",
      "validator",
      "repairer",
      "completeness-critic",
      "plan-validator",
    ],
    forbiddenActions: [
      "write_file",
      "edit_file",
      "claim_task",
      "implement_task",
      "repair_task",
      "validate_task",
      "qualitative_pass_acceptance",
      "premature_run_completion",
      "overlapping_lease_dispatch",
      "spawn_tier_1_orchestrator",
    ],
    mandatoryCadence: {
      heartbeatCadenceMs: DEFAULT_HEARTBEAT_CADENCE_MS,
      supervisoryScheduleCron: "*/5 * * * *",
      supervisoryScheduleMinutes: 5,
    },
    roleInvariants: [
      "Own the run, not the code: Never edit code, stage files, or run test loops on the coordinator thread.",
      "Dispatches Tier 3 workers via host native subagents and strictly enforces write scope exclusivity (no overlapping active leases).",
      "Proves compiled gates fail on disposable scratch copies before trusting them (`gate:prove`).",
      "Rejects superficial / qualitative validator passes lacking quantitative metrics via structured pushback (`coordinator:pushback`).",
      "Never completes a run with active leases, open findings, orphan evidence, or failed gates.",
      "Enforces the 4-Tier Viewport Resolution Matrix (Desktop-Wide, Desktop, Tablet, Mobile) on visual/UI tasks.",
      "Quota Freeze Invariant: Comply with parent Quota Freeze by entering IDLE state and NEVER killing subordinate workers (Zero-Kill).",
    ],
    reflexiveQuestions: [
      "Am I managing leases, DAG waves, and gates rather than editing code or fixing files myself?",
      "Are all dispatched Tier 3 workers operating with non-overlapping write scopes and valid leases?",
      "Have I applied rigorous scepticism and pushed back on unverified or qualitative-only validator reports?",
      "Is every gate proven and verified before marking tasks complete?",
      "Am I preserving all running Tier 3 workers in an IDLE state without killing them during Quota Freeze?",
    ],
  },
};

export const SEVERITY_WEIGHTS: Readonly<Record<DriftSeverity, number>> = {
  none: 0,
  low: 0.1,
  medium: 0.25,
  high: 0.5,
  critical: 1.0,
};
