export {
  AI_VENDOR_PATTERN,
  ATTRIBUTION_TRAILER_KEYS,
  type AttributionRule,
  type AttributionViolation,
  auditCommitMessage,
  type CommitMessageAudit,
  computeIsMain,
  CONVENTIONAL_COMMIT_TAGS,
  CONVENTIONAL_SUBJECT_PATTERN,
  extractSubjectLine,
  FORBIDDEN_TRAILER_KEYS,
  formatViolationReport,
  main,
  MAX_SUBJECT_LENGTH,
  runCommitMsgGuard,
  type SubjectLineInfo,
} from "./commit-msg-guard.ts";
export {
  FAIL_CLOSED_ERROR_MESSAGE,
  STANDARD_HOOK_NAMES,
  buildGitHookTemplate,
  computeIsHookTemplateMain,
  hardenGitHooksDirectory,
  hardenHookFile,
  hardenHookScript,
  installGitHook,
  isHookFailingClosed,
  runHookHardener,
} from "./hook-template.ts";
export { computeIsHardenHooksMain, executeHardenHooksCli } from "./harden-hooks.ts";
