/**
 * Lane 10: Authority Domain Root Test Facade.
 * Re-exports domain facades across all 8 subdomains:
 * - session/
 * - grants/
 * - rbac/
 * - tokens/
 * - manifest/
 * - persona/
 * - review/
 * - watchdog/
 */

// 1. Session Subdomain
export {
  enableInMemorySessionStore,
  disableInMemorySessionStore,
  clearInMemorySessionStore,
  isInMemorySessionStoreEnabled,
  getInMemorySessionStore,
  setInMemorySessionData,
  getInMemorySessionData,
  deleteInMemorySessionData,
  readPersistedSession,
  secureReadSession,
  formatSafeErrorCause,
  readOwnDataString,
  inferCanExecute,
  snapshotSession,
  restoreSnapshotIfUnchanged,
  withSessionAuthorityLock,
  assertActiveCapsuleLease,
  registerSessionGrant,
  registerInMemorySessionGrant,
  stageSessionGrant,
  rollbackStagedSessionGrant,
  revokeSessionGrant,
  pruneStaleSessions,
  isSessionLedgerBacked,
  resolveActiveSession,
  autoDeriveCallerIdentity,
  requireTurn1Registration,
  resolveGlobalSessionsDir,
  resolveSessionRepositoryRoot,
  resolveCapsuleStateCandidate,
  assertSafeSessionComponent,
  assertSessionPid,
  sameInode,
  type SessionIdentity,
  type SessionSnapshot,
  type StagedSessionGrant,
  type RegisterSessionOptions,
  type ResolveSessionOptions,
} from "./session/index.ts";

// 2. Grants Subdomain
export {
  assertCoordinatorPreToolGuard,
  isCoordinatorFileEditForbidden,
  isCoordinatorRole,
  RootDirectoryHygieneGuard,
  acquireAuditorLeaseLock,
  releaseAuditorLeaseLock,
  readAuditorLeaseLock,
  assertSingletonSkillAuditor,
  defaultIsPidAlive,
  DEFAULT_AUDITOR_LEASE_DURATION_MS,
  DEFAULT_AUDITOR_LOCK_FILE,
  validateSubagentSpawnRequest,
  rejectDuplicateAuditorSpawn,
  isSingletonAuditorRole,
  DEFAULT_SINGLETON_AUDITOR_ROLE,
  DUPLICATE_SINGLETON_AUDITOR_MESSAGE,
  TimerProtectionGuard,
  type AuditorLeaseLock,
  type AcquireAuditorLeaseOptions,
  type ReleaseAuditorLeaseOptions,
  type SubagentSpawnRequest,
  type SpawnValidationResult,
  type CallerContext,
  type ManagedTaskContext,
} from "./grants/index.ts";

// 3. RBAC Subdomain
export {
  verifyCommandAuthorization,
  executeShieldedCommand,
  isWholeSuiteTestCommand,
  isUnauthorizedGitMutation,
  isPermittedCliTool,
  isShieldedMutationCommand,
  inferRoleFromActorId,
  evaluateSupervisoryState,
  constructSupervisoryPersonaReminder,
  computeScopeOverlaps,
  parseTimeMs,
  STANDING_CHECKLIST_DEFINITIONS,
  DECISION_PROTOCOLS,
  type SupervisoryReminderEvaluationContext,
  type SupervisoryEvaluationResult,
  type SupervisoryPersonaReminder,
  type SupervisoryViolation,
  type ScopeOverlap,
} from "./rbac/index.ts";

// 4. Tokens Subdomain
export {
  identifyExecutionContext,
  formatThreadIdentificationBrief,
  detectHostApp,
  buildCapabilitiesProfile,
  parseTierValue,
  roleToTier,
  agentIdToRole,
  agentIdToTier,
  validateTierSpawning,
  parseStandardAgentId,
  isStandardAgentId,
  recommendStandardAgentId,
  validateAgentNamingConvention,
  recordDefect,
  normalizeRoleKey,
  resolveAgentHostConfiguration,
  verifyMilestoneEvidence,
  verifyEventsHashChain,
  inspectCommandReceipts,
  inspectMilestoneEvents,
  TIER_NAMES,
  MAIN_THREAD_ADVISORY,
  type ExecutionTier,
  type ThreadExecutionContext,
  type DefectRecord,
  type ParsedStandardAgentId,
} from "./tokens/index.ts";

// 5. Manifest Subdomain
export {
  parseYaml,
  parseMarkdownFrontmatter,
  parseRoleContract,
  parseAgentManifest,
  loadRoleContract,
  loadAgentManifest,
  loadUnifiedAgentModel,
  listAvailableRoles,
  listAvailableManifests,
  clearManifestCache,
  findSkillRoot,
  normalizeRoleName,
  parseUnifiedAgentManifest,
  validateUnifiedAgentManifest,
  type AgentManifest,
  type RoleContract,
  type UnifiedAgentModel,
  type UnifiedAgentManifest,
} from "./manifest/index.ts";

// 6. Persona Subdomain
export {
  COGNITIVE_PILLARS,
  COGNITIVE_PILLARS_COUNT,
  COGNITIVE_PILLARS_MAP,
  COGNITIVE_PILLARS_BY_CODE,
  PILLAR_1_CLI_FIRST,
  PILLAR_2_VISUAL_TRUTH,
  PILLAR_3_THREAD_AUTHORITY,
  PILLAR_4_PERPETUAL_SELF_EVOLUTION,
  PILLAR_5_GRAPH_INTEROPERABILITY,
  PILLAR_6_FIRST_PRINCIPLES,
  PILLAR_7_INFINITE_CADENCE,
  getAllCognitivePillars,
  getCognitivePillar,
  getPillarAuditQuestions,
  formatPillarsMarkdown,
  formatPillarsBrief,
  evaluateReflexiveSelfAudit,
  formatReflexiveAuditEvaluation,
  generateWatchdogPersonaGrounding,
  buildWatchdogAuditPrompt,
  createWatchdogTickReminder,
  getRoleBoundaryProfile,
  getAllRoleBoundaryProfiles,
  isSupervisoryRole,
  normalizeSupervisoryRole,
  SUPERVISORY_ROLE_BOUNDARIES,
  VerbatimRoleInjector,
  type CognitivePillar,
  type CognitivePillarId,
  type SupervisoryRole,
  type ReflexiveAuditContext,
  type ReflexiveAuditEvaluation,
  type RoleBoundaryProfile,
  type StagnationTelemetry,
  type RolePromptOptions,
  type MindInitOptions,
  type SupervisoryInitOptions,
  type SubagentSystemPromptOptions,
  type SubagentDispatchContext,
} from "./persona/index.ts";

// 7. Review Subdomain
export {
  SUPERFICIAL_PATTERNS,
  rejectSuperficialClaims,
  detectDomainBatching,
  evaluateCounterfactualEvidence,
  auditTaskVerificationEvidence,
  createPushbackHistory,
  appendPushbackRound,
  evaluateRepairProgression,
  isRepairExhausted,
  generateCorrectiveGuidance,
  validateReviewPushbackInput,
  validateReviewPushbackCriteria,
  type TaskVerificationEvidenceInput,
  type TaskVerificationCheckInput,
  type CounterfactualEvidenceItem,
  type PushbackRound,
  type PushbackHistory,
} from "./review/index.ts";

// 8. Watchdog Subdomain
export {
  loadWatchdogStore,
  saveWatchdogStore,
  resolveWatchdogStorePath,
  createDefaultWatchdogStore,
  registerWatchdog,
  heartbeatWatchdog,
  terminateWatchdog,
  terminatePhaseWatchdogs,
  cleanupPreviousPhaseWatchdogs,
  cleanupStaleWatchdogs,
  listWatchdogs,
  verifyWatchdogLifecycle,
  renderAsciiWatchdogTable,
  parseTimestamp,
  withWatchdogStoreLock,
  setWatchdogLockTimingForTesting,
  DEFAULT_HEARTBEAT_CADENCE_MS,
  DEFAULT_WATCHDOG_TIMEOUT_MS,
  type WatchdogRecord,
  type WatchdogStore,
  type WatchdogPhase,
  type WatchdogStatus,
} from "./watchdog/index.ts";

// 9. Virtual Fixture
export {
  setupVirtualAuthorityFS,
  cleanupVirtualAuthorityFS,
  getVirtualAuthorityFS,
} from "./fixture.ts";
