export {
  verifyCommandAuthorization,
  executeShieldedCommand,
  acquireBroadTestLock,
  guardBroadTestExecution,
  type CommandAuthResult,
  type CommandExecResult,
  type ShieldedCommandOptions,
} from "./command-authorizer.ts";

export {
  inferActorRole,
  inferRoleFromActorId,
  isAnyTestRun,
  isCoordinatorRole,
  isFileMutationCommand,
  isShieldedMutationCommand,
  isSupervisorOrValidatorRole,
  isUnauthorizedGitMutation,
  isWholeSuiteTestRun,
  isWholeSuiteTestCommand,
  isTestFileArgument,
  extractGitSubcommand,
  inspectShellEval,
  isBroadTestRun,
  requiresBroadTestLock,
  canBypassBroadTestLock,
  isTargetedTestRun,
  isPermittedCliTool,
} from "./command-predicates.ts";
