import { FORBIDDEN_VALIDATOR_COMMANDS } from "./authority.ts";
import type { RoleCapabilityEntry, RoleCapabilityMatrix, RoleExecutionTier } from "./types.ts";

const SUP_FORBIDDEN = [
  "task:claim",
  "task:submit",
  "shell",
  "run_command",
  "edit_file",
  "write_to_file",
];

const COORD_SPAWNS = [
  "implementer",
  "validator",
  "publisher",
  "completeness-critic",
  "planner",
  "plan-validator",
  "validator-code-quality",
  "validator-product",
  "validator-security",
  "validator-system-design",
  "validator-ui-design",
];

const PUB_CMDS = [
  "worktree:land",
  "worktree:clean",
  "worktree:status",
  "task:check",
  "doctor",
  "whoami",
  "msg:send",
  "msg:recv",
];

const mk = (
  role: string,
  tier: RoleExecutionTier,
  profile: RoleCapabilityEntry["profile"],
  flags: string,
  allowedCommands: readonly string[],
  forbiddenCommands: readonly string[],
  allowedSpawns: readonly string[],
  invariants: readonly string[],
): [string, RoleCapabilityEntry] => [
  role,
  {
    role,
    tier,
    profile,
    canWriteCode: flags.includes("w"),
    canExecuteCommands: flags.includes("x"),
    canSpawnSubagents: flags.includes("s"),
    canClaimLeases: flags.includes("l"),
    allowedCommands,
    forbiddenCommands,
    allowedSpawns,
    invariants,
  },
];

const mkVal = (
  role: string,
  invariants: readonly string[],
  profile: RoleCapabilityEntry["profile"] = "adversarial",
): [string, RoleCapabilityEntry] => [
  role,
  {
    role,
    tier: 3,
    profile,
    canWriteCode: false,
    canExecuteCommands: false,
    canSpawnSubagents: false,
    canClaimLeases: false,
    allowedCommands: [],
    forbiddenCommands: [...FORBIDDEN_VALIDATOR_COMMANDS],
    allowedSpawns: [],
    invariants,
  },
];

export const CANONICAL_ROLE_CAPABILITIES: RoleCapabilityMatrix = Object.fromEntries([
  mk(
    "mind",
    0,
    "deliberate",
    "xs",
    ["bun harness.ts *", "git status", "git diff", "git log"],
    ["run:exec", ...SUP_FORBIDDEN],
    ["orchestrator", "mind-auditor", "skill-auditor"],
    ["SUPERVISOR_ZERO_CODE_EDITS", "NO_RAW_JSONL_READS"],
  ),
  mk(
    "orchestrator",
    1,
    "deliberate",
    "xs",
    ["bun harness.ts *"],
    SUP_FORBIDDEN,
    ["coordinator"],
    ["SUPERVISOR_ZERO_CODE_EDITS", "UNIDIRECTIONAL_DELEGATION"],
  ),
  mk("coordinator", 2, "default", "xs", ["bun harness.ts *"], SUP_FORBIDDEN, COORD_SPAWNS, [
    "SUPERVISOR_ZERO_CODE_EDITS",
  ]),
  mk(
    "implementer",
    3,
    "default",
    "wxsl",
    ["bun harness.ts *", "bun test *", "git diff", "git status"],
    ["authority:decide", "mind:admit", "mind:rotate"],
    ["sub-implementer", "sub-validator", "sub-investigator"],
    ["STRICT_LEASE_CONFINEMENT", "ZERO_ANY_INVARIANT", "ZERO_SUPPRESSIONS_INVARIANT"],
  ),
  mkVal("validator", ["ANTI_BOUNDARY_LEAK", "COGNITIVE_HARD_LOCK", "READ_ONLY_OBSERVER"]),
  mkVal("completeness-critic", ["ANTI_BOUNDARY_LEAK", "COGNITIVE_HARD_LOCK"]),
  mk(
    "planner",
    2,
    "deliberate",
    "x",
    ["bun harness.ts plan:*", "bun harness.ts msg:*"],
    ["edit_file", "write_to_file", "task:claim"],
    [],
    ["MANDATORY_BRAINSTORM_BEFORE_COMPILE", "SUPERVISOR_ZERO_CODE_EDITS"],
  ),
  mkVal("plan-validator", ["REJECT_SHALLOW_UMBRELLA_COMPRESSION", "ANTI_BOUNDARY_LEAK"]),
  mk(
    "publisher",
    3,
    "default",
    "wxl",
    PUB_CMDS,
    ["authority:decide", "mind:admit"],
    [],
    ["PUBLISHER_TRANSACTION_ISOLATION", "ZERO_SOURCE_EDITS", "ATOMIC_RELEASE_ONLY"],
  ),
  mk(
    "sub-implementer",
    3,
    "default",
    "wxl",
    ["bun harness.ts *", "bun test *"],
    ["authority:decide", "mind:admit"],
    [],
    ["LEAF_WORKER_CONFINEMENT"],
  ),
  mkVal("sub-validator", ["ANTI_BOUNDARY_LEAK", "COGNITIVE_HARD_LOCK"]),
  mkVal("sub-investigator", ["READ_ONLY_CONFINEMENT"], "cheap_bulk"),
  mk(
    "ui-headless-validator",
    3,
    "default",
    "x",
    ["run:exec", "task:brief", "task:check", "task:submit", "doctor", "whoami"],
    ["edit_file", "write_to_file", "task:claim", "authority:decide", "mind:admit", "mind:rotate"],
    [],
    ["ZERO_SOURCE_EDITS", "NO_TEST_RE_RUNS", "MANDATORY_SCREENSHOT_CAPTURE_ALL_4_VIEWPORTS"],
  ),
  mk(
    "ui-optical-validator",
    3,
    "adversarial",
    "s",
    ["finding:get", "report:get", "evidence:get", "evidence:screenshots", "whoami"],
    [...FORBIDDEN_VALIDATOR_COMMANDS],
    ["sub-validator"],
    ["ANTI_BOUNDARY_LEAK", "COGNITIVE_HARD_LOCK", "SOURCE_CODE_BLINDNESS_QUARANTINE"],
  ),
  mk(
    "owner",
    "independent",
    "deliberate",
    "wxs",
    ["bun harness.ts *", "authority:decide", "agent:register", "doctor"],
    [],
    ["mind", "orchestrator", "coordinator"],
    ["GENESIS_AUTHORITY_CONFERRAL", "FAIL_CLOSED_RBAC"],
  ),
  mk(
    "independent-planner",
    "independent",
    "deliberate",
    "",
    ["msg:send", "msg:recv", "msg:poll"],
    ["edit_file", "write_to_file", "task:claim", "run_command"],
    [],
    ["COMPLETE_HARNESS_DECOUPLING", "PURE_ENGLISH_CONCEPTUAL_STANDARD"],
  ),
]);
