export type {
  AggregatedDefect,
  DefectCategory,
  DefectEntry,
  DefectHypothesis,
  DefectKeyOptions,
  DefectOccurrence,
  DefectRecordInput,
  DefectRemediationAction,
  DefectResolutionProof,
  DefectSeverity,
  DefectStatus,
  HistoricalOccurrence,
  LiveDeduplicationOptions,
  ParseDefectLogOptions,
} from "../../../logging/defects/index.ts";
