// Main summary module canonical facade

export type {
  ActionKind,
  ActionOutcome,
  ActionStepRecord,
  ActionTarget,
  ArchivedRoundContext,
  ArchivedRoundNodesInput,
  BadgeDetail,
  BranchSubgraph,
  BranchSubgraphInput,
  BrowserTestRun,
  BrowserTestViewport,
  CoreNodeInput,
  CoreNodes,
  CriticNodeInput,
  CriticNodes,
  DagNodeSummary,
  DagWaveMetrics,
  DependencyForensicItem,
  EdgeContainerDetail,
  EdgeExchange,
  EdgeKind,
  EdgeSpec,
  EdgeTrafficDetail,
  EdgeVariant,
  ExchangeFinding,
  ExchangeTransferredFile,
  ExchangeType,
  FileRef,
  FindingDetail,
  GraphDataset,
  GraphEdgeData,
  GraphGeneratorInput,
  GraphNodeData,
  GraphSection,
  IoPort,
  MediaAsset,
  NamedBrowserTestViewport,
  NodeFinding,
  NodeKind,
  NodeMetadata,
  NodeMetrics,
  NodeRole,
  NodeScript,
  NodeStateTransition,
  NodeStatus,
  NodeTelemetry,
  NodeTool,
  NodeValidatorDomain,
  ObservedTraffic,
  PayloadKind,
  PlanValidatorNodesInput,
  RunCompletionFacts,
  RunEnhancedPlanFacts,
  RunFacts,
  RunFactsInput,
  RunIntegrityFacts,
  RunPromptFacts,
  RunReportFacts,
  RunRepositoryFacts,
  RunRequirementFacts,
  TaskEdgeFactoryParams,
  TaskNodeContext,
  TaskPreparationInput,
  VisualDagRenderOptions,
  VisualDagWave,
} from "./graph/index.ts";

export {
  AssetRegistry,
  activeAgentBadge,
  buildArchivedRoundNodes,
  buildBranchSubgraphs,
  buildCriticAndTerminalNodes,
  buildGateNode,
  buildImplementerNode,
  buildPlanValidatorNodes,
  buildPromptAndPlanNodes,
  buildRunFacts,
  buildTaskEdges,
  buildValidatorNode,
  commandDurationMs,
  commandLogBytes,
  computeArchivedRounds,
  createEdge,
  dispatchExchange,
  evidenceExchange,
  findingExchanges,
  formatBox,
  generateGraphDataset,
  mapGateStatus,
  mapTaskStatus,
  prepareTaskContext,
  projectFindingsForNode,
  renderAsciiDag,
  renderNodeBox,
  renderVisualDag,
  reportBytes,
  resolveImplementerId,
  resolveValidatorId,
  statusBadge,
  statusGlyph,
  submissionExchange,
  transferredFiles,
  verdictExchange,
  visualizeDag,
} from "./graph/index.ts";

export type {
  AgentLedgerView,
  DetectHostIdentityOptions,
  FileChurnRecord,
  HostCapabilities,
  HostIdentity,
  HostTelemetryProbe,
  MetricsInput,
  PushbackRoundRecord,
  RollupMetrics,
  StepAssignments,
  TaskTimestampSummary,
  TimelineEventRecord,
  TimingBreakdown,
  TokenEstimation,
  TokenUsageDetail,
  ValidationInterval,
  WaveSource,
} from "./metrics/index.ts";

export {
  buildNodeTelemetry,
  buildNodeTools,
  collectActionSteps,
  collectMetrics,
  collectTimeline,
  computeExecutionSteps,
  computeGateTiming,
  computeGateTokens,
  computeTaskTiming,
  computeTaskTokens,
  computeWallDurationMs,
  detectHostIdentity,
  detectHostTelemetry,
  extractTaskTimestamps,
  narrateUnclassifiedEvent,
  parseDurationMs,
  readAgentLedgerView,
  reportedTokenUsage,
} from "./metrics/index.ts";

export type {
  AdjacentFindingView,
  AsciiBranch,
  AsciiGraphInput,
  AsciiSubTask,
  AsciiTask,
  AsciiWave,
  AttributedFileRef,
  ChecklistCoverageItemView,
  CommandView,
  CriticReportView,
  DispositionView,
  EnhancedPlanView,
  GateView,
  LogRead,
  MarkdownFormatterInput,
  PlanEntryView,
  ReportContext,
  ReportContextInput,
  RequirementView,
  TaskChecklistCoverageView,
  TaskCommandPartition,
} from "./markdown/index.ts";

export {
  LOG_READ_CEILING_BYTES,
  UNKNOWN,
  buildNodeScripts,
  buildReportContext,
  buildStateTransitions,
  cell,
  code,
  evidenceLabel,
  evidencedText,
  fence,
  fileProvenanceDetails,
  fileProvenanceTable,
  formatDuration,
  formatSummaryMarkdown,
  isCriticCommand,
  joinOrNone,
  joinOrUnknown,
  note,
  numberOrUnknown,
  partitionTaskCommands,
  readBranches,
  readCommands,
  readCriticReport,
  readDispositions,
  readEnhancedPlan,
  readGates,
  readGraphRevision,
  readLog,
  readLogText,
  readRequirements,
  readTaskChecklistCoverage,
  readTopologyRecord,
  renderActionProvenance,
  renderAgents,
  renderBranches,
  renderChecklistCoverage,
  renderCritic,
  renderEnhancedPlan,
  renderFilesChanged,
  renderGates,
  renderOriginalPrompt,
  renderPhases,
  renderProbesAndPushbacks,
  renderRequirements,
  renderRunIdentity,
  renderScripts,
  renderTaskGraphAscii,
  renderTaskGraphSection,
  renderTaskTrajectory,
  renderTelemetry,
  renderTimeline,
  renderTools,
  renderTopology,
  section,
  table,
  textOrUnknown,
  toolRefText,
} from "./markdown/index.ts";

export type {
  AssetMapOptions,
  AssetMeasurement,
  AssetScope,
  AssetSink,
  FindingDetailsOptions,
  IndexProvider,
} from "./assets/index.ts";

export {
  collectCriticEvidenceAssets,
  collectFindingAssets,
  collectReportAssets,
  collectValidationAssets,
  extractFindingScreenshots,
  extractMediaPaths,
  getMimeTypeForUrl,
  inferAssetProps,
  isImageExtension,
  mapFindingDetails,
  mapMediaAssets,
  mapRunScreenshotAssets,
  measureAssets,
  measureCapsuleAsset,
  readHeader,
} from "./assets/index.ts";

export type { SummaryGenerationOptions, SummarySuite } from "./formatters/index.ts";

export {
  buildNodeBrowserTests,
  enrichFileRefsWithDiffs,
  generateSummarySuite,
  loadCommandsFromDir,
} from "./formatters/index.ts";
