// @ts-nocheck
export { HarnessError } from "./errors/index.ts";
export type { JsonValue, JsonObject, JsonPrimitive } from "./contracts/index.ts";
export { type SyncDirectoryReader, collectBoundedDirectoryEntries } from "./bounded-directory.ts";
export type {
  DualTimeRecord,
  DurationResult,
  ActionTelemetry,
  SubagentStatus,
  SubagentLifecycleTelemetry,
  ToolExecutionStatus,
  ToolExecutionTelemetry,
  TestStatus,
  IndividualTestTiming,
  UnitTestTelemetry,
  SchedulerWatchdogTelemetry,
  StepMachineTelemetry,
} from "./dual-time/index.ts";
export {
  isDualTimeRecord,
  isActionTelemetry,
  isSubagentLifecycleTelemetry,
  isToolExecutionTelemetry,
  isUnitTestTelemetry,
  isSchedulerWatchdogTelemetry,
  isStepMachineTelemetry,
  extractTimestampMs,
  getDualTime,
  formatDualTimeDisplay,
  formatDuration,
  calculateDuration,
  createActionTelemetry,
  createSubagentLifecycleTelemetry,
  updateSubagentLifecycle,
  createToolExecutionTelemetry,
  createUnitTestTelemetry,
  calculateDrift,
  createSchedulerWatchdogTelemetry,
  createStepMachineTelemetry,
  updateStepMachineTelemetry,
} from "./dual-time/index.ts";
export {
  type DurableWriteStep,
  type AtomicWriteOptions,
  type DurableAppendOptions,
  type DurableAppendDependencies,
  fsyncDirectory,
  atomicWriteBytes,
  durableAppendBytes,
  atomicWriteJson,
} from "./durable-write.ts";
export {
  type JsonReadLimits,
  canonicalJsonBytes,
  sha256Bytes,
  parseJsonBytes,
  readBoundedBytes,
  readCanonicalObject,
  normalizeJson,
  jsonCopy,
  sameJson,
} from "./json.ts";
export { readRegularFileNoFollow } from "./no-follow.ts";
export { safeRepoPath } from "./paths.ts";
export {
  CAPSULES_DIR_NAME,
  OLT_DIR_NAME,
  OLT_FILES,
  findRepoRoot,
  isInsideCapsule,
  isTestEnvironment,
  loadSkillGlobalConfig,
  resolveBacklogPath,
  resolveCapsulesDir,
  resolveCompletedDefectsPath,
  resolveCompletedTasksPath,
  resolveDefectsPath,
  resolveEvidenceDir,
  resolveMemoryPath,
  resolveOltDir,
  resolvePolicyPath,
  resolveQuotaDagSnapshotPath,
  resolveScratchDir,
  resolveSkillGlobalConfigPath,
  resolveSkillHomeRepo,
  resolveTelemetryPath,
  resolveWatchdogsPath,
  stripCapsulePath,
  type SkillGlobalConfig,
} from "./shared/paths.ts";
export {
  RESTRICTED_GIT_ENVIRONMENT,
  RESTRICTED_GIT_ARGUMENTS,
  restrictedRepositoryGitArgv,
  isGitArgv,
  isRestrictedGitDiffArgv,
  restrictedGitDiffArgv,
} from "./restricted-git.ts";
export { includeRuntimeSourceEntry } from "./runtime-filter.ts";
export { type RuntimeSnapshot, runtimeTreeSnapshot, copyPinnedRuntime } from "./runtime-tree.ts";
export {
  assertZeroAny,
  scanSourceCodeForAny,
  scanFileForAny,
  scanDirectoryForAny,
  collectTsFiles,
  isTypeSafetyViolation,
  isTypeSafetyScanResult,
  type TypeSafetyViolation,
  type TypeSafetyScanResult,
  type TypeSafetyScanOptions,
} from "./type-safety/index.ts";
export type {
  AdaptiveAdjustmentReason,
  AdaptiveTimerConfig,
  AdaptiveTimerState,
  AntiIdleIntervalOptions,
  AntiIdleIntervalResult,
  BackoffStrategy,
  BackoffStrategyOptions,
  CompositeSeedOptions,
  IntervalAdjustmentResult,
  JitterOptions,
} from "./scheduling/index.ts";
export {
  AdaptiveTimerController,
  DEFAULT_ADAPTIVE_ACTIVITY_BOOST,
  DEFAULT_ADAPTIVE_BACKOFF_FACTOR,
  DEFAULT_ADAPTIVE_MAX_INTERVAL_MS,
  DEFAULT_ADAPTIVE_MIN_INTERVAL_MS,
  DEFAULT_BASE_INTERVAL_MS,
  DEFAULT_JITTER_RATIO,
  DEFAULT_MAX_INTERVAL_MS,
  DEFAULT_MAX_PAUSE_INTERVAL_MS,
  DEFAULT_WATCHDOG_HEARTBEAT_INTERVAL_MS,
  MAX_JITTER_RATIO,
  MIN_INTERVAL_MS,
  MIN_JITTER_RATIO,
  QUIESCENCE_INTERVAL_MULTIPLIER,
  applyIntervalJitter,
  calculateBackoffWithStrategy,
  calculateDeterministicInterval,
  calculateExponentialBackoff,
  computeAntiIdleInterval,
  createCompositeSeed,
  createDeterministicRandom,
  fnv1a32,
  formatIntervalDuration,
  parseDuration,
  parseIntervalDuration,
  projectIntervalProgression,
} from "./scheduling/index.ts";
export type {
  EpistemicGrade,
  EpistemicVector,
  EpistemicEvaluationInput,
  EpistemicConfidenceResult,
  EpistemicWeights,
  EvaluateEpistemicOptions,
  EpistemicRecord,
  EpistemicQueryPredicate,
  EpistemicQueryOrder,
  EpistemicQueryProjection,
  EpistemicQuery,
  EpistemicQueryAggregate,
  EpistemicQueryPlan,
  EpistemicQueryResult,
  EpistemicEventType,
  EpistemicStreamEvent,
  StreamSubscription,
  StreamSubscriber,
  StreamErrorHandler,
  ReplayedEpistemicState,
  EpistemicStateSnapshot,
  EpistemicStateDiff,
} from "./epistemic/index.ts";
export {
  DEFAULT_EPISTEMIC_WEIGHTS,
  DEFAULT_PASS_THRESHOLD,
  clamp,
  calculateEpistemicGrade,
  computeWeightedEpistemicScore,
  computeEpistemicEntropy,
  computeEvidenceConfidence,
  computeShannonEntropy,
  computeWilsonScoreInterval,
  evaluateEpistemicConfidence,
  EpistemicIndexStore,
  EpistemicQueryOptimizer,
  computeEpistemicAggregate,
  matchesEpistemicPredicate,
  EpistemicEventBus,
  EpistemicEventJournal,
  EpistemicEventStream,
  EpistemicStateReplayer,
  diffEpistemicStates,
  reconstructEpistemicState,
  buildSparseIndexFromState,
} from "./epistemic/index.ts";
