import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import * as path from "node:path";
import { setupVirtualMindFS, cleanupVirtualMindFS, scratchRoot } from "../../fixtures/mind-fixture.ts";
import {
  executeAutonomousMindInit,
  AutonomousMindInitializer,
  resolveOrGenerateCharter,
  DEFAULT_STANDARD_CHARTER_YAML,
} from "../../../../olt/scripts/src/mind/lifecycle/mind-init-flow.ts";
import { mindInitCommand } from "../../../../olt/scripts/src/cli/commands/mind-init.ts";
import { MIND_COMMANDS } from "../../../../olt/scripts/src/cli/registry/mind/index.ts";
import type { VirtualMemoryFS } from "../../../../olt/scripts/src/testing/virtual-fs/index.ts";

describe("Wave 4: Single-Touch Autonomous Mind Initialization & Flow", () => {
  let vfs: VirtualMemoryFS;
  let testDir: string;

  beforeEach(() => {
    vfs = setupVirtualMindFS();
    testDir = scratchRoot("mind-init-flow");
    vfs.mkdirSync(path.join(testDir, ".olt"), { recursive: true });
  });

  afterEach(() => {
    cleanupVirtualMindFS();
  });

  describe("Charter Resolution & Auto-Generation", () => {
    test("auto-generates standard default charter when none exists", () => {
      const resolved = resolveOrGenerateCharter(testDir);
      expect(resolved.autoGenerated).toBe(true);
      expect(vfs.existsSync(resolved.fullPath)).toBe(true);
      expect(resolved.text).toContain("identity:");
      expect(resolved.text).toContain("G1");
      expect(resolved.text).toContain("70/20/10 Innovation Portfolio");
    });

    test("auto-detects existing olt/agents/mind.yaml in the skill-home repo", () => {
      const skillScriptsDir = path.join(testDir, "olt", "scripts");
      vfs.mkdirSync(skillScriptsDir, { recursive: true });
      vfs.writeFileSync(path.join(skillScriptsDir, "harness.ts"), "", "utf-8");
      const agentsDir = path.join(testDir, "olt", "agents");
      vfs.mkdirSync(agentsDir, { recursive: true });
      const charterPath = path.join(agentsDir, "mind.yaml");
      vfs.writeFileSync(charterPath, DEFAULT_STANDARD_CHARTER_YAML, "utf-8");

      const resolved = resolveOrGenerateCharter(testDir);
      expect(resolved.autoGenerated).toBe(false);
      expect(resolved.fullPath).toBe(charterPath);
      expect(resolved.text).toContain("identity:");
    });

    test("uses explicitly provided charter path", () => {
      const customPath = path.join(testDir, "custom-charter.yaml");
      vfs.writeFileSync(customPath, DEFAULT_STANDARD_CHARTER_YAML, "utf-8");

      const resolved = resolveOrGenerateCharter(testDir, customPath);
      expect(resolved.autoGenerated).toBe(false);
      expect(resolved.fullPath).toBe(customPath);
    });

    test("resolves relative custom charter path correctly", () => {
      const relDir = path.join(testDir, "config");
      vfs.mkdirSync(relDir, { recursive: true });
      const relPath = path.join(relDir, "custom-charter.yaml");
      vfs.writeFileSync(relPath, DEFAULT_STANDARD_CHARTER_YAML, "utf-8");

      const resolved = resolveOrGenerateCharter(testDir, "config/custom-charter.yaml");
      expect(resolved.autoGenerated).toBe(false);
      expect(resolved.fullPath).toBe(relPath);
    });

    test("falls back to generating default charter when custom path does not exist", () => {
      const resolved = resolveOrGenerateCharter(testDir, "non-existent-charter.yaml");
      expect(resolved.autoGenerated).toBe(true);
      expect(resolved.fullPath).toBe(path.join(testDir, ".olt", "mind.yaml"));
      expect(vfs.existsSync(resolved.fullPath)).toBe(true);
    });
  });

  describe("3-Stage Autonomous Initialization Execution", () => {
    test("executes all 3 stages, pins bedrock invariants, and initializes sovereign execution loop", async () => {
      const result = await executeAutonomousMindInit({
        repo: testDir,
        simulateProbes: true,
        actor: "owner",
        mindId: "mind-gen-1",
      });

      expect(result.snapshot).toBeDefined();
      expect(result.snapshot.snapshotId).toBeDefined();
      expect(result.intent).toBeDefined();
      expect(result.intent.priority).toBe("P1");
      expect(result.p1_deliverable).toBeDefined();
      expect(result.p1_deliverable.priority).toBe("P1");

      expect(result.deficit_topology).toBeDefined();
      expect(result.deficit_topology.summary).toBeDefined();
      expect(result.deficit_topology.summary.healthStatus).toBeDefined();
      expect(result.deficit_topology.recommendedRoadmapAllocation).toBeDefined();

      expect(result.governance).toBeDefined();
      expect(result.governance.ready).toBe(true);
      expect(result.companions).toBeDefined();
      expect(result.companions.deployed).toBe(true);
      expect(result.companions.mindAuditorId).toBe("mind-gen-1-mind-auditor");
      expect(result.companions.skillAuditorId).toBe("mind-gen-1-skill-auditor");

      expect(result.mobilized_hierarchy.length).toBeGreaterThanOrEqual(4);
      const roles = result.mobilized_hierarchy.map((g) => g.role);
      expect(roles).toContain("mind");
      expect(roles).toContain("mind-auditor");
      expect(roles).toContain("skill-auditor");
      expect(roles).toContain("orchestrator");

      expect(vfs.existsSync(result.dashboard.md_path)).toBe(true);
      expect(vfs.existsSync(result.dashboard.json_path)).toBe(true);
      const dashboardMd = vfs.readFileSync(result.dashboard.md_path, "utf-8");
      expect(dashboardMd).toContain("Executive Runtime Trajectory");
      expect(dashboardMd).toContain("Innovation Portfolio Balance");
      expect(dashboardMd).toContain("Bedrock Invariants");

      expect(result.cadence_initialized).toBe(true);
      const lastPulsePath = path.join(result.run_root, "last_pulse.json");
      expect(vfs.existsSync(lastPulsePath)).toBe(true);

      expect(result.markdown).toContain("SOVEREIGN AUTONOMOUS MIND INITIALIZED");
      expect(result.markdown).toContain("Stage 1: In-Flight Worktree & User Intent Extraction");
      expect(result.markdown).toContain("Stage 2: Empirical Baseline Probes & Deficit Topology");
      expect(result.markdown).toContain(
        "Stage 3: Strategic Goal Configuration & Mobilized Hierarchy",
      );
    });

    test("AutonomousMindInitializer class operates modularly across all stages", async () => {
      const initializer = new AutonomousMindInitializer({
        repo: testDir,
        simulateProbes: true,
      });

      const inFlight = await initializer.ingestInFlight(testDir);
      expect(inFlight.snapshot).toBeDefined();
      expect(inFlight.intent).toBeDefined();
      expect(inFlight.deliverable).toBeDefined();

      const probeResult = await initializer.probeBaseline(testDir, { simulate: true });
      expect(probeResult.topologyMatrix).toBeDefined();

      const fullResult = await initializer.initialize();
      expect(fullResult.mind_id).toBe("mind-gen-1");
      expect(fullResult.cadence_initialized).toBe(true);
    });
  });

  describe("CLI Command & Registry Integration", () => {
    test("mindInitCommand runs single-touch zero-parameter autonomous initialization", async () => {
      const commandResult = await mindInitCommand({ repo: testDir }, {});

      expect(commandResult.markdown).toBeDefined();
      expect(typeof commandResult.markdown).toBe("string");
      expect(commandResult.mind_id).toBe("mind-gen-1");
      expect(commandResult.run_root).toBeDefined();
      expect(commandResult.dashboard).toBeDefined();
      expect(commandResult.governance).toBeDefined();
    });

    test("mind:init and mind:bootstrap commands are registered with optional flags", () => {
      const initSpec = MIND_COMMANDS.find((c) => c.name === "mind:init");
      expect(initSpec).toBeDefined();
      const bootstrapSpec = MIND_COMMANDS.find((c) => c.name === "mind:bootstrap");
      expect(bootstrapSpec).toBeDefined();

      const repoFlag = initSpec?.flags.find((f) => f.name === "repo");
      expect(repoFlag?.required).toBe(false);

      const charterFlag = initSpec?.flags.find((f) => f.name === "charter");
      expect(charterFlag?.required).toBe(false);

      const actorFlag = initSpec?.flags.find((f) => f.name === "actor");
      expect(actorFlag?.required).toBe(false);
    });
  });
});
