import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  executeAutonomousMindInit,
  AutonomousMindInitializer,
  resolveOrGenerateCharter,
  DEFAULT_STANDARD_CHARTER_YAML,
  CANONICAL_BEDROCK_INVARIANTS_LIST,
} from "../../../olt/scripts/src/mind/lifecycle/mind-init-flow.ts";
import { mindInitCommand } from "../../../olt/scripts/src/cli/commands/mind-init.ts";
import { MIND_COMMANDS } from "../../../olt/scripts/src/cli/registry/mind/index.ts";

describe("Wave 4: Single-Touch Autonomous Mind Initialization & Flow", () => {
  let testDir: string;

  beforeEach(() => {
    testDir = join(
      tmpdir(),
      `mind-init-test-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    );
    mkdirSync(testDir, { recursive: true });
    mkdirSync(join(testDir, ".olt"), { recursive: true });
  });

  afterEach(() => {
    try {
      rmSync(testDir, { recursive: true, force: true });
    } catch {
      // Cleanup best effort
    }
  });

  describe("Charter Resolution & Auto-Generation", () => {
    test("auto-generates standard default charter when none exists", () => {
      const resolved = resolveOrGenerateCharter(testDir);
      expect(resolved.autoGenerated).toBe(true);
      expect(existsSync(resolved.fullPath)).toBe(true);
      expect(resolved.text).toContain("identity:");
      expect(resolved.text).toContain("G1");
      expect(resolved.text).toContain("70/20/10 Innovation Portfolio");
    });

    test("auto-detects existing olt/agents/mind.yaml", () => {
      const agentsDir = join(testDir, "olt", "agents");
      mkdirSync(agentsDir, { recursive: true });
      const charterPath = join(agentsDir, "mind.yaml");
      writeFileSync(charterPath, DEFAULT_STANDARD_CHARTER_YAML, "utf-8");

      const resolved = resolveOrGenerateCharter(testDir);
      expect(resolved.autoGenerated).toBe(false);
      expect(resolved.fullPath).toBe(charterPath);
      expect(resolved.text).toContain("identity:");
    });

    test("uses explicitly provided charter path", () => {
      const customPath = join(testDir, "custom-charter.yaml");
      writeFileSync(customPath, DEFAULT_STANDARD_CHARTER_YAML, "utf-8");

      const resolved = resolveOrGenerateCharter(testDir, customPath);
      expect(resolved.autoGenerated).toBe(false);
      expect(resolved.fullPath).toBe(customPath);
    });
  });

  describe("3-Stage Autonomous Initialization Execution", () => {
    test("executes all 3 stages, pins bedrock invariants, and initializes sovereign execution loop", async () => {
      const result = await executeAutonomousMindInit({
        repo: testDir,
        simulateProbes: true,
        actor: "owner",
        mindId: "mind-gen-1",
      });

      // Verification of Stage 1: Snapshot & Intent
      expect(result.snapshot).toBeDefined();
      expect(result.snapshot.snapshotId).toBeDefined();
      expect(result.intent).toBeDefined();
      expect(result.intent.priority).toBe("P1");
      expect(result.p1_deliverable).toBeDefined();
      expect(result.p1_deliverable.priority).toBe("P1");

      // Verification of Stage 2: Empirical Baseline & Deficit Topology
      expect(result.deficit_topology).toBeDefined();
      expect(result.deficit_topology.summary).toBeDefined();
      expect(result.deficit_topology.summary.healthStatus).toBeDefined();
      expect(result.deficit_topology.recommendedRoadmapAllocation).toBeDefined();

      // Verification of Stage 3: Mobilized Hierarchy & Dashboard
      expect(result.governance).toBeDefined();
      expect(result.governance.ready).toBe(true);
      expect(result.companions).toBeDefined();
      expect(result.companions.deployed).toBe(true);
      expect(result.companions.mindAuditorId).toBe("mind-gen-1-mind-auditor");
      expect(result.companions.skillAuditorId).toBe("mind-gen-1-skill-auditor");

      // Mobilized Hierarchy includes Mind, Mind Auditor, Skill Auditor, Orchestrator
      expect(result.mobilized_hierarchy.length).toBeGreaterThanOrEqual(4);
      const roles = result.mobilized_hierarchy.map((g) => g.role);
      expect(roles).toContain("mind");
      expect(roles).toContain("mind-auditor");
      expect(roles).toContain("skill-auditor");
      expect(roles).toContain("orchestrator");

      // Live Executive Dashboard files
      expect(existsSync(result.dashboard.md_path)).toBe(true);
      expect(existsSync(result.dashboard.json_path)).toBe(true);
      const dashboardMd = readFileSync(result.dashboard.md_path, "utf-8");
      expect(dashboardMd).toContain("Executive Runtime Trajectory");
      expect(dashboardMd).toContain("Innovation Portfolio Balance");
      expect(dashboardMd).toContain("Bedrock Invariants");

      // Cadence initialized & last_pulse.json recorded
      expect(result.cadence_initialized).toBe(true);
      const lastPulsePath = join(result.run_root, "last_pulse.json");
      expect(existsSync(lastPulsePath)).toBe(true);

      // Markdown brief formatted with rich content
      expect(result.markdown).toContain("SOVEREIGN AUTONOMOUS MIND INITIALIZED");
      expect(result.markdown).toContain("Stage 1: In-Flight Worktree & User Intent Extraction");
      expect(result.markdown).toContain("Stage 2: Empirical Baseline Probes & Deficit Topology");
      expect(result.markdown).toContain("Stage 3: Strategic Goal Configuration & Mobilized Hierarchy");
    });

    test("AutonomousMindInitializer class operates modularly across all stages", async () => {
      const initializer = new AutonomousMindInitializer({
        repo: testDir,
        simulateProbes: true,
      });

      const inFlight = await initializer.ingestInFlight(testDir);
      expect(inFlight.snapshot).toBeDefined();
      expect(inFlight.intent).toBeDefined();
      expect(inFlight.deliverable).toBeDefined();

      const probeResult = await initializer.probeBaseline(testDir, { simulate: true });
      expect(probeResult.topologyMatrix).toBeDefined();

      const fullResult = await initializer.initialize();
      expect(fullResult.mind_id).toBe("mind-gen-1");
      expect(fullResult.cadence_initialized).toBe(true);
    });
  });

  describe("CLI Command & Registry Integration", () => {
    test("mindInitCommand runs single-touch zero-parameter autonomous initialization", async () => {
      const commandResult = await mindInitCommand({ repo: testDir }, {});

      expect(commandResult.markdown).toBeDefined();
      expect(typeof commandResult.markdown).toBe("string");
      expect(commandResult.mind_id).toBe("mind-gen-1");
      expect(commandResult.run_root).toBeDefined();
      expect(commandResult.dashboard).toBeDefined();
      expect(commandResult.governance).toBeDefined();
    });

    test("mind:init and mind:bootstrap commands are registered with optional flags", () => {
      const initSpec = MIND_COMMANDS.find((c) => c.name === "mind:init");
      expect(initSpec).toBeDefined();
      const bootstrapSpec = MIND_COMMANDS.find((c) => c.name === "mind:bootstrap");
      expect(bootstrapSpec).toBeDefined();

      const repoFlag = initSpec?.flags.find((f) => f.name === "repo");
      expect(repoFlag?.required).toBe(false);

      const charterFlag = initSpec?.flags.find((f) => f.name === "charter");
      expect(charterFlag?.required).toBe(false);

      const actorFlag = initSpec?.flags.find((f) => f.name === "actor");
      expect(actorFlag?.required).toBe(false);
    });
  });
});
