export {
  validateCapsuleDiskHygiene,
  validateDensityBudgets,
  validateFacadeExports,
  validateNoBackwardsCompatibilityShims,
  validateRepositoryCodingConventions,
  validateZeroCommentsInCode,
  type CapsuleHygieneValidationResult,
  type CapsuleHygieneViolation,
  type CommentViolation,
  type DensityCheckOptions,
  type DensityValidationResult,
  type DirectoryDensityViolation,
  type FacadeExportViolation,
  type FacadeValidationResult,
  type FileDensityViolation,
  type RepoConventionsCheckOptions,
  type RepoConventionsValidationResult,
  type ShimValidationResult,
  type ShimViolation,
  type ZeroCommentsValidationResult,
} from "./coding-conventions/index.ts";
