export type {
  ClippingViolation,
  CompanionManifestData,
  ContrastViolation,
  CrossChannelProof,
  DualChannelAuditResult,
  DualChannelInput,
  EvaluatedCriterion,
  ManifestCriteriaValidationResult,
  OrphanViolation,
  OverflowViolation,
  PngDimensionRead,
  PngVerificationResult,
  ScreenshotMetadata,
  StackingViolation,
  StructuredFinding,
  ValidateCompanionManifestOptions,
  ViewportMetrics,
  VisualMetricsReport,
} from "./dual-channel-analyzer/index.ts";

export {
  DEFAULT_REQUIRED_VIEWPORTS,
  MANIFEST_INVARIANT,
  MAX_DEVICE_SCALE_FACTOR,
  METRIC_PATTERN,
  PNG_SIGNATURE,
  PROTECTED_VIEWPORT_BANDS,
  SCREENSHOT_INVARIANT,
  SUPERFICIAL_BOILERPLATE_PATTERNS,
  UI_DIR_PATTERNS,
  UI_EXTENSIONS,
  analyzeDualChannel,
  domInvariantsInspected,
  isUiScope,
  measuredWidthOf,
  readPngPixelDimensions,
  resolveScreenshotPath,
  selfReportedDimensionsWithinTolerance,
  validateCompanionManifestCriteria,
  validateCrossChannelConsistency,
  verifyScreenshotPixelDimensions,
} from "./dual-channel-analyzer/index.ts";
