export {
  DEFAULT_DARWIN_AUDIO_COMMAND,
  DEFAULT_DARWIN_SOUND_PATH,
  DEFAULT_HOOK_CONFIG,
  DEFAULT_HOOK_SCHEMA,
  DEFAULT_HOOK_VERSION,
  loadHookConfig,
  parseHookConfig,
  parseHookDefinition,
  resolveHookConfigFile,
  saveHookConfig,
} from "./config.ts";
export {
  ALLOWED_SHELL_EXECUTABLES,
  buildHookChildEnvironment,
  commandContainsRecursiveDelete,
  defaultProcessRunner,
  dispatchLifecycleHook,
  dispatchSingleHook,
  executeAudioAction,
  executeCustomAction,
  executeShellAction,
  executeWebhookAction,
  findForbiddenCommandMatch,
  isAllowedShellExecutable,
  isPlatformSupported,
  matchesEvent,
  resolveAudioSoundPath,
  resolvePinnedHookCwd,
} from "./dispatcher.ts";
export type {
  HookAudioRefusalRule,
  HookCwdResolution,
  HookShellRefusalRule,
  ProcessRunner,
  ProcessRunResult,
} from "./dispatcher.ts";
export type {
  CustomHookHandler,
  HookAction,
  HookActionType,
  HookConfig,
  HookDefinition,
  HookResult,
  KnownLifecycleEvent,
  LifecycleEvent,
} from "./types.ts";
