export {
  acquireFullSuiteTestLock,
  createTestSummaryRecord,
  formatTestSummaryMarkdown,
  getLatestTestSummary,
  guardTestExecution,
  isFullSuiteTestCommand,
  isProcessAlive,
  isTestFilePath,
  readLockPayload,
  resetConcurrencyLockStore,
  resolveLockPath,
  resolveTestSummaryDir,
  saveTestSummary,
  setInMemoryLockPayload,
  type AcquireLockOptions,
  type AcquireLockResult,
  type FullSuiteTestLockPayload,
  type GuardTestExecutionResult,
  type TestSummaryRecord,
} from "./concurrency-lock.ts";

export {
  allocateIsolatedPort,
  allocateIsolatedPorts,
  applyEnvOverrides,
  createTestIsolationContext,
  findRepoRoot,
  getIsolatedTempDir,
  isPortAvailable,
  releaseIsolatedPort,
  removeIsolatedTempDir,
  restoreEnvSnapshot,
  runWithIsolation,
  snapshotEnv,
  withIsolatedEnv,
  withIsolatedEnvSync,
  type AllocatePortOptions,
  type IsolatedTempDirOptions,
  type TestIsolationContext,
  type TestIsolationOptions,
} from "./isolation.ts";

export {
  assertScopedExecutionPolicy,
  auditScopedExecutionCompliance,
  buildScopedTestCommand,
  resolveScopedTestTargets,
  validateMemoryAndCpuConservation,
  type BuildScopedTestCommandOptions,
  type ExecutionBudgetMetrics,
  type ResolveTargetsOptions,
  type ResourceBudgetLimits,
  type ResourceUsageSample,
  type ScopedExecutionAuditParams,
  type ScopedExecutionAuditResult,
  type ScopedExecutionPolicy,
  type ScopedTestTarget,
  type TestFramework,
  type TestRunnerType,
} from "./scoped-execution.ts";

export {
  VirtualDirent,
  VirtualFSError,
  VirtualMemoryFS,
  VirtualStats,
  normalizePosixPath,
  virtualFS,
  type IVirtualFileSystem,
  type MkdirOptions,
  type ReadFileOptions,
  type ReaddirOptions,
  type RmOptions,
  type StatOptions,
  type VirtualDirNode,
  type VirtualFSNode,
  type VirtualFSSnapshot,
  type VirtualFileNode,
  type VirtualNodeType,
  type VirtualStatsInit,
  type WriteFileOptions,
} from "./virtual-fs/index.ts";
