import { describe, expect, test } from "bun:test";
import { decoupleDisjointTasks } from "../../../olt/scripts/src/graph/parallel-decoupler.ts";

describe("parallel-decoupler: decoupleDisjointTasks", () => {
  test("decouples artificial linear chain into 40 parallel lanes and updates statuses", () => {
    const nodes = Array.from({ length: 40 }, (_, i) => ({
      id: `task-${i + 1}`,
      type: "task",
      label: `Task ${i + 1}`,
      write_scope: [`src/lane-${i + 1}.ts`],
      effort: 1,
      status: i === 0 ? "ready" : "proposed",
    }));

    const edges = Array.from({ length: 39 }, (_, i) => ({
      source: `task-${i + 2}`,
      target: `task-${i + 1}`,
      type: "depends_on",
    }));

    const graph = {
      schema: "harness.graph",
      version: 1,
      revision: 1,
      nodes,
      edges,
    };

    const result = decoupleDisjointTasks(graph, { maxLanes: 40 });

    expect(result.decoupledEdges).toHaveLength(39);
    expect(result.warnings).toHaveLength(39);
    expect(result.waves).toHaveLength(1);
    expect(result.waves[0]!.tasks).toHaveLength(40);
    expect(result.metrics.parallelismFactor).toBe(40);
    expect(result.metrics.optimalLanes).toBe(40);
    expect(result.lanes).toHaveLength(40);

    const resultNodes = result.graph.nodes as Record<string, unknown>[];
    for (const node of resultNodes) {
      if (node.type === "task") {
        expect(node.status).toBe("ready");
      }
    }
  });

  test("preserves dependency edges with declared dataflow justifications when preserveJustified is true", () => {
    const graph = {
      schema: "harness.graph",
      version: 1,
      revision: 1,
      nodes: [
        {
          id: "task-gen",
          type: "task",
          write_scope: ["src/gen.ts"],
          effort: 2,
          status: "ready",
        },
        {
          id: "task-consume",
          type: "task",
          write_scope: ["src/consumer.ts"],
          effort: 3,
          status: "proposed",
          depReasons: {
            "task-gen": "Reads schema generated by task-gen",
          },
        },
      ],
      edges: [
        {
          source: "task-consume",
          target: "task-gen",
          type: "depends_on",
          dataflow_justification: "Reads schema generated by task-gen",
        },
      ],
    };

    const result = decoupleDisjointTasks(graph, { preserveJustified: true });
    expect(result.decoupledEdges).toHaveLength(0);
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]!.dataflowJustified).toBe(true);
    expect(result.waves).toHaveLength(2);
    expect(result.metrics.criticalSpan).toBe(5);
  });

  test("removes dataflow justified edges when preserveJustified is false", () => {
    const graph = {
      schema: "harness.graph",
      version: 1,
      revision: 1,
      nodes: [
        {
          id: "task-gen",
          type: "task",
          write_scope: ["src/gen.ts"],
          effort: 2,
          status: "ready",
        },
        {
          id: "task-consume",
          type: "task",
          write_scope: ["src/consumer.ts"],
          effort: 3,
          status: "proposed",
        },
      ],
      edges: [
        {
          source: "task-consume",
          target: "task-gen",
          type: "depends_on",
          justification: "Non-critical ordering",
        },
      ],
    };

    const result = decoupleDisjointTasks(graph, { preserveJustified: false });
    expect(result.decoupledEdges).toHaveLength(1);
    expect(result.waves).toHaveLength(1);
  });

  test("preserves dependency edges with overlapping write scopes", () => {
    const graph = {
      schema: "harness.graph",
      version: 1,
      revision: 1,
      nodes: [
        {
          id: "task-1",
          type: "task",
          write_scope: ["src/core"],
          status: "ready",
        },
        {
          id: "task-2",
          type: "task",
          write_scope: ["src/core/utils.ts"],
          status: "proposed",
        },
      ],
      edges: [
        {
          source: "task-2",
          target: "task-1",
          type: "depends_on",
        },
      ],
    };

    const result = decoupleDisjointTasks(graph);
    expect(result.decoupledEdges).toHaveLength(0);
    expect(result.warnings).toHaveLength(0);
    expect(result.waves).toHaveLength(2);
  });

  test("handles empty or invalid graph object safely", () => {
    const resultNull = decoupleDisjointTasks(null);
    expect(resultNull.decoupledEdges).toHaveLength(0);
    expect(resultNull.warnings).toHaveLength(0);
    expect(resultNull.metrics.totalWork).toBe(0);
    expect(resultNull.waves).toHaveLength(0);

    const resultString = decoupleDisjointTasks("invalid-input");
    expect(resultString.decoupledEdges).toHaveLength(0);
    expect(resultString.metrics.totalWork).toBe(0);
  });

  test("decouples complex mixed DAG separating disjoint chains while maintaining true blockers", () => {
    const graph = {
      schema: "harness.graph",
      version: 1,
      revision: 1,
      nodes: [
        { id: "a1", type: "task", write_scope: ["src/a1.ts"], effort: 2, status: "ready" },
        { id: "a2", type: "task", write_scope: ["src/a2.ts"], effort: 2, status: "proposed" },
        { id: "b1", type: "task", write_scope: ["src/shared/b.ts"], effort: 3, status: "ready" },
        { id: "b2", type: "task", write_scope: ["src/shared/b.ts"], effort: 3, status: "proposed" },
        { id: "c1", type: "task", write_scope: ["src/c1.ts"], effort: 1, status: "ready" },
        {
          id: "c2",
          type: "task",
          write_scope: ["src/c2.ts"],
          effort: 1,
          status: "proposed",
          depReasons: { c1: "Needs c1 output file" },
        },
      ],
      edges: [
        { source: "a2", target: "a1", type: "depends_on" },
        { source: "b2", target: "b1", type: "depends_on" },
        { source: "c2", target: "c1", type: "depends_on", justification: "Needs c1 output file" },
      ],
    };

    const result = decoupleDisjointTasks(graph);
    expect(result.decoupledEdges).toHaveLength(1);
    expect(result.decoupledEdges[0]!).toEqual({ source: "a2", target: "a1" });

    const nodes = result.graph.nodes as Record<string, unknown>[];
    const a2Node = nodes.find((n) => n.id === "a2");
    const b2Node = nodes.find((n) => n.id === "b2");
    const c2Node = nodes.find((n) => n.id === "c2");

    expect(a2Node?.status).toBe("ready");
    expect(b2Node?.status).toBe("proposed");
    expect(c2Node?.status).toBe("proposed");
  });
});
