export const ERROR_CODES = [
  "AUTHENTICATION_FAILURE",
  "INTEGRITY",
  "INVALID_ARGUMENT",
  "INVALID_STATE",
  "LOCK_TIMEOUT",
  "NOT_FOUND",
  "NOT_IMPLEMENTED",
  "PATH_SAFETY",
  "PERMISSION_DENIED",
  "ROLE_CONFINEMENT_VIOLATION",
  "UNSUPPORTED_HOST",
  "UNSUPPORTED_PLATFORM",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
