import {
  defectAuditCommand,
  calculateApcaLightnessContrast,
  discoverDefectFiles,
  formatDefectAuditReport,
  getApcaBadgeInfo,
  renderApcaContrastBadge,
  renderAsciiDefectTable,
  type ApcaBadgeInfo,
  type ApcaContrastCompliance,
  type AuditedDefect,
  type DefectAuditCommandResult,
  type DefectAuditSummary,
  type DefectStatus,
  type RGBColor,
} from "../cli/commands/defect-audit.ts";
import type { CommandContext, Flags } from "../cli/options.ts";
import {
  appendCompletedDefectLogEntry,
  autoPromoteDefect,
  DEFAULT_COMPLETED_DEFECTS_FILE,
  generateDefectRegressionTest,
  generateRegressionTestSuite,
  isDefectEligibleForPromotion,
  promoteResolvedDefects,
  readCompletedDefectsLog,
  resolveCanonicalCompletedDefectsPath,
  resolveCompletedDefectsPath,
  validateRegressionTest,
  writeCompletedDefectsLog,
  type AutoPromoteDefectParams,
  type DefectPromotionOptions,
  type DefectPromotionResult,
  type GeneratedRegressionTest,
  type RegressionTestGeneratorOptions,
  type RegressionTestSuiteOptions,
} from "./defects.ts";

export {
  appendCompletedDefectLogEntry,
  autoPromoteDefect,
  defectAuditCommand,
  calculateApcaLightnessContrast,
  DEFAULT_COMPLETED_DEFECTS_FILE,
  discoverDefectFiles,
  formatDefectAuditReport,
  generateDefectRegressionTest,
  generateRegressionTestSuite,
  getApcaBadgeInfo,
  isDefectEligibleForPromotion,
  promoteResolvedDefects,
  readCompletedDefectsLog,
  renderApcaContrastBadge,
  renderAsciiDefectTable,
  resolveCanonicalCompletedDefectsPath,
  resolveCompletedDefectsPath,
  validateRegressionTest,
  writeCompletedDefectsLog,
  type ApcaBadgeInfo,
  type ApcaContrastCompliance,
  type AuditedDefect,
  type AutoPromoteDefectParams,
  type DefectAuditCommandResult,
  type DefectAuditSummary,
  type DefectPromotionOptions,
  type DefectPromotionResult,
  type DefectStatus,
  type GeneratedRegressionTest,
  type RGBColor,
  type RegressionTestGeneratorOptions,
  type RegressionTestSuiteOptions,
};

export function executeDefectAudit(
  flags: Flags,
  context?: CommandContext,
): DefectAuditCommandResult {
  return defectAuditCommand(flags, context);
}
