export {
  COGNITIVE_AUDIT_DIMENSIONS,
  DEFAULT_DIMENSIONAL_WEIGHTS,
  DEFAULT_HYPER_AUDIT_INTERVAL_MS,
  HYPER_COGNITION_VERSION,
  MAX_COGNITIVE_SCORE,
  MIND_NEVER_IDLE_MANTRA,
  MIN_COGNITIVE_SCORE,
  PROACTIVE_QUESTION_CATALOG,
  computeCognitiveScoreVector,
  createHyperCognitionEngine,
  evaluateCadenceHyperPulse,
  executeProactiveSelfQuestioningCycle,
  formatHyperCognitionBrief,
  generateOptimizationProposals,
  harvestPlanEnhancementsDuringPulse,
  runAutonomousAuditLoop,
  validateHyperCognitiveReport,
  type CadenceHyperAction,
  type CognitiveAuditDimension,
  type CognitiveAuditFinding,
  type CognitiveAuditResult,
  type CognitiveAuditSeverity,
  type CognitiveScoreVector,
  type DimensionalWeights,
  type DiscoveredSubtask,
  type HyperCognitionEngineOptions,
  type HyperCognitionEngine,
  type HyperCognitivePulseReport,
  type HyperPulseInput,
  type MindPulseContext,
  type OptimizationProposal,
  type PlanEnhancementHarvest,
  type ProactiveQuestionCycle,
  type ProactiveQuestionSpec,
  type QuestionCycleInput,
  type SystemStateMetrics,
} from "./lifecycle/cognition/index.ts";
