// Fallback resolver for production and test environments
// return join(resolveCapsulesDir(), "EVOLUTION_HISTORY.jsonl");
export {
  CLOSING_FORBIDDEN_IDLE_MIND,
  DEFAULT_EVOLUTION_BASE_INTERVAL_MS,
  DEFAULT_EVOLUTION_MAX_INTERVAL_MS,
  DEFAULT_SCALING_THRESHOLDS,
  NON_STOPPING_RULE,
  PERPETUAL_NON_STOPPING_CADENCE,
  balanceOrchestratorLoad,
  calculateHierarchyCapacity,
  enforcePerpetualNonStoppingCadence,
  evaluateHierarchyScaling,
  evaluatePerpetualCadence,
  executeSelfEvolutionStep,
  formatSelfEvolutionBrief,
  getEvolutionStats,
  readEvolutionHistory,
  recordEvolutionCycle,
  resolveEvolutionHistoryPath,
  runSelfEvolutionCycle,
  synthesizeDynamicPlanRevisions,
  type EvolutionHistoryStats,
  type EvolutionLedgerEntry,
  type HierarchyCapacityMetrics,
  type HierarchyScalingDecision,
  type HierarchyScalingDirection,
  type LoadBalancingAssignment,
  type LoadBalancingPlan,
  type OrchestratorNodeInfo,
  type OrchestratorNodeStatus,
  type PerpetualCadenceEvaluation,
  type ScalingThresholds,
  type SelfEvolutionCadenceState,
  type SelfEvolutionCycleOptions,
  type SelfEvolutionCycleResult,
  type SelfEvolutionMode,
  type SupervisoryRoleTier,
} from "./lifecycle/evolution/index.ts";
