import type { AgentOperationalContract } from "./types.ts";
import { defineContract, FORBIDDEN_WRITE_TOOLS, FORBIDDEN_EXEC_TOOLS } from "./archetypes.ts";

export const CONTRACTS_TIER_3_QUALITY_UI: readonly AgentOperationalContract[] = [
  defineContract({
    id: "ui-optical-validator",
    name: "UI Optical Cognitive Validator",
    role: "ui-optical-validator",
    tier: 3,
    category: "quality",
    aliases: [
      "ui-visual-reviewer",
      "ui_optical_validator",
      "ui-cognitive-validator",
      "optical-validator",
      "visual-reviewer",
      "headful-chrome-critic",
    ],
    toolBoundaries: {
      canWriteCode: false,
      canExecuteCommands: false,
      canSpawnSubagents: true,
      canClaimLeases: false,
      allowedTools: [
        "view_file",
        "evidence:screenshots",
        "task:brief",
        "task:validate-start",
        "task:probe",
        "task:reject",
        "task:review",
        "msg:send",
        "msg:recv",
        "msg:poll",
      ],
      forbiddenTools: [...FORBIDDEN_WRITE_TOOLS, ...FORBIDDEN_EXEC_TOOLS],
    },
    permissions: {
      may: [
        "Headful Chrome visual screenshot inspection across all 4 mandatory viewports (1920x1080, 1440x900, 768x1024, 390x844)",
        "Audit the 8 Optical Dimensions (visual hierarchy, optical spacing rhythm, typography, clipping, APCA contrast, theme harmony, z-index overlays, touch targets >= 44px)",
        "Execute Socratic challenge loop with natural cognitive design critique",
      ],
      mustNot: [
        "Execute ANY terminal/bash commands (0 command execution privileges)",
        "Write, edit, format, or delete repository files (0 source edits)",
        "Read implementation source code (source-code blindness quarantine)",
        "Issue superficial boilerplate approvals without screenshot image artifact inspection",
      ],
      allowedCommands: [
        "task:brief",
        "task:validate-start",
        "task:probe",
        "task:reject",
        "task:review",
        "finding:get",
        "report:get",
        "evidence:get",
        "evidence:screenshots",
        "agent:register",
        "agent:report",
        "agent:release",
        "whoami",
        "msg:send",
        "msg:recv",
        "msg:poll",
      ],
      forbiddenCommands: [...FORBIDDEN_WRITE_TOOLS, ...FORBIDDEN_EXEC_TOOLS],
      allowedSpawns: ["sub-validator"],
    },
    invariants: [
      "COGNITIVE_VALIDATOR_ZERO_COMMANDS_HARDLOCK",
      "SOURCE_CODE_BLINDNESS_QUARANTINE",
      "HEADFUL_CHROME_VISUAL_REVIEW_MANDATE",
      "OPTICAL_8_DIMENSIONS_AUDIT",
      "SOCRATIC_CHALLENGE_QUOTA",
      "SUPERFICIAL_UI_APPROVAL_BAN",
      "FOUR_VIEWPORT_MANDATE",
    ],
    isHeadfulReviewer: true,
    isSourceCodeBlind: true,
    manifestPath: "olt/agents/ui-optical-validator.yaml",
    certifiedDeliverables: [
      {
        type: "headful_visual_critique",
        description: "Headful Chrome Visual Critique",
        evidenceRequired: true,
      },
      {
        type: "socratic_challenge_receipt",
        description: "Socratic Challenge & Pushback Receipt",
        evidenceRequired: true,
      },
    ],
  }),

  defineContract({
    id: "ui-headless-validator",
    name: "UI Headless Mechanic Validator",
    role: "ui-headless-validator",
    tier: 3,
    category: "quality",
    aliases: [
      "ui-mechanic-validator",
      "ui-debugger",
      "ui_headless_validator",
      "ui_mechanic_validator",
      "ui-headless-debugger",
      "headless-debugger",
    ],
    toolBoundaries: {
      canWriteCode: false,
      canExecuteCommands: true,
      canSpawnSubagents: false,
      canClaimLeases: false,
      allowedTools: [
        "run:exec",
        "task:brief",
        "task:validate-start",
        "task:check",
        "task:probe",
        "task:reject",
        "task:review",
        "task:submit",
        "msg:send",
        "msg:recv",
        "msg:poll",
      ],
      forbiddenTools: [...FORBIDDEN_WRITE_TOOLS],
    },
    permissions: {
      may: [
        "Execute automated Playwright test runs and headless browser rendering via `run:exec`",
        "Capture multi-viewport screenshot image artifacts into evidence directory",
        "Audit DOM hitbox geometry metrics and touch target bounds (>= 44x44px)",
      ],
      mustNot: [
        "Write application source code (0 source edits)",
        "Re-run implementer unit tests",
        "Approve UI tasks based solely on automated test passes",
      ],
      allowedCommands: [
        "task:brief",
        "task:validate-start",
        "task:check",
        "run:exec",
        "task:probe",
        "task:reject",
        "task:review",
        "task:submit",
        "finding:get",
        "report:get",
        "evidence:get",
        "evidence:screenshots",
        "agent:register",
        "agent:report",
        "agent:release",
        "doctor",
        "whoami",
        "msg:send",
        "msg:recv",
        "msg:poll",
      ],
      forbiddenCommands: [...FORBIDDEN_WRITE_TOOLS],
      allowedSpawns: [],
    },
    invariants: [
      "ZERO_SOURCE_EDITS",
      "NO_TEST_RE_RUNS",
      "AUTOMATED_TESTS_ARE_HALF_THE_JOB",
      "MANDATORY_SCREENSHOT_CAPTURE_ALL_4_VIEWPORTS",
      "HITBOX_METRIC_VERIFICATION_44PT",
      "SUPERFICIAL_UI_APPROVAL_BAN",
    ],
    isHeadlessDebugger: true,
    manifestPath: "olt/agents/ui-headless-validator.yaml",
    certifiedDeliverables: [
      {
        type: "hitbox_geometry_audit",
        description: "44pt Hitbox Geometry Audit",
        evidenceRequired: true,
      },
      {
        type: "captured_screenshots_evidence",
        description: "Multi-Viewport Screenshot Evidence",
        evidenceRequired: true,
      },
    ],
  }),
];
