import { describe, expect, test } from "bun:test";
import { formatDoctorBrief } from "../../../../olt/scripts/src/cli/commands/diagnostics-ops.ts";
import {
  formatAgentListBrief,
  formatAgentRegisterBrief,
  formatAutoPartitionBrief,
  formatBranchOpenBrief,
  formatCapsuleInitBrief,
  formatCriticReviewBrief,
  formatCriticStartBrief,
  formatFindingBrief,
  formatOrchestrateBrief,
  formatPlanApplyBrief,
  formatPlanAuditBrief,
  formatPlanClaimBrief,
  formatPlanCompileBrief,
  formatPlanEnhanceBrief,
  formatPlanReplanBrief,
  formatPlanReviewBrief,
  formatPlanStatusBrief,
  formatPlanValidateStartBrief,
  formatQueueEmptyBrief,
  formatQueueListBrief,
  formatQueueNextBrief,
  formatQueuePopBrief,
  formatQueueWaveBrief,
  formatReportBrief,
  formatRunCompleteBrief,
  formatRunExecBrief,
  formatRunStatusBrief,
  formatTaskAssignRepairerBrief,
  formatTaskClaimBrief,
  formatTaskHeartbeatBrief,
  formatTaskProbeBrief,
  formatTaskRegisteredBrief,
  formatTaskRejectBrief,
  formatTaskReviewPassBrief,
  formatTaskSubmitBrief,
  formatValidationStartBrief,
} from "../../../../olt/scripts/src/cli/formatters/index.ts";

describe("Formatter Integration with ⚡ Next Actions GPS blocks", () => {
  test("every brief includes ⚡ Next Actions and satisfies <= 30 line limit", () => {
    const briefs = [
      formatOrchestrateBrief({
        runId: "run-1",
        runRoot: "/capsules/run-1",
        promptSha256: "abc",
        promptBytes: 100,
        runIdWasDerived: false,
      }),
      formatCapsuleInitBrief({
        runId: "run-1",
        runRoot: ".olt/capsules/run-1",
        promptSha256: "abc",
        assurance: "source-verified",
      }),
      formatTaskRegisteredBrief({
        taskId: "task-1",
        label: "T1",
        writeScope: ["src/"],
        gateCmd: "bun test",
        deps: [],
        totalTasks: 1,
      }),
      formatPlanEnhanceBrief({
        runId: "run-1",
        markdownPath: "plan.md",
        jsonPath: "plan.json",
        markdownSha256: "abc",
        promptSha256: "def",
        revision: 1,
        summaryPresent: true,
        counts: { observations: 1, todos: 1, risks: 0, openQuestions: 0, sources: 1 },
      }),
      formatPlanCompileBrief({
        revision: 1,
        totalTasks: 1,
        topology: { revision: 1, maxParallel: 1, waves: [{ wave: 1, taskIds: ["t1"] }] },
        topologyDeclaration: { independentRoots: 1, edgeCount: 0 },
        collisions: 0,
        requirementsCount: 1,
        runId: "run-1",
      }),
      formatPlanStatusBrief("run-1", [
        { id: "t1", label: "T1", writeScope: ["a"], gate: "g", deps: [] },
      ]),
      formatPlanReplanBrief({
        revision: 2,
        repairRound: 1,
        newTasksCount: 1,
        repairTasks: [
          { id: "R-1", writeScope: ["src/"], findingsCount: 1, gate: "g", gateSource: "finding" },
        ],
        runId: "run-1",
      }),
      formatPlanClaimBrief({ runId: "run-1", agent: "planner", packetId: "P-1" }),
      formatPlanApplyBrief({ runId: "run-1", revision: 2, totalTasks: 3 }),
      formatAutoPartitionBrief({
        glob: "src/**/*.ts",
        groupBy: "file",
        taskIds: ["t1", "t2"],
        totalTasks: 2,
        breadthWarnings: [],
      }),
      formatPlanAuditBrief({ runId: "run-1", revision: 1, findings: [], notEvaluated: [] }),
      formatPlanValidateStartBrief({
        runId: "run-1",
        validator: "val-1",
        token: "tok-v",
        graphRevision: 1,
        totalTasks: 2,
      }),
      formatPlanReviewBrief({
        runId: "run-1",
        validator: "val-1",
        status: "approved",
        graphRevision: 1,
        findingsCount: 0,
        summary: "looks good",
        dependencyEdgesReviewed: 1,
        gateIdsReviewed: 1,
      }),
      formatTaskClaimBrief({
        taskId: "task-1",
        agent: "w1",
        token: "tok-1",
        durationMinutes: 30,
        writeScope: ["src/"],
      }),
      formatTaskHeartbeatBrief({
        taskId: "task-1",
        agent: "w1",
        extendedMinutes: 30,
        newDeadline: "21:00",
      }),
      formatTaskSubmitBrief({
        taskId: "task-1",
        agent: "w1",
        filesTouchedCount: 1,
        writeScope: ["src/"],
        reportPath: "r.json",
      }),
      formatValidationStartBrief({
        taskId: "task-1",
        validator: "val-1",
        token: "tok-v",
        gates: ["bun test"],
      }),
      formatTaskReviewPassBrief({
        taskId: "task-1",
        validator: "val-1",
        gateSummary: "passed",
        reportPath: "r.json",
        taskStatus: "validated",
      }),
      formatTaskRejectBrief({
        taskId: "task-1",
        validator: "val-1",
        findingId: "f-1",
        issue: "failed",
        status: "changes_requested",
      }),
      formatTaskProbeBrief({
        taskId: "task-1",
        validator: "val-1",
        round: 1,
        demands: [{ id: "d1", demand: "show proof" }],
        repairRound: 0,
      }),
      formatTaskAssignRepairerBrief({
        taskId: "task-1",
        replacementId: "rep-2",
        reason: "stuck",
        evidence: "timeout",
      }),
      formatQueueNextBrief({
        taskId: "task-1",
        label: "T1",
        priority: 50,
        writeScope: ["src/"],
        gates: ["bun test"],
        runId: "run-1",
      }),
      formatQueueEmptyBrief("run-1"),
      formatQueueListBrief({
        ready: ["t1"],
        leased: [],
        validating: [],
        blocked: [],
        satisfied: [],
      }),
      formatQueueWaveBrief({
        runId: "run-1",
        entries: [
          { taskId: "t1", label: "T1", priority: 50, writeScope: ["src/"], recordedWave: 1 },
        ],
        maxParallel: 4,
        topologySource: "recorded",
        topologyRevision: 1,
      }),
      formatQueuePopBrief({
        taskId: "t1",
        agent: "w1",
        token: "tok-1",
        deadlineMinutes: 30,
        expiresAt: "22:00",
        writeScope: ["src/"],
        gates: ["bun test"],
      }),
      formatCriticStartBrief({
        critic: "c1",
        token: "tok-c",
        tasksSatisfied: 2,
        totalTasks: 2,
        reqsEvidenced: 2,
        totalReqs: 2,
        finalGates: [],
      }),
      formatCriticReviewBrief({
        critic: "c1",
        decision: "approve",
        summary: "all done",
        token: "tok-c",
        runId: "run-1",
      }),
      formatRunCompleteBrief({
        runId: "run-1",
        capsulePath: "/capsules/run-1",
        tasksCount: 2,
        validationsCount: 2,
        gatesPassed: 2,
        totalGates: 2,
      }),
      formatRunStatusBrief("run-1", "Executing", [], "1/1"),
      formatRunExecBrief({ commandStr: "bun test", exitCode: 0, outputSummary: "ok" }),
      formatAgentRegisterBrief(
        {
          id: "ag-1",
          role: "implementer",
          host: "local",
          provider: { value: "openai", evidence_class: "agent_reported" },
          model: { value: "gpt-4", evidence_class: "agent_reported" },
          model_tier: { value: "tier-3", evidence_class: "agent_reported" },
          thinking_level: { value: "high", evidence_class: "agent_reported" },
          context_window: { value: 128000, evidence_class: "agent_reported" },
          tools_granted: { value: [], evidence_class: "agent_reported" },
          parent_agent_id: null,
          parent_task_id: null,
          granted_at: "now",
          status: "active",
        },
        "run-1",
      ),
      formatAgentListBrief([], "run-1", false),
      formatBranchOpenBrief(
        {
          id: "br-1",
          parent_task_id: "t1",
          parent_agent_id: "ag-1",
          reason: "subdivide",
          depth: 1,
          status: "open",
          sub_tasks: [],
        },
        "run-1",
      ),
      formatFindingBrief({
        finding: { id: "f-1", severity: "blocking", message: "fail" },
        path: "f.json",
      }),
      formatReportBrief({
        report: { status: "pass", summary: "passed" },
        path: "rep.json",
        name: "review",
      }),
      formatDoctorBrief("run-1", {
        healthy: true,
        bun_version: "1.3.0",
        bun_supported: true,
        gitignored: true,
        issues: [],
      }),
    ];

    for (const brief of briefs) {
      expect(brief).toContain("⚡ Next Actions:");
      expect(brief.split("\n").length).toBeLessThanOrEqual(30);
    }
  });
});
