export {
  CANONICAL_VIEWPORTS,
  CONFIG_CANDIDATE_NAMES,
  DEFAULT_PRESETS,
  DEFAULT_SIDEBAR_LAYOUT,
  exportDefaultCaptureConfigYaml,
  findCaptureConfigFile,
  loadCaptureConfig,
  parseYamlOrJson,
  validateCaptureConfig,
  type CaptureAction,
  type CaptureAuthConfig,
  type CaptureConfig,
  type CapturePreset,
  type CaptureScreenTarget,
  type CaptureUserConfig,
  type CaptureViewport,
  type SidebarLayoutConfig,
  type SidebarLayoutSelectors,
  type SidebarPosition,
} from "./config/index.ts";

export {
  COGNITIVE_BOILERPLATE,
  NAMED_COLORS,
  auditFocusRingContrast,
  calculateApcaLightness,
  calculateConcentricRadius,
  calculateFittsId,
  calculateHickHymanEntropy,
  calculateOpticalCurvatureMetrics,
  calculateWcagLuminance,
  compositeColorOver,
  evaluateCognitiveQuestions,
  formatManifestFilename,
  generateRemediations,
  getExpectedAppleTracking,
  getSubpixelFraction,
  hslToRgb,
  isCertifiedManifest,
  loadCompanionManifest,
  parseCssColor,
  saveCompanionManifest,
  snapToDevicePixelRatio,
  srgbChannelToLinear,
  synthesizeCompanionManifest,
  validateApcaElement,
  validateAppleOpticalTracking,
  validateClsReservation,
  validateCognitive,
  validateCognitiveSemanticDepth,
  validateConcentricRadius,
  validateCowanChunking,
  validateCustom,
  validateFittsLaw,
  validateFloatingUiCollision,
  validateFocusRingOpticalSnapping,
  validateGeistTokens,
  validateHickHyman,
  validateMaterialStateLayers,
  validateMechanical,
  validateNestedConcentricCorners,
  validateNormanRecovery,
  validateSidebarLayout,
  validateSubpixelSnapping,
  validateTouchTargetClearance,
  validateTouchTargetDimensions,
  validateUiStatesFsm,
  validateWaiAriaFocusTrap,
  type CodeRemediation,
  type CodeRemediationFramework,
  type CognitiveAnalysisReport,
  type CognitiveSemanticDepthDefect,
  type CognitiveSemanticDepthResult,
  type CompanionManifestV2,
  type ConcentricCornerEvaluation,
  type DefectSeverity,
  type DprSnapEvaluation,
  type ElementBoundingBox,
  type ElementComputedStyles,
  type ElementMediaMeta,
  type ElementPhysicsSnapshot,
  type EvaluatedCognitiveQuestion,
  type EvaluatedCriterion,
  type FocusRingDefect,
  type FocusRingDefectType,
  type FocusRingGeometry,
  type OpticalCurvatureMetrics,
  type OpticalSnapResult,
  type OpticalSnappingOptions,
  type PillarValidationResult,
  type QuestionEvaluatorParams,
  type RgbaColor,
  type UIInteractionState,
  type ValidationContext,
  type ValidationDefect,
  type ValidationPillar,
  type ValidationVerdict,
} from "./validator/index.ts";

export {
  CANONICAL_ROLES,
  DEFAULT_DOM_SIMULATION_OPTIONS,
  DEFAULT_LAYOUT_SHIFT_OPTIONS,
  DOM_EVENT_DISPATCH_SCRIPT,
  DOM_PHYSICS_EXTRACTION_SCRIPT,
  DefaultFallbackBrowserProvider,
  DomEventSimulator,
  LayoutShiftTracker,
  SessionAuthResolver,
  buildCumulativeLayoutShiftReport,
  buildSyntheticInteractionPlan,
  calculateDistanceFraction,
  calculateImpactFraction,
  calculateLayoutShiftScore,
  classifyLayoutShift,
  clipRectToViewport,
  computeLayoutMetrics,
  computeRectanglesUnionArea,
  createEmptyDomPhysicsSnapshot,
  createSessionAuthResolver,
  createSyntheticPngBuffer,
  detectLayoutShiftBetweenSnapshots,
  extractDomPhysics,
  filterScreens,
  groupSessionWindows,
  identifyRootCausingElements,
  resolveCaptureOutputDir,
  resolveDomSimulationOptions,
  resolveLayoutShiftTrackerOptions,
  resolveViewportsForScreen,
  runLiveCapture,
  simulateDomEvent,
  type AABB,
  type CaptureBrowserDriver,
  type CaptureBrowserProvider,
  type CaptureError,
  type CaptureItemResult,
  type CapturePageDriver,
  type CaptureRunOptions,
  type CaptureRunResult,
  type CompanionManifest,
  type CumulativeLayoutShiftReport,
  type DomEventSimulationReport,
  type DomEventStepResult,
  type DomPhysicsSnapshot,
  type DomSimulationOptions,
  type ExpectedShiftBehavior,
  type ExtractedComputedStyles,
  type ExtractedElementMetrics,
  type ExtractedElementPhysics,
  type LayoutOverflowEntry,
  type LayoutShiftEntry,
  type LayoutShiftTrackerOptions,
  type LayoutShiftWindow,
  type ResolvedDomSimulationOptions,
  type ResolvedLayoutShiftTrackerOptions,
  type ResolvedSessionAuth,
  type SyntheticDomEvent,
  type SyntheticDomEventType,
  type TextClippingEntry,
  type UnexpectedShiftDefect,
  type UnstableElementDisplacement,
} from "./runners/index.ts";
