import {
  msgHealthCommand,
  msgListCommand,
  msgListenCommand,
  msgPollCommand,
  msgRecvCommand,
  msgSendCommand,
} from "../commands/index.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag, type CommandSpec } from "./types.ts";

export const ENGINE_COMMANDS: readonly CommandSpec[] = [
  {
    name: "msg:send",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "Send an authenticated mailbox message to an agent or role.",
    description:
      "Dispatches an HMAC-signed envelope into the recipient inbox and records it in the sender outbox.",
    flags: [
      requiredFlag("to", "string", "Recipient agent ID or role."),
      requiredFlag("type", "string", "Mailbox message type (e.g. DISPATCH_TASK, PULSE_HEARTBEAT)."),
      optionalFlag("body", "string", "Plain text message body."),
      optionalFlag("payload", "string", "JSON payload string or object data."),
      optionalFlag("actor", "string", "Sender agent ID (auto-derived if omitted)."),
      optionalFlag("role", "string", "Sender agent role (auto-derived if omitted)."),
      optionalFlag("correlation-id", "string", "Correlation ID for message threading."),
      optionalFlag("secret", "string", "Repository secret key for HMAC signing."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts msg:send --to worker-1 --type DISPATCH_TASK --body "Process chunk #42"',
      'bun harness.ts msg:send --to coordinator --type HANDOFF_RECEIPT --payload \'{"status":"done"}\'',
      'bun harness.ts msg:send --to mechanic-1 --type DIRECTIVE --body "Run diagnostics" --correlation-id corr-101',
    ],
    handler: msgSendCommand,
  },
  {
    name: "msg:recv",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "Receive unread mailbox messages from the agent inbox.",
    description:
      "Reads unread HMAC-verified messages, optionally waiting if the inbox is empty and advancing the cursor.",
    flags: [
      optionalFlag("actor", "string", "Recipient agent ID (auto-derived if omitted)."),
      optionalFlag("wait", "bool", "Wait for messages if inbox is empty."),
      optionalFlag("timeout", "int", "Timeout in milliseconds when waiting (default: 5000)."),
      optionalFlag(
        "advance-cursor",
        "bool",
        "Advance cursor after reading messages (default: true).",
      ),
      optionalFlag("no-advance-cursor", "bool", "Do not advance cursor after reading messages."),
      optionalFlag("type", "string", "Filter by message type."),
      optionalFlag("correlation-id", "string", "Filter by correlation ID."),
      optionalFlag("secret", "string", "Repository secret key for HMAC verification."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts msg:recv --actor worker-1",
      "bun harness.ts msg:recv --actor worker-1 --wait --timeout 10000",
      "bun harness.ts msg:recv --actor worker-1 --type DISPATCH_TASK --no-advance-cursor",
    ],
    handler: msgRecvCommand,
  },
  {
    name: "msg:poll",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "Poll mailbox for messages at regular intervals until received or timeout.",
    description:
      "Repeatedly checks the inbox at specified intervals until unread messages arrive or limits are reached. A timeout of 0 indicates infinite timeout.",
    flags: [
      optionalFlag("actor", "string", "Recipient agent ID (auto-derived if omitted)."),
      optionalFlag("interval", "int", "Polling interval in milliseconds (default: 500)."),
      optionalFlag(
        "timeout",
        "int",
        "Polling timeout in milliseconds (default: 30000). A timeout of 0 indicates infinite timeout.",
      ),
      optionalFlag("max-rounds", "int", "Maximum polling rounds."),
      optionalFlag(
        "continuous",
        "bool",
        "Run continuously without exiting on first message batch.",
      ),
      optionalFlag(
        "advance-cursor",
        "bool",
        "Advance cursor after reading messages (default: true).",
      ),
      optionalFlag("no-advance-cursor", "bool", "Do not advance cursor after reading messages."),
      optionalFlag("type", "string", "Filter by message type."),
      optionalFlag("correlation-id", "string", "Filter by correlation ID."),
      optionalFlag("secret", "string", "Repository secret key for HMAC verification."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
      optionalFlag("json", "bool", "Output machine-readable JSON."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts msg:poll --actor worker-1 --interval 200 --timeout 5000",
      "bun harness.ts msg:poll --actor worker-1 --max-rounds 10",
      "bun harness.ts msg:poll --actor worker-1 --type DISPATCH_TASK",
    ],
    handler: msgPollCommand,
  },
  {
    name: "msg:listen",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "Continuously listen for and drain incoming mailbox messages.",
    description:
      "Starts continuous draining on the agent mailbox, streaming incoming messages until interrupted.",
    flags: [
      optionalFlag("actor", "string", "Recipient agent ID (auto-derived if omitted)."),
      optionalFlag(
        "interval",
        "int",
        "Polling interval / idle wait in milliseconds (default: 50).",
      ),
      optionalFlag("batch-size", "int", "Maximum messages to process per drain pass."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
      optionalFlag("secret", "string", "Repository secret key for HMAC verification."),
      optionalFlag("json", "bool", "Emit JSON output rather than text stream."),
      optionalFlag("timeout", "int", "Drain timeout in milliseconds."),
      optionalFlag("max-messages", "int", "Maximum messages to process before stopping."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts msg:listen --actor worker-1",
      "bun harness.ts msg:listen --actor worker-1 --interval 50 --batch-size 10",
    ],
    handler: msgListenCommand,
  },
  {
    name: "msg:list",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "List mailbox summaries and unread counts across agents.",
    description:
      "Scans the repository mailbox store to report message counts, unread queue depths, outbox activity, and quarantine status per agent.",
    flags: [
      optionalFlag("actor", "string", "Filter mailbox summary to a single agent ID."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
      optionalFlag("detailed", "bool", "Show detailed per-message delivery status."),
      optionalFlag("verbose", "bool", "Alias for detailed per-message delivery status."),
      optionalFlag("message-id", "string", "Inspect delivery status of a specific message ID."),
      optionalFlag("id", "string", "Alias for message-id."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts msg:list",
      "bun harness.ts msg:list --actor worker-1",
      "bun harness.ts msg:list --base-dir /path/to/project",
    ],
    handler: msgListCommand,
  },
  {
    name: "msg:health",
    aliases: [],
    domain: "msg",
    tier: "primary",
    internal: false,
    summary: "Check mailbox listener liveness and health status.",
    description:
      "Inspects listener heartbeat, lock state, process status, and delivery metrics to determine listener health.",
    flags: [
      optionalFlag("actor", "string", "Recipient agent ID (auto-derived if omitted)."),
      optionalFlag("base-dir", "string", "Base directory for mailbox root."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts msg:health",
      "bun harness.ts msg:health --actor worker-1",
      "bun harness.ts msg:health --base-dir /path/to/project",
    ],
    handler: msgHealthCommand,
  },
];

export const MSG_COMMANDS = ENGINE_COMMANDS;
