import {
  evidenceGetCommand,
  evidenceScreenshotsCommand,
  findingGetCommand,
  reportGetCommand,
} from "../commands/inspection-ops.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag, type CommandSpec } from "./types.ts";

export const INSPECTION_COMMANDS: readonly CommandSpec[] = [
  {
    name: "finding:get",
    aliases: [],
    domain: "inspection",
    summary: "Read one finding file, or every finding in the capsule.",
    description: "Without an id the whole findings directory is listed.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("id", "string", "Finding id or file name."),
      optionalFlag("finding", "string", "Alias of --id."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts finding:get --run .olt/capsules/<run-id> --id finding-task-1"],
    handler: findingGetCommand,
  },
  {
    name: "report:get",
    aliases: [],
    domain: "inspection",
    summary: "Read a submission, review or critic report.",
    description:
      "With --task the review report is preferred and the submission is used as the fallback; --critic reads the completeness review.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Task whose report is wanted."),
      optionalFlag("critic", "bool", "Read the critic review report."),
      optionalFlag("submission", "bool", "Force the submission report."),
      optionalFlag("review", "bool", "Force the review report."),
      optionalFlag("type", "string", "submission, review or critic."),
      optionalFlag("stage", "string", "Alias of --type."),
      optionalFlag("report", "string", "Explicit report file name."),
      optionalFlag("id", "string", "Alias of --report."),
      optionalFlag("screenshots", "bool", "Include screenshot records."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts report:get --run .olt/capsules/<run-id> --task task-1 --type review",
    ],
    handler: reportGetCommand,
  },
  {
    name: "evidence:get",
    aliases: [],
    domain: "inspection",
    summary: "Read recorded command evidence.",
    description: "Filters the evidence directory by command id, task, gate or actor.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("command", "string", "Command id."),
      optionalFlag("id", "string", "Alias of --command."),
      optionalFlag("cmd", "string", "Alias of --command."),
      optionalFlag("task", "string", "Filter by task id."),
      optionalFlag("gate", "string", "Filter by gate id."),
      optionalFlag("actor", "string", "Filter by actor."),
      optionalFlag("screenshots", "bool", "Include screenshot records."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts evidence:get --run .olt/capsules/<run-id> --task task-1"],
    handler: evidenceGetCommand,
  },
  {
    name: "evidence:screenshots",
    aliases: [],
    domain: "inspection",
    summary: "List captured UI screenshots with their test ids and viewports.",
    description: "Queries the screenshot store rather than the evidence files.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Filter by task id."),
      optionalFlag("command", "string", "Filter by command id."),
      optionalFlag("cmd", "string", "Alias of --command."),
      optionalFlag("id", "string", "Alias of --command."),
      optionalFlag("actor", "string", "Filter by actor."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts evidence:screenshots --run .olt/capsules/<run-id> --task task-1"],
    handler: evidenceScreenshotsCommand,
  },
];
