import {
  policyCheckDriftCommand,
  policyGetCommand,
  policyInitCommand,
  policySetCommand,
} from "../commands/policy-ops.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag, type CommandSpec } from "./types.ts";

export const POLICY_COMMANDS: readonly CommandSpec[] = [
  {
    name: "policy:init",
    aliases: [],
    domain: "policy",
    tier: "internal",
    internal: true,
    summary: "Initialize canonical .olt/policy.json with auto-detected ecosystem defaults.",
    description:
      "Scans repository signatures to detect ecosystem and initializes .olt/policy.json.",
    flags: [
      optionalFlag("repo-root", "string", "Target repository root directory."),
      optionalFlag("repo", "string", "Alias for --repo-root."),
      optionalFlag("dir", "string", "Alias for --repo-root."),
      optionalFlag("ecosystem", "string", "Override detected repository ecosystem."),
      optionalFlag("force", "bool", "Force overwrite if policy already exists."),
      optionalFlag("json", "bool", "Output in JSON format."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts policy:init", "bun harness.ts policy:init --repo /path/to/repo"],
    handler: policyInitCommand,
  },
  {
    name: "policy:get",
    aliases: [],
    domain: "policy",
    tier: "internal",
    internal: true,
    summary: "Inspect repo policy or retrieve a specific policy key value.",
    description:
      "Reads .olt/policy.json and retrieves a specific dot-separated key or the entire policy.",
    flags: [
      optionalFlag(
        "key",
        "string",
        "Dot-separated key to retrieve (e.g. test_runner.default_command).",
      ),
      optionalFlag("repo-root", "string", "Target repository root directory."),
      optionalFlag("repo", "string", "Alias for --repo-root."),
      optionalFlag("dir", "string", "Alias for --repo-root."),
      optionalFlag("json", "bool", "Output in JSON format."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts policy:get",
      "bun harness.ts policy:get --key test_runner.default_command",
      "bun harness.ts policy:get --json",
    ],
    handler: policyGetCommand,
  },
  {
    name: "policy:set",
    aliases: [],
    domain: "policy",
    tier: "internal",
    internal: true,
    summary: "Set or update a specific key value in .olt/policy.json.",
    description:
      "Atomically updates a dot-separated key in .olt/policy.json with flock protection.",
    flags: [
      requiredFlag(
        "key",
        "string",
        "Dot-separated key to set (e.g. review_protocol.cognitive_pushes).",
      ),
      requiredFlag("value", "string", "Value to set (string, number, boolean, or JSON)."),
      optionalFlag("repo-root", "string", "Target repository root directory."),
      optionalFlag("repo", "string", "Alias for --repo-root."),
      optionalFlag("dir", "string", "Alias for --repo-root."),
      optionalFlag("json", "bool", "Output in JSON format."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts policy:set --key review_protocol.cognitive_pushes --value 5",
      "bun harness.ts policy:set --key typecheck_command --value 'bun run typecheck'",
    ],
    handler: policySetCommand,
  },
  {
    name: "policy:check-drift",
    aliases: ["policy:drift"],
    domain: "policy",
    tier: "internal",
    internal: true,
    summary: "Check for policy file drift against a known SHA-256 checksum.",
    description: "Computes SHA-256 hash of .olt/policy.json and detects configuration drift.",
    flags: [
      optionalFlag("checksum", "string", "Known SHA-256 checksum to compare against."),
      optionalFlag("repo-root", "string", "Target repository root directory."),
      optionalFlag("repo", "string", "Alias for --repo-root."),
      optionalFlag("dir", "string", "Alias for --repo-root."),
      optionalFlag("rearm", "bool", "Trigger re-arming and log drift event if drifted."),
      optionalFlag("strict", "bool", "Exit nonzero if drift or corruption detected."),
      optionalFlag("json", "bool", "Output in JSON format."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts policy:check-drift",
      "bun harness.ts policy:check-drift --checksum <sha256> --rearm",
    ],
    handler: policyCheckDriftCommand,
  },
];
