import {
  queueListCommand,
  queueNextCommand,
  queuePopCommand,
  queueWaveCommand,
} from "../commands/queue.ts";
import {
  mindQueueAddCommand,
  mindQueueCleanCommand,
  mindQueueDrainCommand,
  mindQueueListCommand,
  mindQueueSealCommand,
  todoAddCommand,
  todoCleanCommand,
  todoDrainCommand,
  todoListCommand,
  todoSealCommand,
} from "../commands/todo-ops.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag, type CommandSpec } from "./types.ts";

export {
  mindQueueAddCommand,
  mindQueueCleanCommand,
  mindQueueDrainCommand,
  mindQueueListCommand,
  mindQueueSealCommand,
  queueListCommand,
  queueNextCommand,
  queuePopCommand,
  queueWaveCommand,
  todoAddCommand,
  todoCleanCommand,
  todoDrainCommand,
  todoListCommand,
  todoSealCommand,
};

export const QUEUE_COMMANDS: readonly CommandSpec[] = [
  {
    name: "queue:next",
    aliases: [],
    domain: "queue",
    summary: "Show the highest-priority ready task without claiming it.",
    description: "Reads the queue and reports the task a coordinator would dispatch next.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:next --run .olt/capsules/<run-id>"],
    handler: queueNextCommand,
  },
  {
    name: "queue:list",
    aliases: [],
    domain: "queue",
    summary: "Partition every task by queue status.",
    description:
      "Groups tasks into ready, leased, validating, blocked and satisfied partitions with the blocking dependencies.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:list --run .olt/capsules/<run-id>"],
    handler: queueListCommand,
  },
  {
    name: "queue:wave",
    aliases: [],
    domain: "queue",
    summary: "Show every task claimable right now, ranked by critical depth — for display only.",
    description:
      "The readiness query: runs the scheduler over live task state and returns every task whose dependencies are done and whose write scope collides with nothing currently leased, ranked by critical depth and capped at max_parallel. Annotates each task with the wave plan:compile recorded, or reports the topology as absent, purely for display. This is not a batch to assemble and dispatch as one unit — claim each entry the moment an agent is free, and re-run this (or claim atomically with queue:pop / task:claim) the instant any agent finishes; never wait for the rest of one call's answer before claiming the next task. Read-only: each dispatched agent still claims its own task.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag(
        "max-parallel",
        "int",
        "Occupancy ceiling for this query; defaults to the configured default_max_parallel.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:wave --run .olt/capsules/<run-id> --max-parallel 4"],
    handler: queueWaveCommand,
  },
  {
    name: "queue:pop",
    aliases: [],
    domain: "queue",
    summary: "Claim the highest-priority ready task and mint a lease token.",
    description:
      "Atomically leases the next ready task to an agent. Fails when no task is ready rather than waiting.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("agent", "string", "Agent id receiving the lease."),
      optionalFlag("lease-duration", "int", "Lease length in seconds (5-86400)."),
      optionalFlag("lease-seconds", "int", "Alias of --lease-duration.", 1200),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts queue:pop --run .olt/capsules/<run-id> --agent worker-1 --lease-seconds 1800",
    ],
    handler: queuePopCommand,
  },
  {
    name: "queue:add",
    aliases: [],
    domain: "queue",
    summary: "Add a feedback item to the mind queue.",
    description: "Appends a new feedback item to .olt/backlog.jsonl.",
    flags: [
      requiredFlag("title", "string", "Title of the feedback item."),
      optionalFlag("content", "string", "Content or body of the feedback item."),
      optionalFlag("description", "string", "Detailed description of the feedback."),
      optionalFlag("priority", "string", "Priority level: CRITICAL, HIGH, NORMAL, LOW."),
      optionalFlag("category", "string", "Feedback category."),
      optionalFlag("id", "string", "Explicit item ID override."),
      optionalFlag("queue-file", "string", "Override queue file path."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:add --title 'Fix memory leak' --priority HIGH"],
    handler: mindQueueAddCommand,
  },
  {
    name: "queue:drain",
    aliases: [],
    domain: "queue",
    summary: "Drain and mark pending feedback items for execution.",
    description: "Drains pending items from .olt/backlog.jsonl in FIFO order.",
    flags: [
      requiredFlag(
        "authority-run",
        "string",
        "Capsule run whose active Mind grant authorizes this mutation.",
      ),
      optionalFlag(
        "actor",
        "string",
        "Explicit acting Mind identity; must match the verified session when supplied.",
      ),
      optionalFlag("limit", "int", "Maximum items to drain.", 5),
      optionalFlag("mark-as", "string", "Target status: PROCESSED, IN_PROGRESS, ADMITTED."),
      optionalFlag("category", "string", "Filter by category."),
      optionalFlag("priority", "string", "Filter by priority level."),
      optionalFlag("queue-file", "string", "Override queue file path."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts queue:drain --authority-run <run>",
      "bun harness.ts queue:drain --authority-run <run> --limit 3",
    ],
    authority: {
      requiresActingIdentity: true,
      authorityRunFlag: "authority-run",
      allowedRoles: ["mind"],
      constrainedPathFlags: ["queue-file", "queue-path"],
    },
    handler: mindQueueDrainCommand,
  },
  {
    name: "queue:status",
    aliases: [],
    domain: "queue",
    summary: "List and inspect mind feedback queue items.",
    description:
      "Lists active feedback items from the canonical feedback queue (.olt/backlog.jsonl).",
    flags: [
      optionalFlag("status", "string", "Filter by item status."),
      optionalFlag("priority", "string", "Filter by priority level."),
      optionalFlag("category", "string", "Filter by category."),
      optionalFlag("queue-file", "string", "Override queue file path."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
      optionalFlag("all", "bool", "Show all items without pagination."),
      optionalFlag("limit", "int", "Maximum items to display."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:status"],
    handler: mindQueueListCommand,
  },
  {
    name: "queue:seal",
    aliases: [],
    domain: "queue",
    summary: "Seal completed queue items with empirical verification proofs.",
    description: "Marks queue items completed and attaches proof records.",
    flags: [
      requiredFlag(
        "authority-run",
        "string",
        "Capsule run whose active Mind grant authorizes this mutation.",
      ),
      optionalFlag(
        "actor",
        "string",
        "Explicit acting Mind identity; must match the verified session when supplied.",
      ),
      requiredFlag("id", "string", "Feedback item ID to seal."),
      optionalFlag("proof", "string", "Commit SHA or test receipt proving resolution."),
      optionalFlag("resolution", "string", "Resolution description."),
      optionalFlag("commit", "string", "Commit SHA proving resolution."),
      optionalFlag("test-path", "string", "Test file path proving resolution."),
      optionalFlag("assertions", "string", "Number of test assertions verified."),
      optionalFlag("runtime-ms", "string", "Execution duration in milliseconds."),
      optionalFlag("note", "string", "Resolution notes."),
      optionalFlag("summary", "string", "Summary of resolution."),
      optionalFlag("queue-file", "string", "Override queue file path."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:seal --authority-run <run> --id fb-123 --proof sha-abc"],
    authority: {
      requiresActingIdentity: true,
      authorityRunFlag: "authority-run",
      allowedRoles: ["mind"],
      constrainedPathFlags: ["queue-file", "queue-path"],
    },
    handler: mindQueueSealCommand,
  },
  {
    name: "queue:clean",
    aliases: [],
    domain: "queue",
    summary: "Prune resolved items from queue into completed-tasks archive.",
    description: "Moves sealed items from .olt/backlog.jsonl to .olt/completed-tasks.jsonl.",
    flags: [
      requiredFlag(
        "authority-run",
        "string",
        "Capsule run whose active Mind grant authorizes this mutation.",
      ),
      optionalFlag(
        "actor",
        "string",
        "Explicit acting Mind identity; must match the verified session when supplied.",
      ),
      optionalFlag("force", "bool", "Force clean all completed items."),
      optionalFlag("dry-run", "bool", "Simulate clean without mutating files."),
      optionalFlag("queue-file", "string", "Override queue file path."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
      optionalFlag("archive-file", "string", "Override archive destination file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts queue:clean --authority-run <run>"],
    authority: {
      requiresActingIdentity: true,
      authorityRunFlag: "authority-run",
      allowedRoles: ["mind"],
      constrainedPathFlags: ["queue-file", "queue-path", "archive-file"],
    },
    handler: mindQueueCleanCommand,
  },
];
