import type { CommandSpec } from "./types.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag } from "./types.ts";
import {
  reportUnifiedCommand,
  reportDagCommand,
  reportGraphCommand,
  reportGraphJsonCommand,
  reportHealthCommand,
  reportLeasesCommand,
  reportDecisionsCommand,
} from "../commands/unified-reporting.ts";
import { summaryViewCommand } from "../commands/summary-ops.ts";
import { reportGetCommand } from "../commands/inspection-ops.ts";
import { streamEventsCommand } from "../commands/stream-events.ts";
import { exportGraphJsonCommand } from "../commands/graph-export.ts";
import { dagViewCommand } from "../commands/dag-view.ts";
import { dagRenderCommand, dagTraceCommand } from "../commands/dag.ts";
import { usageReportCommand } from "../commands/usage-report.ts";

export const REPORTING_COMMANDS: readonly CommandSpec[] = [
  {
    name: "report",
    aliases: ["report:all"],
    domain: "reporting",
    summary:
      "Deliver unified topology, lifecycle tier breakdown, agent roles, IDs, and timestamps.",
    description:
      "Generates comprehensive unified run report across tasks, topology, agent lifecycle tiers, and audit trail.",
    flags: [
      optionalFlag(
        "run",
        "string",
        "Capsule run root. Defaults to current repository .olt/capsules/ when omitted.",
      ),
      optionalFlag("run-id", "string", "Alias of --run."),
      optionalFlag("repo", "string", "Repository root to search for .olt/capsules/.", "."),
      optionalFlag("detailed", "bool", "Detailed topology and audit forensics."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts report --run .olt/capsules/<run-id>",
      "bun harness.ts report:unified --run .olt/capsules/<run-id>",
    ],
    handler: reportUnifiedCommand,
  },
  {
    name: "report:graph-json",
    aliases: ["dag:export-json"],
    domain: "reporting",
    summary: "Export DAG telemetry and metrics to JSON.",
    description: "Export DAG telemetry and metrics to JSON.",
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    flags: [
      optionalFlag("run", "string", "Path to capsule run directory"),
      optionalFlag("run-id", "string", "Capsule run identifier"),
      optionalFlag("out", "string", "Path to save JSON"),
      optionalFlag("pretty", "bool", "Format output JSON nicely"),
    ],
    examples: ["bun harness.ts report:graph-json --run .olt/capsules/<run-id> --out graph.json"],
    handler: exportGraphJsonCommand,
  },
  {
    name: "report:dag",
    aliases: [],
    domain: "reporting",
    summary: "Canonical reporting for DAG status.",
    description:
      "Aliases/links to dag:view to inspect compiled graph or planning buffer DAG topology.",
    flags: [
      optionalFlag(
        "run",
        "string",
        "Capsule run root. Defaults to current repository .olt/capsules/ when omitted.",
      ),
      optionalFlag("run-id", "string", "Alias of --run."),
      optionalFlag("repo", "string", "Repository root to search for .olt/capsules/.", "."),
      optionalFlag(
        "detailed",
        "bool",
        "Render full write scopes, gate commands, and dependency lists.",
      ),
      optionalFlag(
        "recommendations",
        "bool",
        "Highlight algorithmic parallelization opportunities.",
      ),
      optionalFlag("all", "bool", "Do not truncate output lines."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:dag --run .olt/capsules/<run-id>"],
    handler: reportDagCommand,
  },
  {
    name: "report:graph",
    aliases: [],
    domain: "reporting",
    summary: "Visual/ASCII and graph overview.",
    description: "Renders the task graph.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("detailed", "bool", "Detailed output."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:graph --run .olt/capsules/<run-id>"],
    handler: reportGraphCommand,
  },
  {
    name: "report:health",
    aliases: [],
    domain: "reporting",
    summary: "Canonical reporting for health/doctor status.",
    description: "Runs the capsule doctor to check health status.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("source", "string", "Source."),
      optionalFlag("home", "string", "Home."),
      optionalFlag("clients", "string", "Clients."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:health --run .olt/capsules/<run-id>"],
    handler: reportHealthCommand,
  },
  {
    name: "report:leases",
    aliases: [],
    domain: "reporting",
    summary: "Active lease and agent matrix.",
    description: "Reports the matrix of active leases.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:leases --run .olt/capsules/<run-id>"],
    handler: reportLeasesCommand,
  },
  {
    name: "report:decisions",
    aliases: [],
    domain: "reporting",
    summary: "Inspection of authority decisions and governance audit.",
    description: "Reports the decisions audit matrix.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:decisions --run .olt/capsules/<run-id>"],
    handler: reportDecisionsCommand,
  },
  {
    name: "report:summary",
    aliases: [],
    domain: "reporting",
    summary: "Render executive summary brief of capsule run.",
    description: "Renders the executive brief in markdown or JSON directly to terminal.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("out", "string", "Directory for viewer registry export."),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:summary --run .olt/capsules/<run-id>"],
    handler: summaryViewCommand,
  },
  {
    name: "report:task",
    aliases: [],
    domain: "reporting",
    summary: "Read and render a task submission, review or critic report.",
    description:
      "Extracts and formats full task report evidence including verification outcomes, gate executions, and screenshot records without requiring raw file inspection.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Task whose report is wanted."),
      optionalFlag("critic", "bool", "Read the critic review report."),
      optionalFlag("submission", "bool", "Force the submission report."),
      optionalFlag("review", "bool", "Force the review report."),
      optionalFlag("type", "string", "submission, review or critic."),
      optionalFlag("stage", "string", "Alias of --type."),
      optionalFlag("report", "string", "Explicit report file name."),
      optionalFlag("id", "string", "Alias of --report."),
      optionalFlag("screenshots", "bool", "Include screenshot records."),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts report:task --run .olt/capsules/<run-id> --task task-1",
      "bun harness.ts report:task --run .olt/capsules/<run-id> --task task-1 --type review",
    ],
    handler: reportGetCommand,
  },
  {
    name: "stream:events",
    aliases: ["events:stream", "events:tail"],
    domain: "reporting",
    summary: "Stream, query, and tail structured capsule events.",
    description:
      "Streams chronological capsule events as rich terminal ASCII tables, Markdown, or NDJSON, with sequence filtering and optional webhook delivery.",
    flags: [
      optionalFlag("run", "string", "Capsule run root."),
      optionalFlag("run-id", "string", "Capsule run identifier."),
      optionalFlag("repo", "string", "Repository root."),
      optionalFlag("from-seq", "int", "Starting event sequence number."),
      optionalFlag("to-seq", "int", "Ending event sequence number."),
      optionalFlag("max-events", "int", "Maximum events to return.", 50),
      optionalFlag("filter-type", "string", "Filter events by event type name."),
      optionalFlag("filter-actor", "string", "Filter events by acting agent ID."),
      optionalFlag("all", "bool", "Return all matching events."),
      optionalFlag("now", "bool", "Return only the latest event in the log."),
      optionalFlag("format", "string", "Output format: markdown, json, or ndjson."),
      optionalFlag("webhook-url", "string", "Webhook endpoint URL for event forwarding."),
      optionalFlag("webhook-retries", "int", "Webhook retry attempts.", 3),
      optionalFlag("webhook-timeout", "int", "Webhook request timeout in ms.", 5000),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts stream:events --run .olt/capsules/<run-id>",
      "bun harness.ts stream:events --run .olt/capsules/<run-id> --from-seq 10 --max-events 20",
      "bun harness.ts stream:events --run .olt/capsules/<run-id> --filter-type task-claimed",
    ],
    handler: streamEventsCommand,
  },
  {
    name: "dag",
    aliases: [
      "dag:render",
      "dag:view",
      "graph:sugiyama",
      "report:sugiyama",
      "graph:ascii",
      "status:dag",
    ],
    domain: "reporting",
    summary:
      "Render Sugiyama hierarchical DAG layout with rounded Unicode boxes and cycle diagnostics.",
    description:
      "Computes Sugiyama layered layout, crossing minimization via barycenter heuristics, Tarjan cycle alerts, illegal bypass warnings, and orthogonal connectors.",
    flags: [
      optionalFlag(
        "run",
        "string",
        "Capsule run root. Defaults to current repository .olt/capsules/ when omitted.",
      ),
      optionalFlag("run-id", "string", "Alias of --run."),
      optionalFlag("repo", "string", "Repository root to search for .olt/capsules/.", "."),
      optionalFlag(
        "detailed",
        "bool",
        "Render full write scopes, gate commands, and dependency lists.",
      ),
      optionalFlag(
        "recommendations",
        "bool",
        "Include algorithmic parallelization recommendations.",
      ),
      optionalFlag("box-style", "string", "Box border style: rounded, sharp, or ascii.", "rounded"),
      optionalFlag("all", "bool", "Do not truncate output lines."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts dag:render --run .olt/capsules/<run-id>",
      "bun harness.ts dag:render --detailed --box-style rounded",
    ],
    handler: dagViewCommand,
  },
  {
    name: "dag:trace",
    aliases: ["trace:dag", "stream:trace"],
    domain: "reporting",
    summary: "Real-time step tracer and dynamic living DAG expansion timeline.",
    description:
      "Replays events.jsonl to construct dynamic branch expansions and renders a chronological vertical step timeline with status glyphs and telemetry.",
    flags: [
      optionalFlag("run", "string", "Capsule run root."),
      optionalFlag("run-id", "string", "Capsule run identifier."),
      optionalFlag("repo", "string", "Repository root."),
      optionalFlag("from-seq", "int", "Starting event sequence number."),
      optionalFlag("to-seq", "int", "Ending event sequence number."),
      optionalFlag("max-steps", "int", "Maximum step entries to display.", 50),
      optionalFlag("task", "string", "Filter steps by task ID."),
      optionalFlag("actor", "string", "Filter steps by agent ID."),
      optionalFlag("filter-type", "string", "Filter steps by event kind."),
      optionalFlag("detailed", "bool", "Detailed step inspection."),
      optionalFlag("all", "bool", "Return all steps without line truncation."),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts dag:trace --run .olt/capsules/<run-id>",
      "bun harness.ts dag:trace --run .olt/capsules/<run-id> --task task-1",
    ],
    handler: dagTraceCommand,
  },
  {
    name: "usage:report",
    aliases: ["telemetry:usage", "quota:report"],
    domain: "reporting",
    summary: "Discover and report cross-platform quota, rate limit, and token usage telemetry.",
    description:
      "Autonomously probes frontier LLM platforms (Antigravity, Claude, Cursor, OpenAI/Codex) using a 3-tier fallback strategy and generates unified ASCII telemetry tables.",
    flags: [
      optionalFlag(
        "platform",
        "string",
        "Filter probe to a specific platform ID (antigravity, claude, cursor, openai, codex).",
      ),
      optionalFlag("detailed", "bool", "Include full raw vendor observation payloads."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts usage:report",
      "bun harness.ts usage:report --platform antigravity",
      "bun harness.ts usage:report --detailed",
    ],
    handler: usageReportCommand,
  },
];
