import type { CommandSpec } from "./types.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag } from "./types.ts";
import {
  reportUnifiedCommand, reportDagCommand, reportGraphCommand, reportGraphJsonCommand,
  reportHealthCommand, reportLeasesCommand, reportDecisionsCommand,
} from "../commands/unified-reporting.ts";
import { summaryViewCommand } from "../commands/summary-ops.ts";
import { reportGetCommand } from "../commands/inspection-ops.ts";
import { streamEventsCommand } from "../commands/stream-events.ts";
import { exportGraphJsonCommand } from "../commands/graph-export.ts";
import { dagViewCommand } from "../commands/dag-view.ts";
import { dagRenderCommand, dagTraceCommand } from "../commands/dag.ts";
import { usageReportCommand } from "../commands/usage-report.ts";
import { quotaCheckCommand } from "../commands/quota-check.ts";
import { quotaFreezeCommand } from "../commands/quota-freeze.ts";
import { quotaResumeCommand } from "../commands/quota-resume.ts";
import { skillAuditLiveCommand } from "../commands/skill-audit-live.ts";
import { notifyPhaseCommand, notifyTestCommand } from "../commands/index.ts";

export {
  reportUnifiedCommand, reportDagCommand, reportGraphCommand, reportGraphJsonCommand,
  reportHealthCommand, reportLeasesCommand, reportDecisionsCommand, summaryViewCommand,
  reportGetCommand, streamEventsCommand, exportGraphJsonCommand, dagViewCommand,
  dagRenderCommand, dagTraceCommand, usageReportCommand, quotaCheckCommand,
  quotaFreezeCommand, quotaResumeCommand, skillAuditLiveCommand, notifyPhaseCommand,
  notifyTestCommand,
};

export const REPORTING_COMMANDS: readonly CommandSpec[] = [
  {
    name: "report", aliases: [], domain: "reporting",
    summary: "Deliver unified topology, lifecycle tier breakdown, agent roles, IDs, and timestamps.",
    description: "Generates comprehensive unified run report across tasks, topology, agent lifecycle tiers, and audit trail.",
    flags: [
      optionalFlag("run", "string", "Capsule run root. Defaults to current repository .olt/capsules/ when omitted."),
      optionalFlag("run-id", "string", "Alias of --run."),
      optionalFlag("repo", "string", "Repository root to search for .olt/capsules/.", "."),
      optionalFlag("detailed", "bool", "Detailed topology and audit forensics."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report --run .olt/capsules/<run-id>"], handler: reportUnifiedCommand,
  },
  {
    name: "report:summary", aliases: [], domain: "reporting",
    summary: "Render executive summary brief of capsule run.",
    description: "Renders the executive brief in markdown or JSON directly to terminal.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("out", "string", "Directory for viewer registry export."),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:summary --run .olt/capsules/<run-id>"], handler: summaryViewCommand,
  },
  {
    name: "report:task", aliases: [], domain: "reporting",
    summary: "Read and render a task submission, review or critic report.",
    description: "Extracts and formats full task report evidence including verification outcomes, gate executions, and screenshot records without requiring raw file inspection.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Task whose report is wanted."),
      optionalFlag("critic", "bool", "Read the critic review report."),
      optionalFlag("submission", "bool", "Force the submission report."),
      optionalFlag("review", "bool", "Force the review report."),
      optionalFlag("type", "string", "submission, review or critic."),
      optionalFlag("stage", "string", "Alias of --type."),
      optionalFlag("report", "string", "Explicit report file name."),
      optionalFlag("id", "string", "Alias of --report."),
      optionalFlag("screenshots", "bool", "Include screenshot records."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts report:task --run .olt/capsules/<run-id> --task task-1",
      "bun harness.ts report:task --run .olt/capsules/<run-id> --task task-1 --type review",
    ],
    handler: reportGetCommand,
  },
  {
    name: "report:health", aliases: [], domain: "reporting",
    summary: "Canonical reporting for health/doctor status.",
    description: "Runs the capsule doctor to check health status.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("source", "string", "Source."),
      optionalFlag("home", "string", "Home."),
      optionalFlag("clients", "string", "Clients."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:health --run .olt/capsules/<run-id>"], handler: reportHealthCommand,
  },
  {
    name: "report:leases", aliases: [], domain: "reporting",
    summary: "Active lease and agent matrix.",
    description: "Reports the matrix of active leases.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:leases --run .olt/capsules/<run-id>"], handler: reportLeasesCommand,
  },
  {
    name: "report:decisions", aliases: [], domain: "reporting",
    summary: "Inspection of authority decisions and governance audit.",
    description: "Reports the decisions audit matrix.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:decisions --run .olt/capsules/<run-id>"], handler: reportDecisionsCommand,
  },
  {
    name: "report:usage", aliases: [], domain: "reporting",
    summary: "Discover and report cross-platform quota, rate limit, and token usage telemetry.",
    description: "Autonomously probes frontier LLM platforms (Antigravity, Claude, Cursor, OpenAI/Codex) using a 3-tier fallback strategy and generates unified ASCII telemetry tables.",
    flags: [
      optionalFlag("platform", "string", "Filter probe to a specific platform ID (antigravity, claude, cursor, openai, codex)."),
      optionalFlag("detailed", "bool", "Include full raw vendor observation payloads."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts report:usage",
      "bun harness.ts report:usage --platform antigravity",
      "bun harness.ts report:usage --detailed",
    ],
    handler: usageReportCommand,
  },
  {
    name: "report:dag", aliases: ["dag", "dag:render", "dag:view", "graph:render"], domain: "reporting",
    summary: "Render Sugiyama hierarchical DAG layout with rounded Unicode boxes and cycle diagnostics.",
    description: "Computes Sugiyama layered layout, crossing minimization via barycenter heuristics, Tarjan cycle alerts, illegal bypass warnings, and orthogonal connectors.",
    flags: [
      optionalFlag("run", "string", "Capsule run root. Defaults to current repository .olt/capsules/ when omitted."),
      optionalFlag("run-id", "string", "Alias of --run."),
      optionalFlag("repo", "string", "Repository root to search for .olt/capsules/.", "."),
      optionalFlag("detailed", "bool", "Render full write scopes, gate commands, and dependency lists."),
      optionalFlag("recommendations", "bool", "Include algorithmic parallelization recommendations."),
      optionalFlag("box-style", "string", "Box border style: rounded, sharp, or ascii.", "rounded"),
      optionalFlag("all", "bool", "Do not truncate output lines."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:dag --run .olt/capsules/<run-id>"], handler: dagViewCommand,
  },
  {
    name: "report:graph-json", aliases: [], domain: "reporting",
    summary: "Export DAG telemetry and metrics to JSON.",
    description: "Export DAG telemetry and metrics to JSON.",
    flags: [
      optionalFlag("run", "string", "Path to capsule run directory"),
      optionalFlag("run-id", "string", "Capsule run identifier"),
      optionalFlag("out", "string", "Path to save JSON"),
      optionalFlag("pretty", "bool", "Format output JSON nicely"),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts report:graph-json --run .olt/capsules/<run-id> --out graph.json"], handler: exportGraphJsonCommand,
  },
  {
    name: "events:stream", aliases: [], domain: "reporting",
    summary: "Stream, query, and tail structured capsule events.",
    description: "Streams chronological capsule events as rich terminal ASCII tables, Markdown, or NDJSON, with sequence filtering and optional webhook delivery.",
    flags: [
      optionalFlag("run", "string", "Capsule run root."),
      optionalFlag("run-id", "string", "Capsule run identifier."),
      optionalFlag("repo", "string", "Repository root."),
      optionalFlag("from-seq", "int", "Starting event sequence number."),
      optionalFlag("to-seq", "int", "Ending event sequence number."),
      optionalFlag("max-events", "int", "Maximum events to return.", 50),
      optionalFlag("filter-type", "string", "Filter events by event type name."),
      optionalFlag("filter-actor", "string", "Filter events by acting agent ID."),
      optionalFlag("all", "bool", "Return all matching events."),
      optionalFlag("now", "bool", "Return only the latest event in the log."),
      optionalFlag("format", "string", "Output format: markdown, json, or ndjson."),
      optionalFlag("webhook-url", "string", "Webhook endpoint URL for event forwarding."),
      optionalFlag("webhook-retries", "int", "Webhook retry attempts.", 3),
      optionalFlag("webhook-timeout", "int", "Webhook request timeout in ms.", 5000),
      optionalFlag("json", "bool", "Output JSON."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts events:stream --run .olt/capsules/<run-id>"], handler: streamEventsCommand,
  },
  {
    name: "events:trace", aliases: [], domain: "reporting",
    summary: "Real-time step tracer and dynamic living DAG expansion timeline.",
    description: "Replays events.jsonl to construct dynamic branch expansions and renders a chronological vertical step timeline with status glyphs and telemetry.",
    flags: [
      optionalFlag("run", "string", "Capsule run root."),
      optionalFlag("run-id", "string", "Capsule run identifier."),
      optionalFlag("repo", "string", "Repository root."),
      optionalFlag("from-seq", "int", "Starting event sequence number."),
      optionalFlag("to-seq", "int", "Ending event sequence number."),
      optionalFlag("max-steps", "int", "Maximum step entries to display.", 50),
      optionalFlag("task", "string", "Filter steps by task ID."),
      optionalFlag("actor", "string", "Filter steps by agent ID."),
      optionalFlag("filter-type", "string", "Filter steps by event kind."),
      optionalFlag("detailed", "bool", "Detailed step inspection."),
      optionalFlag("all", "bool", "Return all steps without line truncation."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts events:trace --run .olt/capsules/<run-id>"], handler: dagTraceCommand,
  },
  {
    name: "quota:check", aliases: [], domain: "reporting",
    summary: "Evaluate quota circuit-breaker status, wrap-up directives, and auto-wake timer schedule.",
    description: "Probes cross-platform quota telemetry, detects exhaustion (<10%), generates wrap-up directives for active agents, and computes one-shot auto-wake scheduler payloads.",
    flags: [
      optionalFlag("platform", "string", "Filter probe to a specific platform ID (antigravity, claude, cursor, openai, codex)."),
      optionalFlag("threshold", "string", "Quota percentage threshold to trigger circuit breaker (default: 10.0).", "10.0"),
      optionalFlag("active-agents", "int", "Number of currently active agents to register in auto-wake schedule.", 0),
      optionalFlag("detailed", "bool", "Include full vendor observation payloads."),
      optionalFlag("json", "bool", "Output structured JSON report."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts quota:check"], handler: quotaCheckCommand,
  },
  {
    name: "quota:freeze", aliases: [], domain: "reporting",
    summary: "Initiate DAG quota freeze and create a snapshot.",
    description: "Probes quota telemetry and freezes DAG operations if circuit breaker is triggered or force is applied. Outputs state to a snapshot file.",
    flags: [
      optionalFlag("repo", "string", "Must resolve to the verified run repository."),
      requiredFlag("run", "string", "Verified capsule run root."),
      requiredFlag("actor", "string", "Acting mind or orchestrator agent ID."),
      optionalFlag("threshold", "string", "Quota percentage threshold (default: 10.0).", "10.0"),
      optionalFlag("active-agents", "int", "Number of currently active agents.", 0),
      optionalFlag("force", "bool", "Override quota policy only; never bypasses quota evidence.", false),
      optionalFlag("json", "bool", "Output structured JSON report."),
      optionalFlag("detailed", "bool", "Detailed markdown output."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts quota:freeze --run .olt/capsules/<run-id> --actor mind_1"], handler: quotaFreezeCommand,
  },
  {
    name: "quota:resume", aliases: [], domain: "reporting",
    summary: "Resume DAG operations from a quota freeze snapshot.",
    description: "Probes quota telemetry and resumes operations from a prior freeze if quota is healthy or force is applied.",
    flags: [
      optionalFlag("repo", "string", "Must resolve to the verified run repository."),
      requiredFlag("run", "string", "Verified capsule run root."),
      requiredFlag("actor", "string", "Acting mind or orchestrator agent ID."),
      optionalFlag("threshold", "string", "Quota percentage threshold (default: 10.0).", "10.0"),
      optionalFlag("force", "bool", "Override quota policy only; does not bypass run or grant authority.", false),
      optionalFlag("json", "bool", "Output structured JSON report."),
      optionalFlag("detailed", "bool", "Detailed markdown output."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts quota:resume --run .olt/capsules/<run-id> --actor mind_1"], handler: quotaResumeCommand,
  },
  {
    name: "skill:audit:live", aliases: [], domain: "reporting",
    summary: "Live Tier 0 out-of-band audit of skill compliance and delta event forensics.",
    description: "Scans incremental delta events, audits cognitive contracts, and routes defects upstream.",
    flags: [
      optionalFlag("repo", "string", "Repository root path."),
      optionalFlag("run", "string", "Target capsule run root directory."),
      optionalFlag("log-defects", "bool", "Automatically log detected incidents as defects.", true),
      optionalFlag("json", "bool", "Output structured JSON."),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts skill:audit:live"], handler: skillAuditLiveCommand,
  },
  {
    name: "notify:phase", aliases: [], domain: "reporting",
    summary: "Trigger cross-platform native OS push notification and audio chime upon phase landing.",
    description: "Dispatches native desktop banner notifications and plays the macOS Glass chime upon successful upstream release landings.",
    flags: [
      optionalFlag("phase", "string", "Name or identifier of the completed phase.", "OLT Release"),
      optionalFlag("duration-ms", "int", "Total elapsed duration in milliseconds."),
      optionalFlag("tasks", "int", "Total task count completed in the phase."),
      optionalFlag("commit", "string", "Git commit hash of the release."),
      optionalFlag("title", "string", "Custom notification title."),
      optionalFlag("subtitle", "string", "Custom notification subtitle."),
      optionalFlag("details", "string", "Additional details."),
      optionalFlag("sound", "bool", "Enable Glass audio chime (default: true).", true),
      optionalFlag("no-sound", "bool", "Disable audio chime.", false),
      optionalFlag("silent", "bool", "Suppress all audio/visual alerts.", false),
      optionalFlag("json", "bool", "Output structured JSON report.", false),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts notify:phase --phase 'Core Architecture' --tasks 12 --duration-ms 272000"], handler: notifyPhaseCommand,
  },
  {
    name: "notify:test", aliases: [], domain: "reporting",
    summary: "Send a test native OS notification and Glass chime to verify desktop integration.",
    description: "Triggers a non-blocking test notification and Glass audio chime on macOS or standard alert chime on Linux/Windows.",
    flags: [
      optionalFlag("no-sound", "bool", "Mute audio chime.", false),
      optionalFlag("json", "bool", "Output structured JSON report.", false),
    ],
    readsStdin: false, takesRemainder: false, exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts notify:test"], handler: notifyTestCommand,
  },
];
