import {
  schedBackoffCommand,
  schedEvalCommand,
  schedJitterCommand,
} from "../commands/sched-ops.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, type CommandSpec } from "./types.ts";

export const SCHED_COMMANDS: readonly CommandSpec[] = [
  {
    name: "sched:eval",
    aliases: [],
    domain: "sched",
    summary: "Calculate anti-idle scheduling intervals.",
    description:
      "Computes anti-idle sleep and rollover intervals based on work status, rate limiting, and backoff streak.",
    flags: [
      optionalFlag("pending-work", "bool", "Indicates pending work in queue."),
      optionalFlag("has-pending-work", "bool", "Alias for pending work."),
      optionalFlag("active", "bool", "Indicates active work running."),
      optionalFlag("streak", "int", "Zero-value streak count."),
      optionalFlag("zero-value-streak", "int", "Alias for streak."),
      optionalFlag("retry-after", "int", "Retry-After interval in milliseconds."),
      optionalFlag("retry-after-ms", "int", "Alias for retry-after."),
      optionalFlag("base-interval", "int", "Base interval in milliseconds."),
      optionalFlag("base-interval-ms", "int", "Alias for base-interval."),
      optionalFlag("max-interval", "int", "Maximum interval in milliseconds."),
      optionalFlag("max-interval-ms", "int", "Alias for max-interval."),
      optionalFlag("max-pause-interval", "int", "Maximum pause interval in milliseconds."),
      optionalFlag("max-pause-interval-ms", "int", "Alias for max-pause-interval."),
      optionalFlag("rate-limited", "bool", "Indicates active rate limit."),
      optionalFlag("is-rate-limited", "bool", "Alias for rate-limited."),
      optionalFlag("previous-interval", "int", "Previous interval in milliseconds."),
      optionalFlag("previous-interval-ms", "int", "Alias for previous-interval."),
      optionalFlag("jitter", "bool", "Apply random jitter."),
      optionalFlag("apply-jitter", "bool", "Alias for jitter."),
      optionalFlag("jitter-ratio", "string", "Jitter ratio fraction."),
      optionalFlag("multiplier", "string", "Exponential backoff multiplier."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts sched:eval --streak 2"],
    handler: schedEvalCommand,
  },
  {
    name: "sched:backoff",
    aliases: [],
    domain: "sched",
    summary: "Calculate backoff interval using specified strategy.",
    description:
      "Computes interval delay using exponential, linear, fibonacci, or fixed backoff strategies.",
    flags: [
      optionalFlag("base-interval", "int", "Base interval in milliseconds."),
      optionalFlag("base-interval-ms", "int", "Alias for base-interval."),
      optionalFlag("max-interval", "int", "Maximum interval in milliseconds."),
      optionalFlag("max-interval-ms", "int", "Alias for max-interval."),
      optionalFlag("streak", "int", "Consecutive streak count."),
      optionalFlag(
        "strategy",
        "string",
        "Backoff strategy (exponential, linear, fibonacci, fixed, immediate).",
      ),
      optionalFlag("multiplier", "string", "Backoff multiplier factor."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts sched:backoff --streak 3 --strategy exponential"],
    handler: schedBackoffCommand,
  },
  {
    name: "sched:jitter",
    aliases: [],
    domain: "sched",
    summary: "Apply interval jitter to a base duration.",
    description: "Calculates randomized or deterministic interval with bounded jitter ratio.",
    flags: [
      optionalFlag("interval", "int", "Base interval in milliseconds."),
      optionalFlag("interval-ms", "int", "Alias for interval."),
      optionalFlag("raw-interval-ms", "int", "Alias for interval."),
      optionalFlag("jitter-ratio", "string", "Target jitter ratio."),
      optionalFlag("min-ratio", "string", "Minimum jitter ratio."),
      optionalFlag("max-ratio", "string", "Maximum jitter ratio."),
      optionalFlag("min-interval", "int", "Minimum interval clamp in milliseconds."),
      optionalFlag("min-interval-ms", "int", "Alias for min-interval."),
      optionalFlag("max-interval", "int", "Maximum interval clamp in milliseconds."),
      optionalFlag("max-interval-ms", "int", "Alias for max-interval."),
      optionalFlag("seed", "int", "Deterministic seed value."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts sched:jitter --interval 5000 --seed 42"],
    handler: schedJitterCommand,
  },
];
