import { taskCheckCommand } from "../commands/task-check.ts";
import {
  taskAbandonCommand,
  taskAssignRepairerCommand,
  taskClaimCommand,
  taskHeartbeatCommand,
  taskProbeCommand,
  taskRejectCommand,
  taskReviewCommand,
  taskSubmitCommand,
  taskValidateStartCommand,
} from "../commands/task-ops.ts";
import { taskBriefCommand } from "../commands/task-brief.ts";
import {
  DEFAULT_EXIT_CODES,
  optionalFlag,
  repeatableFlag,
  requiredFlag,
  type CommandSpec,
} from "./types.ts";

export const TASK_COMMANDS: readonly CommandSpec[] = [
  {
    name: "task:brief",
    aliases: [],
    domain: "task",
    summary: "Generate a zero-exploration 1-shot briefing for a task.",
    description:
      "Produces a structured briefing containing assigned write scope, target files, gate commands, recommended file-scoped test commands, acceptance criteria, and next actions.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Task id to brief."),
      optionalFlag("agent", "string", "Agent id assigned to or briefing for the task."),
      optionalFlag("role", "string", "Role under which the task is being briefed."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts task:brief --run .olt/capsules/<run-id> --task task-1",
      "bun harness.ts task:brief --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --role implementer",
    ],
    handler: taskBriefCommand,
  },
  {
    name: "task:claim",
    aliases: [],
    domain: "task",
    summary: "Lease a specific ready task under a declared role.",
    description:
      "Transitions the task to leased and returns the bearer token the agent must echo back. --role is the capability contract the agent is bound to for the whole lease, so the caller names it: implementer for fresh work, repairer for a task returned by a validator.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task id to claim."),
      requiredFlag("agent", "string", "Agent id receiving the lease."),
      requiredFlag(
        "role",
        "string",
        "Role contract the agent claims under: implementer for a ready task, repairer for one in changes_requested.",
      ),
      optionalFlag("lease-duration", "int", "Lease length in seconds (5-86400)."),
      optionalFlag("lease-seconds", "int", "Alias of --lease-duration.", 1200),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts task:claim --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --role implementer",
      "bun harness.ts task:claim --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --role repairer",
    ],
    handler: taskClaimCommand,
  },
  {
    name: "task:heartbeat",
    aliases: [],
    domain: "task",
    summary: "Extend a live lease so a long edit does not expire.",
    description: "Requires the lease token; a stale or foreign token is refused.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Leased task id."),
      requiredFlag("agent", "string", "Agent holding the lease."),
      requiredFlag("token", "string", "Lease bearer token."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts task:heartbeat --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --token <token>",
    ],
    handler: taskHeartbeatCommand,
  },
  {
    name: "task:submit",
    aliases: [],
    domain: "task",
    summary: "Submit completed task work for validation.",
    description:
      "Records the submission report, audits write-scope compliance, and moves the task to submitted. --summary is mandatory unless --report supplies the whole report; nothing is substituted for it. files_changed comes from --files-changed when given, otherwise from the Git working-tree observation narrowed to the write scope; checks come from --evidence when given, otherwise from the agent's recorded commands. The command fails when neither source yields anything. C4: a content digest of the write scope is compared against the one task:claim recorded; a submission whose scope is byte-identical to its content at claim is refused unless --no-op --reason states why nothing needed to change — an unexplained no-change submission is an error, never inferred as intentional.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Leased task id."),
      requiredFlag("agent", "string", "Agent holding the lease."),
      requiredFlag("token", "string", "Lease bearer token."),
      optionalFlag(
        "summary",
        "string",
        "What the agent changed. Required unless --report carries the summary.",
      ),
      repeatableFlag("evidence", "string", "Recorded command id proving the work."),
      repeatableFlag("files-changed", "string", "Repository-relative path the agent changed."),
      optionalFlag("report", "string", "Path to a complete submission report payload."),
      optionalFlag(
        "no-op",
        "bool",
        "Declares the write scope legitimately needed no change. Requires --reason; refused if the scope actually changed since claim.",
      ),
      optionalFlag(
        "reason",
        "string",
        "Why --no-op is true. Required with --no-op, and meaningless without it.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:submit --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --token <token> --summary "Implemented user auth"',
      'bun harness.ts task:submit --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --token <token> --summary "Investigated; no code change was needed" --no-op --reason "task-0 already fixed the same defect"',
    ],
    handler: taskSubmitCommand,
  },
  {
    name: "task:validate-start",
    aliases: [],
    domain: "task",
    summary: "Dispatch an independent validator against a submitted task.",
    description: "Assigns the validator and mints the validation token required by task:review.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Submitted task id."),
      requiredFlag("validator", "string", "Validator agent id."),
      optionalFlag("lease-duration", "int", "Validation window in seconds."),
      optionalFlag(
        "validator-domain",
        "string",
        "B12.2 standing checklist domain (code-quality, product, security, system-design, ui-design); binds the matching checklist into this validator's packet. Omitted, the domain is DERIVED from the task's write scope (code-quality always applies; ui-design/system-design follow file extension and path signals) — the first applicable domain nobody has an open validation against yet. A task can carry several open validations at once, one per applicable domain; it reaches validated only once every one of them has passed.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts task:validate-start --run .olt/capsules/<run-id> --task task-1 --validator val-1",
      "bun harness.ts task:validate-start --run .olt/capsules/<run-id> --task task-1 --validator val-1 --validator-domain code-quality",
    ],
    handler: taskValidateStartCommand,
  },
  {
    name: "task:review",
    aliases: [],
    domain: "task",
    summary: "Record a validator verdict with its gate evidence.",
    description:
      "--status pass finalises the task and unblocks dependants; --status fail records a defect finding and returns the task for repair. A failing verdict must carry --summary, --severity and --remediation: they are the validator's own finding and the harness supplies no wording for them. A pass is refused while the task is short of min_adversarial_probes probes, a mandatory gate's recorded run exited non-zero, or an open finding has no --resolve answering it. Every open finding, probe demand or defect, must be answered explicitly: the harness never marks one answered on the validator's behalf. --checklist-domain plus --checklist-report (B12.5) attach standing-checklist coverage to the report: which items were checked and passed, which were not applicable, which could not be checked, and any standing-standard finding outside this task's own scope. None of it gates this task's verdict; the report states it separately so the coverage is visible rather than implied.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."),
      requiredFlag("token", "string", "Validation token."),
      requiredFlag("status", "string", "pass or fail."),
      optionalFlag(
        "summary",
        "string",
        "Verdict summary; with --status fail this is the defect the validator observed and is required.",
      ),
      optionalFlag(
        "severity",
        "string",
        "critical, important or minor. Required with --status fail; there is no default severity.",
      ),
      optionalFlag(
        "remediation",
        "string",
        "What would fix the defect. Required with --status fail; the harness writes no remediation of its own.",
      ),
      optionalFlag(
        "revalidation",
        "string",
        "How the fix is to be proven. Without it the finding cites the task's own gate.",
      ),
      optionalFlag("evidence", "string", "Comma-separated command ids proving the verdict."),
      optionalFlag("checks", "string", "Alias of --evidence."),
      optionalFlag("finding-id", "string", "Explicit finding id for a failing verdict."),
      optionalFlag("requirement", "string", "Requirement a failing verdict binds its finding to."),
      repeatableFlag(
        "resolve",
        "string",
        "Answer an open finding: <finding-id>=<command-id>[,<command-id>].",
      ),
      repeatableFlag(
        "resolution-method",
        "string",
        "How a finding was answered: <finding-id>=<method>; defaults to the finding's class.",
      ),
      optionalFlag(
        "checklist-domain",
        "string",
        "B12.5: the standing checklist (code-quality, product, security, system-design, ui-design) this review reports coverage against. Requires --checklist-report; every item in that domain's checklist must be accounted for.",
      ),
      optionalFlag(
        "checklist-report",
        "string",
        'Path to a JSON file: {"items":[{"id":"<checklist-id>","disposition":"checked|not_applicable|could_not_check","reason":"<required unless checked>"}, ...],"adjacent_findings":[{"id","checklist_item_id","severity","observation","remediation","evidence":[...]}]}. Requires --checklist-domain.',
      ),
      optionalFlag(
        "require-semantic-depth",
        "bool",
        "Enforce strict semantic depth audits on companion manifest criteria and cognitive questions.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:review --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --status pass --checks C-123 --summary "All gates pass"',
      "bun harness.ts task:review --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --status pass --checks C-123 --resolve probe-task-1-01-1=C-123",
      'bun harness.ts task:review --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --status fail --summary "Gate command never ran against the new schema" --severity critical --remediation "Point the gate at tests/db and rerun it"',
      'bun harness.ts task:review --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --status pass --checks C-123 --summary "All gates pass" --checklist-domain code-quality --checklist-report coverage.json',
    ],
    handler: taskReviewCommand,
  },
  {
    name: "task:probe",
    aliases: [],
    domain: "task",
    summary: "Record the mandatory adversarial probe: a demand for proof, not a rejection.",
    description:
      "Each --demand becomes a probe_demand finding on the task. The task stays in validating under the same validator, repair_round is untouched, and task:review --status pass stays blocked until min_adversarial_probes rounds are recorded and every demand is answered with command evidence.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."),
      requiredFlag("token", "string", "Validation token."),
      repeatableFlag("demand", "string", "What the implementation must prove; repeat per demand."),
      optionalFlag("requirement", "string", "Requirement the demands bind to."),
      optionalFlag("revalidation", "string", "How each demand is to be answered."),
      optionalFlag("evidence", "string", "Comma-separated command ids the demands cite."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:probe --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --demand "Prove the parser rejects an empty payload"',
    ],
    handler: taskProbeCommand,
  },
  {
    name: "task:reject",
    aliases: [],
    domain: "task",
    summary: "Reject a task with a structured finding for targeted repair.",
    description:
      "Records the validator's finding and returns the task to the implementer. The severity and the remediation are the validator's own judgement, so both are demanded; nothing is graded or worded on its behalf.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."),
      requiredFlag("token", "string", "Validation token."),
      requiredFlag("reason", "string", "What is defective."),
      requiredFlag("severity", "string", "critical, important or minor."),
      optionalFlag(
        "remediation",
        "string",
        "What would fix the defect. Required unless --finding carries it.",
      ),
      optionalFlag("finding", "string", "Alias of --remediation."),
      optionalFlag("finding-id", "string", "Explicit finding id."),
      optionalFlag("evidence", "string", "Comma-separated command ids proving the defect."),
      optionalFlag("checks", "string", "Alias of --evidence."),
      optionalFlag("requirement", "string", "Requirement the finding binds to."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:reject --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --reason "Missing input validation" --severity critical --remediation "Validate the payload before the insert"',
    ],
    handler: taskRejectCommand,
  },
  {
    name: "task:assign-repairer",
    aliases: [],
    domain: "task",
    summary: "Replace the original implementer as a task's repairer, with a recorded reason.",
    description:
      "The original implementer always gets the first repair opportunity; this records the harness's own decision to hand the repair lease to someone else instead. --reason stale requires the prior repair attempt's lease to have gone stale; --reason repeated_failure requires at least two recorded repair rounds; --reason unavailable carries no precondition beyond the task already awaiting its original repairer.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task in changes_requested, awaiting its original repairer."),
      requiredFlag("actor", "string", "Who is recording the reassignment."),
      requiredFlag("repairer", "string", "Replacement agent id; must differ from the original."),
      requiredFlag(
        "reason",
        "string",
        "repeated_failure, stale, or unavailable; each carries its own precondition.",
      ),
      requiredFlag("evidence", "string", "Why the replacement is warranted."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:assign-repairer --run .olt/capsules/<run-id> --task task-1 --actor coordinator --repairer worker-2 --reason unavailable --evidence "worker-1 released without claiming the repair lease"',
    ],
    handler: taskAssignRepairerCommand,
  },
  {
    name: "task:abandon",
    aliases: [],
    domain: "task",
    summary: "Close an open attempt nobody submitted or released, on the coordinator's authority.",
    description:
      "The forced counterpart to task:release: it does not require the lease token, only --actor and --reason, because it exists for a coordinator to unstick a task whose attempt is open but whose agent is gone or unresponsive. The task returns to retry_ready, or to changes_requested when the abandoned attempt was a repair. Refuses if the task's most recent attempt is already closed - there is nothing left open to abandon.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("task", "string", "Task with an open attempt."),
      requiredFlag("actor", "string", "Who is abandoning the attempt. Recorded on the event."),
      requiredFlag("reason", "string", "Why the attempt is being abandoned."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts task:abandon --run .olt/capsules/<run-id> --task task-1 --actor coordinator --reason "agent-1 crashed mid-attempt and will not return"',
    ],
    handler: taskAbandonCommand,
  },
  {
    name: "task:check",
    aliases: [],
    domain: "task",
    summary: "Incremental verification.",
    description: "Check the files.",
    flags: [
      optionalFlag("run", "string", "Capsule run root."),
      optionalFlag("task", "string", "Task ID."),
      repeatableFlag("file", "string", "File path."),
      optionalFlag("typecheck", "bool", "Run typecheck."),
      optionalFlag("lint", "bool", "Run lint."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [],
    handler: taskCheckCommand,
  },
];
