import { taskCheckCommand } from "../commands/task-check.ts";
import {
  taskAbandonCommand,
  taskClaimCommand,
  taskHeartbeatCommand,
  taskProbeCommand,
  taskRejectCommand,
  taskReleaseCommand,
  taskReviewCommand,
  taskSubmitCommand,
  taskValidateStartCommand,
} from "../commands/task-ops.ts";
import { taskBriefCommand } from "../commands/task-brief.ts";
import {
  taskAddCommand,
  taskCompleteCommand,
  taskFailCommand,
  taskListCommand,
  taskLeaseCommand,
  taskPruneCommand,
} from "../commands/task-queue-ops.ts";
import {
  DEFAULT_EXIT_CODES,
  optionalFlag,
  repeatableFlag,
  requiredFlag,
  type CommandHandler,
  type CommandSpec,
  type ExitCodeSpec,
  type FlagSpec,
  type FlagType,
} from "./types.ts";

const TASK_CHECK_EXIT_CODES: readonly ExitCodeSpec[] = [
  { code: 0, meaning: "SUCCESS - verification passed" },
  { code: 1, meaning: "VERIFICATION_FAILED - violations reported" },
  ...DEFAULT_EXIT_CODES.slice(1),
];

const taskCmd = (
  name: string,
  summary: string,
  description: string,
  flags: readonly FlagSpec[],
  handler: CommandHandler,
  examples: readonly string[] = [],
  exitCodes: readonly ExitCodeSpec[] = DEFAULT_EXIT_CODES,
): CommandSpec => ({
  name,
  aliases: [],
  domain: "task",
  summary,
  description,
  flags,
  readsStdin: false,
  takesRemainder: false,
  exitCodes,
  examples,
  handler,
});

const req = (name: string, type: FlagType, desc: string) => requiredFlag(name, type, desc);
const opt = (name: string, type: FlagType, desc: string, def?: FlagSpec["default"]): FlagSpec =>
  optionalFlag(name, type, desc, def);
const rep = (name: string, type: FlagType, desc: string) => repeatableFlag(name, type, desc);

const QUEUE_PATH_FLAGS: readonly FlagSpec[] = [
  opt("queue-path", "string", "Custom task queue file path."),
  opt("path", "string", "Alias for queue-path."),
  opt("run", "string", "Capsule run root or custom queue path."),
];

const TRACING_FLAGS: readonly FlagSpec[] = [
  opt("trace-id", "string", "Trace correlation ID."),
  opt("span-id", "string", "Span ID."),
  opt("parent-span-id", "string", "Parent span correlation ID."),
  opt("trace-sampled", "bool", "Sampled tracing flag."),
];

const QUEUE_OP_FLAGS: readonly FlagSpec[] = [...QUEUE_PATH_FLAGS, ...TRACING_FLAGS];

const LEASE_HOLDER_FLAGS: readonly FlagSpec[] = [
  req("run", "string", "Capsule run root."),
  req("task", "string", "Leased task id."),
  req("agent", "string", "Agent holding the lease."),
  req("token", "string", "Lease bearer token."),
];

const REVIEW_FEEDBACK_FLAGS: readonly FlagSpec[] = [
  opt("kind", "string", "Review channel kind: cognitive or adversarial."),
  opt("micro-cycle", "bool", "Record micro-cycle feedback within active lease."),
  opt("in-lease", "bool", "Alias of --micro-cycle."),
  opt("defect", "string", "Identified defect category or description."),
  opt("max-rounds", "int", "Maximum micro-cycle rounds allowed."),
];

const TASK_ID_FLAGS: readonly FlagSpec[] = [
  opt("task", "string", "Task ID."),
  opt("task-id", "string", "Alias for task ID."),
];

const LEASE_TOKEN_FLAGS: readonly FlagSpec[] = [
  opt("lease-token", "string", "Active lease token."),
  opt("token", "string", "Alias of lease token."),
];

const ARCHIVE_PATH_FLAGS: readonly FlagSpec[] = [
  opt("completed-tasks-path", "string", "Completed tasks archive file path."),
  opt("archive-path", "string", "Alias of completed tasks archive path."),
];

export const TASK_COMMANDS: readonly CommandSpec[] = [
  taskCmd(
    "task:brief",
    "Generate a zero-exploration 1-shot briefing for a task.",
    "Produces a structured briefing containing assigned write scope, target files, gate commands, recommended file-scoped test commands, acceptance criteria, and next actions.",
    [
      req("run", "string", "Capsule run root."),
      opt("task", "string", "Task id to brief."),
      opt("agent", "string", "Agent id assigned to or briefing for the task."),
      opt("role", "string", "Role under which the task is being briefed."),
      opt("all", "bool", "Include all task details in briefing."),
    ],
    taskBriefCommand,
    ["bun harness.ts task:brief --run .olt/capsules/<run-id> --task task-1"],
  ),
  taskCmd(
    "task:claim",
    "Lease a specific ready task under a declared role.",
    "Transitions the task to leased and returns the bearer token the agent must echo back.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Task id to claim."),
      req("agent", "string", "Agent id receiving the lease."),
      req("role", "string", "Role contract the agent claims under."),
      opt("lease-duration", "int", "Lease length in seconds (5-86400)."),
      opt("lease-seconds", "int", "Alias of --lease-duration.", 1200),
    ],
    taskClaimCommand,
    ["bun harness.ts task:claim --run <run> --task t1 --agent w1 --role imp"],
  ),
  taskCmd(
    "task:heartbeat",
    "Extend a live lease so a long edit does not expire.",
    "Requires the lease token; a stale or foreign token is refused.",
    LEASE_HOLDER_FLAGS,
    taskHeartbeatCommand,
    ["bun harness.ts task:heartbeat --run <run> --task t1 --token <tok>"],
  ),
  taskCmd(
    "task:submit",
    "Submit completed task work for validation.",
    "Records the submission report, audits write-scope compliance, and moves the task to submitted.",
    [
      ...LEASE_HOLDER_FLAGS,
      opt("summary", "string", "What the agent changed."),
      rep("evidence", "string", "Recorded command id proving the work."),
      rep("files-changed", "string", "Repository-relative path the agent changed."),
      opt("report", "string", "Path to a complete submission report payload."),
      opt("no-op", "bool", "Declares the write scope legitimately needed no change."),
      opt("reason", "string", "Why --no-op is true."),
    ],
    taskSubmitCommand,
    ['bun harness.ts task:submit --run <run> --task t1 --summary "Done"'],
  ),
  taskCmd(
    "task:validate-start",
    "Dispatch an independent validator against a submitted task.",
    "Assigns the validator and mints the validation token required by task:review.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Submitted task id."),
      req("validator", "string", "Validator agent id."),
      opt("lease-duration", "int", "Validation window in seconds."),
      opt("validator-domain", "string", "B12.2 standing checklist domain."),
    ],
    taskValidateStartCommand,
    ["bun harness.ts task:validate-start --run <run> --task t1 --validator v1"],
  ),
  taskCmd(
    "task:review",
    "Record a validator verdict with its gate evidence.",
    "Records pass or fail verdict along with evidence findings.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Task under validation."),
      req("validator", "string", "Validator agent id."),
      req("token", "string", "Validation token."),
      req("status", "string", "pass or fail."),
      opt("summary", "string", "Verdict summary."),
      opt("severity", "string", "critical, important or minor."),
      opt("remediation", "string", "What would fix the defect."),
      opt("revalidation", "string", "How the fix is to be proven."),
      opt("evidence", "string", "Comma-separated command ids proving the verdict."),
      opt("checks", "string", "Alias of --evidence."),
      opt("finding-id", "string", "Explicit finding id for a failing verdict."),
      opt("requirement", "string", "Requirement a failing verdict binds its finding to."),
      rep("resolve", "string", "Answer an open finding."),
      rep("resolution-method", "string", "How a finding was answered."),
      opt("checklist-domain", "string", "Standing checklist domain."),
      opt("checklist-report", "string", "Path to a JSON checklist report file."),
      opt("require-semantic-depth", "bool", "Enforce strict semantic depth audits."),
      ...REVIEW_FEEDBACK_FLAGS,
    ],
    taskReviewCommand,
    ["bun harness.ts task:review --run <run> --task t1 --status pass"],
  ),
  taskCmd(
    "task:probe",
    "Record the mandatory adversarial probe: a demand for proof, not a rejection.",
    "Each --demand becomes a probe_demand finding on the task.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Task under validation."),
      req("validator", "string", "Validator agent id."),
      req("token", "string", "Validation token."),
      rep("demand", "string", "What the implementation must prove; repeat per demand."),
      opt("requirement", "string", "Requirement the demands bind to."),
      opt("revalidation", "string", "How each demand is to be answered."),
      opt("evidence", "string", "Comma-separated command ids the demands cite."),
      opt("kind", "string", "Review channel kind: cognitive or adversarial."),
    ],
    taskProbeCommand,
    ['bun harness.ts task:probe --run <run> --task t1 --demand "test"'],
  ),
  taskCmd(
    "task:reject",
    "Reject a task with a structured finding for targeted repair.",
    "Records the validator's finding and returns the task to the implementer.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Task under validation."),
      req("validator", "string", "Validator agent id."),
      opt("token", "string", "Validation token."),
      req("reason", "string", "What is defective."),
      opt("severity", "string", "critical, important or minor."),
      opt("remediation", "string", "What would fix the defect."),
      opt("finding", "string", "Alias of --remediation."),
      opt("finding-id", "string", "Explicit finding id."),
      opt("evidence", "string", "Comma-separated command ids proving the defect."),
      opt("checks", "string", "Alias of --evidence."),
      opt("requirement", "string", "Requirement the finding binds to."),
      ...REVIEW_FEEDBACK_FLAGS,
    ],
    taskRejectCommand,
    ['bun harness.ts task:reject --run <run> --task t1 --reason "fail"'],
  ),
  taskCmd(
    "task:abandon",
    "Close an open attempt nobody submitted or released, on the coordinator's authority.",
    "Forced counterpart to task:release for unsticking abandoned tasks.",
    [
      req("run", "string", "Capsule run root."),
      req("task", "string", "Task with an open attempt."),
      req("actor", "string", "Who is abandoning the attempt."),
      req("reason", "string", "Why the attempt is being abandoned."),
    ],
    taskAbandonCommand,
    ['bun harness.ts task:abandon --run <run> --task t1 --reason "crash"'],
  ),
  taskCmd(
    "task:release",
    "Hand a live lease back without waiting for it to expire.",
    "The voluntary counterpart to `recover`. Requires the live lease token; the task returns to retry_ready, or to changes_requested when the released attempt was a repair. A branched task cannot be released - collect or abandon the branch first.",
    LEASE_HOLDER_FLAGS,
    taskReleaseCommand,
    ["bun harness.ts task:release --run <run> --task t1 --agent w1"],
  ),
  taskCmd(
    "task:check",
    "Incremental verification.",
    "Check the files using AST lint audit and TypeScript typecheck pass.",
    [
      opt("run", "string", "Capsule run root."),
      opt("task", "string", "Task ID."),
      rep("file", "string", "File path."),
      opt("actor", "string", "Who is running the check."),
      opt("typecheck", "bool", "Force the typecheck pass to run."),
      opt("lint", "bool", "Run only the AST lint audit."),
      opt("format", "string", "Output format (json, text, etc.)."),
    ],
    taskCheckCommand,
    ["bun harness.ts task:check --file src/index.ts"],
    TASK_CHECK_EXIT_CODES,
  ),
  taskCmd(
    "task:add",
    "Enqueue a task in the task queue.",
    "Appends a new task item into the task queue with dependency graph validation.",
    [
      ...TASK_ID_FLAGS,
      opt("title", "string", "Task title."),
      opt("description", "string", "Task description."),
      opt("priority", "string", "Task priority (CRITICAL, HIGH, MEDIUM, LOW)."),
      opt("gate", "string", "Gate verification command."),
      rep("write-scope", "string", "Assigned writable file path."),
      rep("charter-goals", "string", "Charter goal identifiers."),
      rep("acceptance-criteria", "string", "Acceptance criteria items."),
      rep("dependencies", "string", "Task dependency IDs."),
      opt("source-type", "string", "Task source type."),
      opt("status", "string", "Initial task status."),
      opt("assigned-tier", "string", "Assigned execution tier."),
      opt("assigned-role", "string", "Assigned agent role."),
      opt("max-retries", "int", "Maximum retry count."),
      ...QUEUE_OP_FLAGS,
    ],
    taskAddCommand,
    ['bun harness.ts task:add --task task-1 --title "Implement auth" --gate "bun test"'],
  ),
  taskCmd(
    "task:list",
    "List tasks in the task queue.",
    "Queries and lists queue items with filtering and queue statistics.",
    [
      opt("capsule", "string", "Alias for run."),
      opt("status", "string", "Filter tasks by status."),
      opt("priority", "string", "Filter tasks by priority."),
      opt("agent-id", "string", "Filter tasks by assigned agent ID."),
      opt("search", "string", "Filter tasks by substring in ID or title."),
      opt("limit", "int", "Maximum number of tasks to return."),
      opt("offset", "int", "Pagination offset."),
      opt("page", "int", "Pagination page number."),
      ...QUEUE_PATH_FLAGS,
      opt("stats", "bool", "Include queue statistics in output."),
      ...TRACING_FLAGS,
    ],
    taskListCommand,
    ["bun harness.ts task:list --status PENDING"],
  ),
  taskCmd(
    "task:lease",
    "Claim an active lease on a task in the queue.",
    "Claims an exclusive active lease on a task for an agent worker.",
    [
      ...TASK_ID_FLAGS,
      opt("agent-id", "string", "Agent ID claiming the lease."),
      opt("lease-duration", "int", "Lease duration in seconds."),
      opt("duration-seconds", "int", "Alias of lease duration."),
      ...QUEUE_OP_FLAGS,
    ],
    taskLeaseCommand,
    ["bun harness.ts task:lease --task task-1 --agent-id worker-1"],
  ),
  taskCmd(
    "task:complete",
    "Mark a task as completed in the queue.",
    "Records task completion, unblocks downstream dependents, and optionally archives the task.",
    [
      ...TASK_ID_FLAGS,
      opt("agent-id", "string", "Agent ID completing the task."),
      ...LEASE_TOKEN_FLAGS,
      opt("proof-summary", "string", "Summary proof of task completion."),
      opt("test-path", "string", "Test file path demonstrating completion."),
      opt("commit-sha", "string", "Commit SHA associated with completion."),
      opt("auto-archive", "bool", "Automatically archive completed task."),
      opt("auto-prune", "bool", "Automatically prune completed task from queue."),
      ...ARCHIVE_PATH_FLAGS,
      ...QUEUE_OP_FLAGS,
    ],
    taskCompleteCommand,
    ['bun harness.ts task:complete --task task-1 --proof-summary "All tests pass"'],
  ),
  taskCmd(
    "task:fail",
    "Mark a task as failed in the queue.",
    "Transitions task to failed or increments retry count if retries remain.",
    [
      ...TASK_ID_FLAGS,
      opt("id", "string", "Alias of task ID."),
      opt("message", "string", "Failure error message."),
      opt("error", "string", "Alias of error message."),
      opt("reason", "string", "Alias of error message."),
      opt("agent", "string", "Alias of agent ID."),
      opt("agent-id", "string", "Agent ID recording failure."),
      ...LEASE_TOKEN_FLAGS,
      opt("can-retry", "bool", "Allow task retry if retry count permits."),
      opt("escalate", "bool", "Escalate task upon reaching max retries."),
      ...QUEUE_PATH_FLAGS,
    ],
    taskFailCommand,
    ['bun harness.ts task:fail --task task-1 --message "Test failure"'],
  ),
  taskCmd(
    "task:prune",
    "Prune completed tasks from the queue.",
    "Removes completed tasks from the active queue and archives them to completed log.",
    [
      ...ARCHIVE_PATH_FLAGS,
      opt("auto-archive", "bool", "Archive completed tasks before pruning."),
      opt("no-auto-archive", "bool", "Disable archiving completed tasks before pruning."),
      ...QUEUE_PATH_FLAGS,
    ],
    taskPruneCommand,
    ["bun harness.ts task:prune"],
  ),
];
