import { taskCheckCommand } from "../commands/task-check.ts";
import {
  taskAbandonCommand, taskAssignRepairerCommand, taskClaimCommand, taskHeartbeatCommand,
  taskProbeCommand, taskRejectCommand, taskReviewCommand, taskSubmitCommand, taskValidateStartCommand,
} from "../commands/task-ops.ts";
import { taskBriefCommand } from "../commands/task-brief.ts";
import {
  taskAddCommand, taskListCommand, taskLeaseCommand, taskCompleteCommand, taskFailCommand, taskPruneCommand,
} from "../commands/task-queue-ops.ts";
import {
  DEFAULT_EXIT_CODES, optionalFlag, repeatableFlag, requiredFlag,
  type CommandHandler, type CommandSpec, type ExitCodeSpec, type FlagSpec,
} from "./types.ts";

export {
  taskAbandonCommand, taskAddCommand, taskAssignRepairerCommand, taskBriefCommand, taskCheckCommand,
  taskClaimCommand, taskCompleteCommand, taskFailCommand, taskHeartbeatCommand, taskLeaseCommand,
  taskListCommand, taskProbeCommand, taskPruneCommand, taskRejectCommand, taskReviewCommand,
  taskSubmitCommand, taskValidateStartCommand,
};

const TASK_CHECK_EXIT_CODES: readonly ExitCodeSpec[] = [
  { code: 0, meaning: "SUCCESS - the AST lint audit, and typecheck if requested, both passed" },
  { code: 1, meaning: "VERIFICATION_FAILED - the always-on AST lint audit or the requested typecheck reported violations" },
  ...DEFAULT_EXIT_CODES.slice(1),
];

function taskCmd(name: string, summary: string, description: string, flags: readonly FlagSpec[], handler: CommandHandler, exitCodes: readonly ExitCodeSpec[] = DEFAULT_EXIT_CODES, examples: readonly string[] = []): CommandSpec {
  return { name, aliases: [], domain: "task", summary, description, flags, readsStdin: false, takesRemainder: false, exitCodes, examples, handler };
}

export const TASK_COMMANDS: readonly CommandSpec[] = [
  taskCmd(
    "task:brief",
    "Generate a zero-exploration 1-shot briefing for a task.",
    "Produces a structured briefing containing assigned write scope, target files, gate commands, recommended file-scoped test commands, acceptance criteria, and next actions.",
    [
      requiredFlag("run", "string", "Capsule run root."), optionalFlag("task", "string", "Task id to brief."),
      optionalFlag("agent", "string", "Agent id assigned to or briefing for the task."), optionalFlag("role", "string", "Role under which the task is being briefed."),
    ],
    taskBriefCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:brief --run .olt/capsules/<run-id> --task task-1"],
  ),
  taskCmd(
    "task:claim",
    "Lease a specific ready task under a declared role.",
    "Transitions the task to leased and returns the bearer token the agent must echo back.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task id to claim."),
      requiredFlag("agent", "string", "Agent id receiving the lease."), requiredFlag("role", "string", "Role contract the agent claims under."),
      optionalFlag("lease-duration", "int", "Lease length in seconds (5-86400)."), optionalFlag("lease-seconds", "int", "Alias of --lease-duration.", 1200),
    ],
    taskClaimCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:claim --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --role implementer"],
  ),
  taskCmd(
    "task:heartbeat",
    "Extend a live lease so a long edit does not expire.",
    "Requires the lease token; a stale or foreign token is refused.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Leased task id."),
      requiredFlag("agent", "string", "Agent holding the lease."), requiredFlag("token", "string", "Lease bearer token."),
    ],
    taskHeartbeatCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:heartbeat --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --token <token>"],
  ),
  taskCmd(
    "task:submit",
    "Submit completed task work for validation.",
    "Records the submission report, audits write-scope compliance, and moves the task to submitted.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Leased task id."),
      requiredFlag("agent", "string", "Agent holding the lease."), requiredFlag("token", "string", "Lease bearer token."),
      optionalFlag("summary", "string", "What the agent changed."), repeatableFlag("evidence", "string", "Recorded command id proving the work."),
      repeatableFlag("files-changed", "string", "Repository-relative path the agent changed."), optionalFlag("report", "string", "Path to a complete submission report payload."),
      optionalFlag("no-op", "bool", "Declares the write scope legitimately needed no change."), optionalFlag("reason", "string", "Why --no-op is true."),
    ],
    taskSubmitCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:submit --run .olt/capsules/<run-id> --task task-1 --agent worker-1 --token <token> --summary "Implemented feature"'],
  ),
  taskCmd(
    "task:validate-start",
    "Dispatch an independent validator against a submitted task.",
    "Assigns the validator and mints the validation token required by task:review.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Submitted task id."),
      requiredFlag("validator", "string", "Validator agent id."), optionalFlag("lease-duration", "int", "Validation window in seconds."),
      optionalFlag("validator-domain", "string", "B12.2 standing checklist domain."),
    ],
    taskValidateStartCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:validate-start --run .olt/capsules/<run-id> --task task-1 --validator val-1"],
  ),
  taskCmd(
    "task:review",
    "Record a validator verdict with its gate evidence.",
    "Records pass or fail verdict along with evidence findings.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."), requiredFlag("token", "string", "Validation token."),
      requiredFlag("status", "string", "pass or fail."), optionalFlag("summary", "string", "Verdict summary."),
      optionalFlag("severity", "string", "critical, important or minor."), optionalFlag("remediation", "string", "What would fix the defect."),
      optionalFlag("revalidation", "string", "How the fix is to be proven."), optionalFlag("evidence", "string", "Comma-separated command ids proving the verdict."),
      optionalFlag("checks", "string", "Alias of --evidence."), optionalFlag("finding-id", "string", "Explicit finding id for a failing verdict."),
      optionalFlag("requirement", "string", "Requirement a failing verdict binds its finding to."), repeatableFlag("resolve", "string", "Answer an open finding."),
      repeatableFlag("resolution-method", "string", "How a finding was answered."), optionalFlag("checklist-domain", "string", "Standing checklist domain."),
      optionalFlag("checklist-report", "string", "Path to a JSON checklist report file."), optionalFlag("require-semantic-depth", "bool", "Enforce strict semantic depth audits."),
      optionalFlag("kind", "string", "Review channel kind: cognitive or adversarial."), optionalFlag("micro-cycle", "bool", "Record micro-cycle feedback within active lease."),
      optionalFlag("in-lease", "bool", "Alias of --micro-cycle."), optionalFlag("defect", "string", "Identified defect category or description."),
      optionalFlag("max-rounds", "int", "Maximum micro-cycle rounds allowed."),
    ],
    taskReviewCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:review --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --status pass --summary "All pass"'],
  ),
  taskCmd(
    "task:probe",
    "Record the mandatory adversarial probe: a demand for proof, not a rejection.",
    "Each --demand becomes a probe_demand finding on the task.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."), requiredFlag("token", "string", "Validation token."),
      repeatableFlag("demand", "string", "What the implementation must prove; repeat per demand."),
      optionalFlag("requirement", "string", "Requirement the demands bind to."), optionalFlag("revalidation", "string", "How each demand is to be answered."),
      optionalFlag("evidence", "string", "Comma-separated command ids the demands cite."),
    ],
    taskProbeCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:probe --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --demand "Prove parser rejects empty payload"'],
  ),
  taskCmd(
    "task:reject",
    "Reject a task with a structured finding for targeted repair.",
    "Records the validator's finding and returns the task to the implementer.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task under validation."),
      requiredFlag("validator", "string", "Validator agent id."), optionalFlag("token", "string", "Validation token."),
      requiredFlag("reason", "string", "What is defective."), optionalFlag("severity", "string", "critical, important or minor."),
      optionalFlag("remediation", "string", "What would fix the defect."), optionalFlag("finding", "string", "Alias of --remediation."),
      optionalFlag("finding-id", "string", "Explicit finding id."), optionalFlag("evidence", "string", "Comma-separated command ids proving the defect."),
      optionalFlag("checks", "string", "Alias of --evidence."), optionalFlag("requirement", "string", "Requirement the finding binds to."),
      optionalFlag("micro-cycle", "bool", "Record micro-cycle feedback within active lease."), optionalFlag("in-lease", "bool", "Alias of --micro-cycle."),
      optionalFlag("defect", "string", "Identified defect category or description."), optionalFlag("max-rounds", "int", "Maximum micro-cycle rounds allowed."),
    ],
    taskRejectCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:reject --run .olt/capsules/<run-id> --task task-1 --validator val-1 --token <token> --reason "Missing validation" --severity critical'],
  ),
  taskCmd(
    "task:assign-repairer",
    "Replace the original implementer as a task's repairer, with a recorded reason.",
    "Assigns repair lease to replacement agent with recorded justification.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task in changes_requested, awaiting its original repairer."),
      requiredFlag("actor", "string", "Who is recording the reassignment."), requiredFlag("repairer", "string", "Replacement agent id; must differ from the original."),
      requiredFlag("reason", "string", "repeated_failure, stale, or unavailable."), requiredFlag("evidence", "string", "Why the replacement is warranted."),
    ],
    taskAssignRepairerCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:assign-repairer --run .olt/capsules/<run-id> --task task-1 --actor coordinator --repairer worker-2 --reason unavailable --evidence "worker-1 released"'],
  ),
  taskCmd(
    "task:abandon",
    "Close an open attempt nobody submitted or released, on the coordinator's authority.",
    "Forced counterpart to task:release for unsticking abandoned tasks.",
    [
      requiredFlag("run", "string", "Capsule run root."), requiredFlag("task", "string", "Task with an open attempt."),
      requiredFlag("actor", "string", "Who is abandoning the attempt."), requiredFlag("reason", "string", "Why the attempt is being abandoned."),
    ],
    taskAbandonCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:abandon --run .olt/capsules/<run-id> --task task-1 --actor coordinator --reason "agent crashed"'],
  ),
  taskCmd(
    "task:check",
    "Incremental verification.",
    "Check the files using AST lint audit and TypeScript typecheck pass.",
    [
      optionalFlag("run", "string", "Capsule run root."), optionalFlag("task", "string", "Task ID."),
      repeatableFlag("file", "string", "File path."), optionalFlag("actor", "string", "Who is running the check."),
      optionalFlag("typecheck", "bool", "Force the typecheck pass to run."), optionalFlag("lint", "bool", "Run only the AST lint audit."),
    ],
    taskCheckCommand,
    TASK_CHECK_EXIT_CODES,
    ["bun harness.ts task:check --file src/index.ts"],
  ),
  taskCmd(
    "task:add",
    "Enqueue a task in the task queue.",
    "Appends a new task item into the task queue with dependency graph validation.",
    [
      optionalFlag("task", "string", "Task ID."), optionalFlag("task-id", "string", "Alias for task ID."),
      optionalFlag("title", "string", "Task title."), optionalFlag("description", "string", "Task description."),
      optionalFlag("priority", "string", "Task priority (CRITICAL, HIGH, MEDIUM, LOW)."), optionalFlag("gate", "string", "Gate verification command."),
      repeatableFlag("write-scope", "string", "Assigned writable file path."), repeatableFlag("charter-goals", "string", "Charter goal identifiers."),
      repeatableFlag("acceptance-criteria", "string", "Acceptance criteria items."), repeatableFlag("dependencies", "string", "Task dependency IDs."),
      optionalFlag("source-type", "string", "Task source type."), optionalFlag("status", "string", "Initial task status."),
      optionalFlag("assigned-tier", "string", "Assigned execution tier."), optionalFlag("assigned-role", "string", "Assigned agent role."),
      optionalFlag("max-retries", "int", "Maximum retry count."), optionalFlag("queue-path", "string", "Custom task queue file path."),
      optionalFlag("path", "string", "Alias for queue-path."),
    ],
    taskAddCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:add --task task-1 --title "Implement auth" --gate "bun test"'],
  ),
  taskCmd(
    "task:list",
    "List tasks in the task queue.",
    "Queries and lists queue items with filtering and queue statistics.",
    [
      optionalFlag("status", "string", "Filter tasks by status."), optionalFlag("priority", "string", "Filter tasks by priority."),
      optionalFlag("agent-id", "string", "Filter tasks by assigned agent ID."), optionalFlag("search", "string", "Filter tasks by substring in ID or title."),
      optionalFlag("limit", "int", "Maximum number of tasks to return."), optionalFlag("offset", "int", "Pagination offset."),
      optionalFlag("page", "int", "Pagination page number."), optionalFlag("queue-path", "string", "Custom task queue file path."),
      optionalFlag("path", "string", "Alias for queue-path."), optionalFlag("stats", "bool", "Include queue statistics in output."),
    ],
    taskListCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:list --status PENDING"],
  ),
  taskCmd(
    "task:lease",
    "Claim an active lease on a task in the queue.",
    "Claims an exclusive active lease on a task for an agent worker.",
    [
      optionalFlag("task", "string", "Task ID to claim lease on."), optionalFlag("task-id", "string", "Alias of task ID."),
      optionalFlag("agent-id", "string", "Agent ID claiming the lease."), optionalFlag("lease-duration", "int", "Lease duration in seconds."),
      optionalFlag("duration-seconds", "int", "Alias of lease duration."), optionalFlag("queue-path", "string", "Custom task queue file path."),
      optionalFlag("path", "string", "Alias for queue-path."),
    ],
    taskLeaseCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:lease --task task-1 --agent-id worker-1"],
  ),
  taskCmd(
    "task:complete",
    "Mark a task as completed in the queue.",
    "Records task completion, unblocks downstream dependents, and optionally archives the task.",
    [
      optionalFlag("task", "string", "Task ID to complete."), optionalFlag("task-id", "string", "Alias of task ID."),
      optionalFlag("agent-id", "string", "Agent ID completing the task."), optionalFlag("lease-token", "string", "Active lease token."),
      optionalFlag("token", "string", "Alias of lease token."), optionalFlag("proof-summary", "string", "Summary proof of task completion."),
      optionalFlag("test-path", "string", "Test file path demonstrating completion."), optionalFlag("commit-sha", "string", "Commit SHA associated with completion."),
      optionalFlag("auto-archive", "bool", "Automatically archive completed task."), optionalFlag("auto-prune", "bool", "Automatically prune completed task from queue."),
      optionalFlag("completed-tasks-path", "string", "Completed tasks archive file path."), optionalFlag("archive-path", "string", "Alias of completed tasks archive path."),
      optionalFlag("queue-path", "string", "Custom task queue file path."), optionalFlag("path", "string", "Alias for queue-path."),
    ],
    taskCompleteCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:complete --task task-1 --proof-summary "All tests pass"'],
  ),
  taskCmd(
    "task:fail",
    "Mark a task as failed in the queue.",
    "Transitions task to failed or increments retry count if retries remain.",
    [
      optionalFlag("task", "string", "Task ID to fail."), optionalFlag("task-id", "string", "Alias of task ID."),
      optionalFlag("message", "string", "Failure error message."), optionalFlag("error", "string", "Alias of error message."),
      optionalFlag("reason", "string", "Alias of error message."), optionalFlag("agent-id", "string", "Agent ID recording failure."),
      optionalFlag("lease-token", "string", "Active lease token."), optionalFlag("token", "string", "Alias of lease token."),
      optionalFlag("can-retry", "bool", "Allow task retry if retry count permits."), optionalFlag("escalate", "bool", "Escalate task upon reaching max retries."),
      optionalFlag("queue-path", "string", "Custom task queue file path."), optionalFlag("path", "string", "Alias for queue-path."),
    ],
    taskFailCommand,
    DEFAULT_EXIT_CODES,
    ['bun harness.ts task:fail --task task-1 --message "Test failure"'],
  ),
  taskCmd(
    "task:prune",
    "Prune completed tasks from the queue.",
    "Removes completed tasks from the active queue and archives them to completed log.",
    [
      optionalFlag("completed-tasks-path", "string", "Completed tasks archive file path."), optionalFlag("archive-path", "string", "Alias of completed tasks archive path."),
      optionalFlag("auto-archive", "bool", "Archive completed tasks before pruning."), optionalFlag("queue-path", "string", "Custom task queue file path."),
      optionalFlag("path", "string", "Alias for queue-path."),
    ],
    taskPruneCommand,
    DEFAULT_EXIT_CODES,
    ["bun harness.ts task:prune"],
  ),
];
