import {
  mindQueueAddCommand,
  mindQueueCleanCommand,
  mindQueueDrainCommand,
  mindQueueListCommand,
  mindQueueSealCommand,
  todoAddCommand,
  todoCleanCommand,
  todoDrainCommand,
  todoListCommand,
  todoSealCommand,
} from "../commands/todo-ops.ts";
import { DEFAULT_EXIT_CODES, optionalFlag, requiredFlag, type CommandSpec } from "./types.ts";

export {
  mindQueueAddCommand,
  mindQueueCleanCommand,
  mindQueueDrainCommand,
  mindQueueListCommand,
  mindQueueSealCommand,
  todoAddCommand,
  todoCleanCommand,
  todoDrainCommand,
  todoListCommand,
  todoSealCommand,
};

export const TODO_COMMANDS: readonly CommandSpec[] = [
  {
    name: "mind:queue:list",
    aliases: ["todo:list", "feedback:list", "feedback:query", "feedback:status"],
    domain: "mind",
    summary: "List, search, and inspect items in .capsules/mind/queue/feedback-queue.jsonl.",
    description:
      "Queries the persistent file-backed feedback queue, returning priority-ranked items and status statistics.",
    flags: [
      optionalFlag("queue-file", "string", "Custom path to feedback-queue.jsonl."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
      optionalFlag(
        "status",
        "string",
        "Filter by status: PENDING, ADMITTED, PROCESSED, COMPLETED, DECLINED.",
      ),
      optionalFlag(
        "category",
        "string",
        "Filter by category: DOCUMENTATION, AGENT_CONTRACTS, CLI_TOOLING, etc.",
      ),
      optionalFlag(
        "priority",
        "string",
        "Filter by priority: CRITICAL_USER_FEEDBACK, HIGH_ARCHITECTURAL_FEATURE, etc.",
      ),
      optionalFlag("limit", "int", "Maximum number of items to return (default: 20).", 20),
      optionalFlag("all", "bool", "Display all matching items without truncation limit."),
      optionalFlag("format", "string", "Output format: markdown or json."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts mind:queue:list",
      "bun harness.ts todo:list --status PENDING --all",
      "bun harness.ts todo:list --category ARCHITECTURE",
    ],
    handler: todoListCommand,
  },
  {
    name: "mind:queue:add",
    aliases: ["todo:add", "feedback:ingest", "feedback:add"],
    domain: "mind",
    summary: "Ingest a new user feedback or architectural directive into the queue.",
    description:
      "Appends a structured feedback/todo item to .capsules/mind/queue/feedback-queue.jsonl for autonomous Mind intake.",
    flags: [
      requiredFlag("title", "string", "Human-readable summary title."),
      requiredFlag("content", "string", "Detailed feedback or directive content."),
      optionalFlag("id", "string", "Unique feedback item identifier."),
      optionalFlag(
        "priority",
        "string",
        "Priority: CRITICAL_USER_FEEDBACK, HIGH_ARCHITECTURAL_FEATURE, USER_DIRECTIVE, NORMAL, LOW.",
      ),
      optionalFlag(
        "category",
        "string",
        "Category: DOCUMENTATION, AGENT_CONTRACTS, CLI_TOOLING, WATCHDOG, SCALING, ARCHITECTURE, CORE_ENGINE, REPAIR, GENERAL.",
      ),
      optionalFlag("queue-file", "string", "Custom path to feedback-queue.jsonl."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts mind:queue:add --title 'New Feature' --content 'Implement streaming UI' --priority HIGH_ARCHITECTURAL_FEATURE",
      "bun harness.ts todo:add --title 'Fix edge case' --content 'Address empty array handling' --category REPAIR",
    ],
    handler: todoAddCommand,
  },
  {
    name: "mind:queue:drain",
    aliases: ["todo:drain", "feedback:drain", "feedback:pop"],
    domain: "mind",
    summary: "Drain and mark pending items in FIFO order for execution.",
    description:
      "Extracts next available item in FIFO order from feedback-queue.jsonl and transitions its status.",
    flags: [
      optionalFlag(
        "mark-as",
        "string",
        "Status to transition to: PROCESSED, ADMITTED, DECLINED, COMPLETED (default: PROCESSED).",
      ),
      optionalFlag("limit", "int", "Maximum items to drain (default: 1).", 1),
      optionalFlag("category", "string", "Filter category to drain."),
      optionalFlag("priority", "string", "Filter priority to drain."),
      optionalFlag("queue-file", "string", "Custom path to feedback-queue.jsonl."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts mind:queue:drain",
      "bun harness.ts todo:drain --limit 1 --mark-as ADMITTED",
    ],
    handler: todoDrainCommand,
  },
  {
    name: "mind:queue:seal",
    aliases: ["todo:seal"],
    domain: "mind",
    summary: "Seal an item in the queue with resolution proof and verification metadata.",
    description:
      "Records resolution notes and optional empirical proof (commit sha, test paths) for a completed queue item.",
    flags: [
      requiredFlag("id", "string", "Item ID to seal."),
      requiredFlag("resolution", "string", "Resolution note or proof summary."),
      optionalFlag("commit", "string", "Commit SHA associated with the fix."),
      optionalFlag("commit-sha", "string", "Alias for --commit."),
      optionalFlag("test-path", "string", "Path to verification test."),
      optionalFlag("assertions", "string", "Assertion count or summary."),
      optionalFlag("runtime-ms", "int", "Test runtime in milliseconds."),
      optionalFlag("queue-file", "string", "Custom path to feedback-queue.jsonl."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
      optionalFlag(
        "require-commit-sha",
        "bool",
        "Require commit SHA to be present and >= 7 chars.",
      ),
      optionalFlag("require-test-path", "bool", "Require test path to be present."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts mind:queue:seal --id fb-123 --resolution 'Fixed broken parser' --commit a1b2c3d",
      "bun harness.ts todo:seal --id fb-123 --resolution 'Implemented CLI command' --test-path tests/cli.test.ts",
    ],
    handler: todoSealCommand,
  },
  {
    name: "mind:queue:clean",
    aliases: ["todo:clean"],
    domain: "mind",
    summary: "Prune resolved items from the queue into completed archives ledger.",
    description:
      "Archives completed and declined items from feedback-queue.jsonl into completed-tasks.jsonl ledger.",
    flags: [
      optionalFlag("queue-file", "string", "Custom path to feedback-queue.jsonl."),
      optionalFlag("queue-path", "string", "Alias for --queue-file."),
      optionalFlag("archive-file", "string", "Custom path to completed-tasks.jsonl ledger."),
      optionalFlag("completed-file", "string", "Alias for --archive-file."),
      optionalFlag("dry-run", "bool", "Simulate clean without writing changes to files."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts mind:queue:clean", "bun harness.ts todo:clean --dry-run"],
    handler: todoCleanCommand,
  },
];
