import {
  planAddCommand,
  planCompileCommand,
  planEnhanceCommand,
  planInitCommand,
  planReplanCommand,
  planStatusCommand,
} from "../commands/plan.ts";
import { planApplyCommand, planClaimCommand } from "../commands/plan-apply.ts";
import {
  DEFAULT_EXIT_CODES,
  optionalFlag,
  repeatableFlag,
  requiredFlag,
  type CommandSpec,
} from "./types.ts";

export const PLAN_COMMANDS: readonly CommandSpec[] = [
  {
    name: "plan:init",
    aliases: ["init"],
    domain: "plan",
    summary: "Create a run capsule and capture the prompt bytes immutably.",
    description:
      "Initialises <repo>/.capsules/<run-id>, records the verbatim prompt with its sha256, and ensures the capsule is gitignored.",
    flags: [
      optionalFlag("run", "string", "Run id; interchangeable with --run-id."),
      optionalFlag("run-id", "string", "Run id; interchangeable with --run."),
      optionalFlag("repo", "string", "Repository root that owns the capsule.", "."),
      optionalFlag("prompt-file", "string", "File holding the verbatim prompt bytes."),
      optionalFlag("prompt-stdin", "bool", "Read the verbatim prompt bytes from stdin."),
      optionalFlag(
        "capture-mode",
        "string",
        "How the prompt was captured; defaults to the source used.",
      ),
      optionalFlag(
        "source-verified",
        "bool",
        "Assert the prompt source was verified by the caller.",
      ),
      optionalFlag(
        "runtime-source",
        "string",
        "Directory to pin as this run's runtime, verified and copied into runtime/. Defaults to the directory containing the currently running harness.ts.",
      ),
      optionalFlag(
        "no-runtime-pin",
        "bool",
        "Skip pinning a runtime even when one is available by default.",
      ),
    ],
    readsStdin: true,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'printf "%s" "$PROMPT" | bun harness.ts plan:init --repo . --run <run-id> --prompt-stdin',
      "bun harness.ts plan:init --repo . --run-id <run-id> --prompt-file prompt.txt --capture-mode file",
    ],
    handler: planInitCommand,
  },
  {
    name: "plan:enhance",
    aliases: [],
    domain: "plan",
    summary: "Record the agent's reading of the repository as a reviewable plan document.",
    description:
      "Writes planning/enhanced-plan.md and planning/enhanced-plan.json read-only and records their digests in state.planning.enhanced_plan. The agent reads the repository host-side and reports what it found; the harness asks no model anything and invents no entry, so everything recorded carries evidence_class agent_reported. The document is derived: prompt.md stays the requirement source. Needs at least one of --summary, --observation, --todo, --risk or --open-question.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("actor", "string", "Actor recorded on the event."),
      optionalFlag("summary", "string", "The enhanced brief: what this run is actually about."),
      repeatableFlag("observation", "string", "Something the agent found in the repository."),
      repeatableFlag("todo", "string", "One organised to-do item, in the order to do it."),
      repeatableFlag("risk", "string", "A risk the agent identified."),
      repeatableFlag("open-question", "string", "A question the agent could not answer."),
      repeatableFlag("source", "string", "A file the agent actually read."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts plan:enhance --run .capsules/<run-id> --actor planner --summary "Wire the drawer to the graph store" --todo "Add the state machine tab" --todo "Delete the legacy asset writes" --risk "Fixture dataset predates the new schema" --source src/graph/store.ts',
    ],
    handler: planEnhanceCommand,
  },
  {
    name: "plan:add",
    aliases: [],
    domain: "plan",
    summary: "Register a task declaration in the planning buffer.",
    description:
      "Appends one task to the uncompiled planning buffer. Rejected once the plan has been compiled.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("id", "string", "Task id, unique within the buffer."),
      requiredFlag("label", "string", "Human label for the task."),
      requiredFlag("scope", "string", "Comma-separated write scope paths."),
      requiredFlag("gate", "string", "Verification command that proves the task."),
      requiredFlag("actor", "string", "Actor recorded on the event."),
      optionalFlag("deps", "string", "Comma-separated ids this task depends on."),
      optionalFlag("goal", "string", "Goal statement for the task."),
      optionalFlag("criteria", "string", "Semicolon-separated acceptance criteria."),
      optionalFlag("priority", "int", "Scheduling priority; higher runs earlier."),
      optionalFlag("effort", "int", "Relative effort estimate."),
      optionalFlag(
        "requirement-lines",
        "string",
        'Prompt lines this task implements, e.g. "3-5,8". Without it the compiler glues the task to a prompt line by position and warns.',
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts plan:add --run .capsules/<run-id> --id task-1 --label "Database schema" --scope "src/db" --gate "bun test tests/db.test.ts" --actor coordinator',
      'bun harness.ts plan:add --run .capsules/<run-id> --id task-2 --label "CLI wiring" --scope "src/cli" --gate "bun test tests/unit/cli" --actor coordinator --requirement-lines "3-5"',
    ],
    handler: planAddCommand,
  },
  {
    name: "plan:compile",
    aliases: [],
    domain: "plan",
    summary: "Compile the planning buffer into requirements, the DAG, and revision 1.",
    description:
      "Checks scope independence, derives requirements from the prompt lines, builds the graph, and commits graph revision 1. The mandatory run-completion gate is whatever --completion-gate declares; the compiler has no default for it and refuses to invent one.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("actor", "string", "Actor recorded on the event."),
      requiredFlag(
        "completion-gate",
        "string",
        'Command the whole run is finally held to, e.g. "bun test tests/unit". Recorded as the mandatory run-scope gate; there is no default.',
      ),
      optionalFlag("strict-parallel", "bool", "Treat serialization advisories as failures."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts plan:compile --run .capsules/<run-id> --actor planner --completion-gate "bun test tests/unit"',
    ],
    handler: planCompileCommand,
  },
  {
    name: "plan:replan",
    aliases: [],
    domain: "plan",
    summary: "Partition findings into a repair wave and raise the graph revision.",
    description:
      "Ingests validator or critic findings, partitions them into disjoint write scopes, and compiles the next revision.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("actor", "string", "Actor recorded on the event."),
      optionalFlag("findings", "string", "Inline JSON findings payload."),
      optionalFlag("findings-file", "string", "Path to a JSON findings payload."),
      optionalFlag("round", "int", "Explicit repair round number."),
      optionalFlag(
        "gate",
        "string",
        "Revalidation gate for generated repair tasks. Omit only when the findings declare revalidation_gate or the planned task covering the scope has a gate to inherit; there is no default.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      'bun harness.ts plan:replan --run .capsules/<run-id> --actor coordinator --gate "bun run typecheck"',
    ],
    handler: planReplanCommand,
  },
  {
    name: "plan:claim",
    aliases: [],
    domain: "plan",
    summary: "Issue a planner's role packet: the sole way a planner agent gets its contract.",
    description:
      "The planner has no task and no lease, so it cannot task:claim. This is its equivalent: it hands back the planner role contract, the immutable prompt, and the write scope (planning/requirements.json, planning/graph.json) the planner is bound to fill in before plan:apply.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("agent", "string", "The planner's own agent id, already agent:register'd."),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts plan:claim --run .capsules/<run-id> --agent planner-1"],
    handler: planClaimCommand,
  },
  {
    name: "plan:apply",
    aliases: [],
    domain: "plan",
    summary: "Validate and commit the requirements and graph the planner wrote to planning/.",
    description:
      "Reads requirements.json and graph.json (defaulting to planning/ inside the run), validates them against the immutable prompt, and commits them as the next graph revision. --expected-revision rejects the apply outright if the graph has moved since the planner's packet was issued, instead of silently overwriting a newer plan.",
    flags: [
      requiredFlag("run", "string", "Capsule run root."),
      requiredFlag("actor", "string", "Actor recorded on the event."),
      optionalFlag(
        "requirements",
        "string",
        "Path to the requirements document. Defaults to <run>/planning/requirements.json.",
      ),
      optionalFlag(
        "graph",
        "string",
        "Path to the graph document. Defaults to <run>/planning/graph.json.",
      ),
      optionalFlag(
        "expected-revision",
        "int",
        "The graph revision this apply must be built against; the apply is refused if the run has moved past it.",
      ),
    ],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: [
      "bun harness.ts plan:apply --run .capsules/<run-id> --actor planner-1 --expected-revision 0",
    ],
    handler: planApplyCommand,
  },
  {
    name: "plan:status",
    aliases: [],
    domain: "plan",
    summary: "Show the planning buffer or the compiled plan summary.",
    description: "Reports every buffered task with its scope, gate and dependencies.",
    flags: [requiredFlag("run", "string", "Capsule run root.")],
    readsStdin: false,
    takesRemainder: false,
    exitCodes: DEFAULT_EXIT_CODES,
    examples: ["bun harness.ts plan:status --run .capsules/<run-id>"],
    handler: planStatusCommand,
  },
];
