export {
  DynamicToolRegistry,
  getGlobalToolRegistry,
  resetGlobalToolRegistry,
  type ToolCatalogExport,
  type ToolContext,
  type ToolDefinition,
  type ToolExecutionResult,
  type ToolFilter,
  type ToolHandler,
  type ToolMetadata,
  type ToolParameter,
  type ToolParameterType,
  type ToolRegistryStats,
} from "./registry.ts";

export {
  discoverToolsFromDirectory,
  discoverToolsFromManifest,
  parseToolSpec,
  scanAndRegisterTools,
  validateToolSpec,
  type DiscoveredTool,
  type DiscoveryOptions,
  type DiscoveryReport,
} from "./discovery.ts";

export {
  DEFAULT_DARWIN_NOTIFICATION_SOUND,
  DEFAULT_LINUX_NOTIFICATION_SOUND,
  buildPhaseNotificationPayload,
  defaultNotificationSpawner,
  displaySystemNotification,
  escapeAppleScriptString,
  escapePowerShellString,
  formatElapsedDuration,
  isTestEnvironment,
  notifyPhaseCompletion,
  playCompletionChime,
  sendSystemNotification,
  triggerAudioChime,
  triggerPhaseNotification,
  triggerTestNotification,
  type NotificationPayload,
  type NotificationPlatform,
  type NotificationProcessSpawner,
  type NotificationProcessSpawnResult,
  type NotificationResult,
  type PhaseCompletionNotificationOptions,
} from "./notifications.ts";
