export const VENDOR_NAMES: readonly string[] = [
  "ansible",
  "anthropic",
  "antigravity",
  "babel",
  "bard",
  "bitbucket",
  "cargo",
  "cassandra",
  "chatgpt",
  "chromium",
  "claude",
  "cloudflare",
  "codex",
  "cohere",
  "copilot",
  "cypress",
  "deepseek",
  "deno",
  "docker",
  "dotnet",
  "elasticsearch",
  "emacs",
  "esbuild",
  "eslint",
  "firefox",
  "gecko",
  "gemini",
  "github",
  "gitlab",
  "gofmt",
  "golang",
  "gpt",
  "gradle",
  "grok",
  "grunt",
  "gulp",
  "haiku",
  "heroku",
  "homebrew",
  "intellij",
  "jasmine",
  "jest",
  "jetbrains",
  "junit",
  "karma",
  "kubernetes",
  "langchain",
  "llama",
  "maven",
  "mercurial",
  "mistral",
  "mocha",
  "mongodb",
  "mysql",
  "neovim",
  "netlify",
  "nightwatch",
  "npm",
  "nuget",
  "ollama",
  "openai",
  "opus",
  "oxfmt",
  "oxlint",
  "perplexity",
  "playwright",
  "pnpm",
  "poetry",
  "postgres",
  "postgresql",
  "prettier",
  "prisma",
  "puppeteer",
  "pylint",
  "pytest",
  "python",
  "qwen",
  "railway",
  "redis",
  "ripgrep",
  "rspec",
  "rubocop",
  "safari",
  "selenium",
  "snowpack",
  "sonnet",
  "sqlite",
  "stylelint",
  "subversion",
  "terraform",
  "testcafe",
  "tslint",
  "turbopack",
  "typescript",
  "vercel",
  "vite",
  "vitest",
  "vscode",
  "webdriver",
  "webpack",
  "windsurf",
  "xcode",
  "yarn",
];

export interface HostDispatchTerm {
  readonly host: string;
  readonly terms: readonly string[];
}

export const HOST_DISPATCH_TERMS: readonly HostDispatchTerm[] = [
  { host: "antigravity", terms: ["invoke_subagent", "define_subagent", "ReusedSubagentId"] },
  { host: "codex", terms: ["spawn_agent", "multi_agent_v1", "fork_turns", "fork_context"] },
];

export interface HostNameAlias {
  readonly host: string;
  readonly aliases: readonly string[];
}

export const HOST_NAME_ALIASES: readonly HostNameAlias[] = [
  { host: "antigravity", aliases: ["antigravity"] },
  { host: "codex", aliases: ["codex"] },
];
