export type {
  AggregatedDefect,
  DefectCategory,
  DefectContext,
  DefectCuration,
  DefectEntry,
  DefectHypothesis,
  DefectKeyOptions,
  DefectOccurrence,
  DefectRecordInput,
  DefectRemediationAction,
  DefectResolutionProof,
  DefectSeverity,
  DefectStatus,
  EmpiricalFailureProof,
  HistoricalOccurrence,
  LiveDeduplicationOptions,
  ParseDefectLogOptions,
} from "./types.ts";
export {
  categorizeDefect,
  deserializeDefectRecord,
  isRecord,
  normalizeText,
  parseAndDeduplicateDefectJsonl,
  parseDefectLog,
  serializeAggregatedDefectLog,
  serializeDefectLog,
} from "./serializer.ts";
export {
  aggregateDefectEntries,
  computeDefectDedupKey,
  computeDefectDiscriminator,
  createDefectContentHash,
  createFnv1aHash,
  createSha256Hash,
  deduplicateDefectLog,
  mergeDuplicateDefect,
  mergeStatus,
  normalizeObservationSignature,
  parseIsoMs,
  pickHigherSeverity,
  SEVERITY_WEIGHTS,
  toAggregatedDefect,
  withinDeduplicationWindow,
} from "./dedup.ts";
export {
  resolveDefect,
  resolveDefectRecord,
  validateResolutionProof,
  verifyResolutionProofEmpirical,
} from "./resolution.ts";
