/**
 * Unified Mind Subsystem Registry and Cognitive Discovery Engine.
 * Exports cognitive task discovery, self-evolution loops, strategic purpose codification,
 * CLI commands, and core mind domain facilities.
 */

import {
  boolFlag,
  integerFlag,
  listFlag,
  textFlag,
  type CommandContext,
  type Flags,
} from "../../cli/options.ts";
import {
  DEFAULT_EXIT_CODES,
  optionalFlag,
  requiredFlag,
  type CommandSpec,
  type FlagSpec,
} from "../../cli/registry/types.ts";
import { enforceLineLimit } from "../../cli/formatters/line-limiter.ts";
import {
  discoverTasks,
  formatTaskDiscoveryBrief,
  proposeCandidateEvolutions,
  resolveDiscoveryCharterPath,
  scanCodeQuality,
  scanCognitiveGaps,
  scanDormantCriteria,
  scanTestCoverage,
  synthesizeTaskFromDiscovery,
  type CandidateEvolutionProposal,
  type CodeQualityFinding,
  type CodeQualityIssueType,
  type CodeQualityScanOptions,
  type CodeQualityScanResult,
  type CognitiveGapFinding,
  type CognitiveGapScanOptions,
  type CognitiveGapScanResult,
  type CognitiveIssueType,
  type DiscoveredTaskPlan,
  type DiscoveryCategory,
  type DiscoveryItem,
  type DiscoverySeverity,
  type DormantCriteriaFinding,
  type DormantCriteriaScanOptions,
  type DormantCriteriaScanResult,
  type TaskDiscoveryOptions,
  type TaskDiscoveryResult,
  type TestCoverageFinding,
  type TestCoverageIssueType,
  type TestCoverageScanOptions,
  type TestCoverageScanResult,
} from "../tasks/discovery/index.ts";
import {
  CLOSING_FORBIDDEN_IDLE_MIND,
  DEFAULT_EVOLUTION_BASE_INTERVAL_MS,
  DEFAULT_EVOLUTION_MAX_INTERVAL_MS,
  enforcePerpetualNonStoppingCadence,
  evaluatePerpetualCadence,
  executeSelfEvolutionStep,
  formatSelfEvolutionBrief,
  getEvolutionStats,
  NON_STOPPING_RULE,
  PERPETUAL_NON_STOPPING_CADENCE,
  readEvolutionHistory,
  recordEvolutionCycle,
  resolveEvolutionHistoryPath,
  runSelfEvolutionCycle,
  type CadencePhase,
  type EvolutionHistoryStats,
  type EvolutionLedgerEntry,
  type PerpetualCadenceEvaluation,
  type SelfEvolutionCadenceState,
  type SelfEvolutionCycleOptions,
  type SelfEvolutionCycleResult,
  type SelfEvolutionMode,
} from "../lifecycle/evolution/index.ts";
import {
  MIND_STRATEGIC_ALTITUDE,
  MIND_HARD_ZEROS,
  MIND_PROACTIVE_BANDWIDTH_ACTIVITIES,
  diagnoseMacroDag,
  groomBacklog,
  evaluateStrategicCandidateAdmission,
  planProactiveRoadmap,
  executeProactiveMindCognition,
  formatStrategicCognitionBrief,
  verifyMindRoleStrategicInvariants,
  type MacroDagTaskNode,
  type MacroDagBottleneck,
  type MacroDagDiagnosticResult,
  type BacklogGroomingItem,
  type BacklogGroomingResult,
  type StrategicCandidate,
  type StrategicCandidateEvaluation,
  type StrategicCandidateAdmissionResult,
  type ProactiveWaveTask,
  type ProactiveWavePlan,
  type ProactiveRoadmapPlan,
  type ProactiveMindCognitionResult,
  type MacroDagDiagnosticOptions,
  type BacklogGroomingOptions,
  type StrategicCandidateAdmissionOptions,
  type ProactiveRoadmapPlanningOptions,
  type ProactiveMindCognitionOptions,
  type MindProactiveBandwidthActivity,
} from "../lifecycle/purpose/index.ts";
import {
  DEFAULT_COGNITIVE_MEMORY_FILE,
  resolveCanonicalCognitiveMemoryPath,
  resolveCognitiveMemoryPath,
  readCognitiveMemory,
  writeCognitiveMemory,
  updateCognitiveMemory,
  synthesizeAutonomousTasks,
  processAutonomousDualIntake,
  runAutonomousDualIntakeCycle,
  synthesizeSmartTasksFromFeedbackQueue,
  synthesizeSmartTasksFromSelfEvolution,
  expandExternalPromptToPlan,
  expandExternalPromptToWavePlan,
  planEnhance,
  planEnhanceToWavePlan,
  planWaveExecution,
  compileSmartTasksToWavePlan,
  partitionIntoDisjointWaves,
  partitionGroupedFeedbacksStrictly,
  partitionCandidatesStrictly,
  validateAntiBatchingRule,
  validateAntiBatchingIsolation,
  assertAntiBatchingRule,
  calculateScopeCollisions,
  detectScopeCollisions,
  detectScopeOverlap,
  type ActiveHypothesis,
  type RoadmapItem,
  type MacroMetrics,
  type CognitiveMemoryState,
  type SmartTaskPlan,
  type SmartTaskSourceType,
  type AntiBatchingValidationReport,
  type SmartTaskSynthesisResult,
  type WaveGroup,
  type SmartWavePlanResult,
  type ScopeCollision,
  type AutonomousDualIntakeResult,
} from "../tasks/smart/index.ts";
import {
  DEFAULT_TASK_QUEUE_FILE,
  resolveCanonicalTaskQueuePath,
  resolveTaskQueuePath,
  readTaskQueue,
  writeTaskQueue,
  clearTaskQueue,
  enqueueTask,
  enqueueTasksBatch,
  admitTask,
  claimTaskLease,
  popNextEligibleTask,
  popNextEligibleTaskWithCleanup,
  renewTaskLease,
  releaseTaskLease,
  startTaskValidation,
  completeTask,
  escalateTask,
  failTask,
  reclaimExpiredLeases,
  getQueueStats,
  listTaskQueue,
  pruneCompletedTasks,
  validateTaskQueueDag,
  type TaskQueueItem,
  type NewTaskQueueInput,
  type TaskQueueStats,
  type TaskQueueStatus,
  type TaskPriority,
  type TaskSourceType,
  type TaskLease,
} from "../tasks/queue/index.ts";

import { mindTaskDiscoveryCommand } from "./discovery-command.ts";
import { mindSelfEvolveCommand, mindStrategicCognitionCommand } from "./evolution-command.ts";
import {
  MIND_TASK_DISCOVERY_COMMAND_SPEC,
  MIND_SELF_EVOLVE_COMMAND_SPEC,
} from "./cognition-command.ts";

export const MIND_STRATEGIC_COGNITION_COMMAND_SPEC: CommandSpec = {
  name: "mind:strategic-cognition",
  aliases: ["mind-strategic-cognition", "mind:proactive-plan"],
  domain: "mind",
  summary: "Execute proactive strategic cognition during subordinate execution windows.",
  description:
    "Channels Mind cognitive bandwidth at 30,000 feet into macro DAG diagnostics (P = W/S), backlog grooming, candidate admission, and proactive roadmap planning for future fleets.",
  flags: [
    optionalFlag(
      "window-hours",
      "int",
      "Subordinate execution window duration in hours (default: 2).",
      2,
    ),
    optionalFlag("fleet-id", "string", "Target fleet identifier for proactive roadmap."),
    optionalFlag("json", "bool", "Output structured JSON."),
  ],
  readsStdin: false,
  takesRemainder: false,
  exitCodes: DEFAULT_EXIT_CODES,
  examples: [
    "bun harness.ts mind:strategic-cognition",
    "bun harness.ts mind:strategic-cognition --window-hours 3 --fleet-id fleet-gen-5",
  ],
  handler: mindStrategicCognitionCommand,
};
