export {
  commandId,
  canonicalCommandFingerprint,
  embeddedCommandIssues,
  repositoryObservationIssues,
  sameCommandJson,
  CREATE_ATTEMPT_DISPOSITION,
  createCommandSigningCapability,
  createAttemptDispositionCapabilityWithKey,
  type CommandSigningCapability,
  commandLayers,
  effectiveCommandArgv,
  type CommandLayers,
  aggregateFinalAttemptIssues,
  transientFailure,
  applyAttemptRecord,
  applyAttempt,
  replaceFinalAttempt,
  updateRetryExhaustion,
  MAX_COMMAND_ATTEMPT_BYTES,
  MAX_COMMAND_RECORD_BYTES,
  MAX_COMMAND_INTENT_BYTES,
  assertCommandAttemptSize,
  assertCommandRecordSize,
  assertCommandIntentSize,
  boundedEvidenceError,
  runAttempt,
  cleanupAfterAttemptFailure,
  raceWithTimeout,
  settleBounded,
  settleTrackerBeforeOutcome,
  activityMetadata,
  writeSuccessfulAttemptEvidence,
  finalizeSuccessfulAttempt,
  finalizeGateAttempt,
  isBroadScopeTest,
  runCommand,
  prepareCommand,
  executePreparedCommand,
  acquireMutexLock,
  setExecutionLockDependenciesForTesting,
  createInternalCommandRunner,
  type InternalCommandRunner,
  commandExecutionSnapshot,
  type CommandRuntimeCapability,
  type ExecutionLockDependencies,
} from "./models/index.ts";

export { captureGateEnvironment } from "./signing/gate-environment.ts";
export { captureGatePathBindings } from "./signing/gate-path-bindings.ts";
export {
  MAX_SUBAGENT_CAPACITY,
  SubagentPool,
  acquireSubagentSlot,
  releaseSubagentSlot,
  getSubagentPoolStats,
  resetSubagentPool,
  type SubagentSlotOptions,
  type SubagentSlotReceipt,
  type SubagentPoolStats,
} from "./subagent-pool.ts";
