/**
 * @file index.ts
 * Extended Edge-Case Heuristics Engine
 */

export {
  analyzeGlassSurfaces,
  calculateApcaLightnessContrast,
  calculateEffectiveCumulativeBlur,
  compositeRgba,
  extractBlurRadiusPx,
  getRequiredApcaLc,
  parseColorToRgba,
  simulateSubstrateContrasts,
  sRgbToLuminanceY,
  type GlassStackAnalysisResult,
  type GlassSubstrateEvaluation,
  type GlassSurfaceDefect,
  type GlassSurfaceLayer,
  type GlassTextElement,
  type ParsedRgba,
} from "./glass-surfaces/index.ts";

export {
  validateModalFocusTrap,
  type BodyScrollState,
  type FocusCycleReport,
  type FocusSequenceTransition,
  type FocusableNode,
  type ModalFocusTrapDefect,
  type ModalFocusTrapInput,
  type ModalFocusTrapResult,
  type OutsideSiblingNode,
} from "./modal-focus-traps/index.ts";

export {
  CANONICAL_FRACTIONAL_DPR_SCALES,
  evaluateAntiAliasingEdgeContrast,
  evaluateEdgeContrast,
  evaluateElementSubpixelPhysics,
  evaluateSubpixelDrift,
  getPhysicalRoundingError,
  normalizeBorderWidths,
  parseTransformTranslations,
  snapToDevicePixels,
  validateElementSubpixelPhysics,
  validateSubpixelBorders,
  type AntiAliasingEdgeContrastResult,
  type DprEvaluation,
  type EdgeContrastEvaluation,
  type SubpixelBorderAnalysisResult,
  type SubpixelBorderDefect,
  type SubpixelBorderWidths,
  type SubpixelDriftEvaluation,
  type SubpixelDriftResult,
  type SubpixelElementBounds,
  type SubpixelElementInput,
  type SubpixelValidationOptions,
} from "./subpixel-borders/index.ts";

export {
  CANONICAL_VIEWPORTS,
  CANONICAL_VIEWPORT_SPECS,
  MANDATORY_PILLARS,
  MINIMUM_SCREENSHOT_BYTES,
  SUPERFICIAL_BOILERPLATE_PATTERNS,
  auditCriterionSemanticDepth,
  auditManifestSemanticDepth,
  auditSingleViewportManifest,
  computePhysicalViewportMetrics,
  normalizePillar,
  synthesizeDprAwareCompanionManifest,
  verifyMultiViewportManifests,
  type CanonicalViewport,
  type CanonicalViewportSpec,
  type DprAwareManifestSynthesisOptions,
  type MandatoryPillar,
  type ManifestSemanticDepthResult,
  type MultiViewportBundleInput,
  type MultiViewportDefect,
  type MultiViewportManifestEntry,
  type MultiViewportVerificationResult,
  type PhysicalViewportMetrics,
  type ScreenshotArtifact,
  type SemanticDepthAuditResult,
  type SemanticDepthDefect,
  type SingleViewportAudit,
  type SingleViewportAuditOptions,
} from "./multi-viewport-manifest/index.ts";

export {
  FORENSICS_SEVERITIES,
  PERMITTED_VALIDATOR_TOOLS,
  POLL_TOOLS,
  PROPOSAL_TEMPLATES,
  READ_TOOLS,
  REMEDIATION_DIRECTIVES,
  ROOT_CAUSE_CATEGORIES,
  WRITE_TOOLS,
  analyzeBehavioralForensics,
  calculateForensicsEfficiencyScore,
  createIncident,
  evaluateRoleBoundaryHeuristics,
  evaluateSerializationHeuristics,
  evaluateSystemLeaksHeuristics,
  evaluateTokenBurnHeuristics,
  formatBehavioralForensicsReport,
  generateIncidentId,
  generateProposalId,
  isJsonObject,
  isPollTool,
  isReadTool,
  isSupervisorRole,
  isValidatorRole,
  isWriteTool,
  renderBehavioralForensicsAsciiTable,
  serializeProposalsToFeedbackJson,
  synthesizePlanInjectionProposals,
  type AgentRecord,
  type BehavioralForensicsAnalysisResult,
  type BehavioralForensicsContext,
  type BehavioralForensicsIncident,
  type BehavioralForensicsMetrics,
  type BehavioralForensicsSummary,
  type EfficiencyScoringInput,
  type ExtractedToolCall,
  type FeedbackCategory,
  type FeedbackPriority,
  type ForensicsCategory,
  type ForensicsSeverity,
  type PlanInjectionProposal,
  type ProposalMetadata,
  type QuantitativeDeduction,
  type QuantitativeEfficiencyReport,
  type RoleBoundaryAnalysisResult,
  type RootCauseCategory,
  type RunForensicsAnalysisInput,
  type SerializationAnalysisResult,
  type SystemLeaksAnalysisResult,
  type TaskRecord,
  type TokenBurnAnalysisResult,
} from "./behavioral-forensics/index.ts";
