export { proposeBatch } from "./propose-batch.ts";
export { schedulingMetrics } from "./metrics.ts";
export {
  resourceConflict,
  scopeConflict,
  hasActiveOwnership,
  ownershipConflicts,
} from "./conflicts.ts";
export { computeTopology, type TopologyConfig, type TopologyInputs } from "./topology.ts";
export { recordTopology } from "./persist-topology.ts";
export { readySet, type ReadyEntry, type ReadySetSelection } from "./ready-set.ts";
export {
  computeWorkSpanMetrics,
  computeResourceDisjointness,
  partitionOrchestratorDomains,
  calculateValidatorAllocations,
  calculateCriticConcurrency,
  synthesizeDynamicTopology,
  type WorkSpanMetrics,
  type ResourceDisjointnessMetrics,
  type OrchestratorPartition,
  type CrossOrchestratorBarrier,
  type ValidatorDemand,
  type DynamicTopologyWave,
  type DynamicTopologyOptions,
  type DynamicTopologySynthesis,
} from "./dynamic-topology.ts";
export {
  evaluateHierarchicalDecision,
  assertHierarchicalCompliance,
  HIERARCHICAL_TIERS,
  type AgentRoleHierarchy,
  type HierarchicalAction,
  type HierarchicalDecisionContext,
  type HierarchicalDecisionResult,
} from "./decision-tree.ts";
export {
  SchedulerEngine,
  auditDoctorGate,
  auditGraphHealth,
  auditSupervisory5PointHealth,
  auditSupervisoryWatchdog,
  assertDoctorGatePassed,
  determineTopLeader,
  dispatchSupervisoryHealthProbe,
  formatSupervisoryHealthMarkdown,
  probeAgentRegistryAccuracy,
  probeCircularDependencies,
  probeDoctorErrorResolution,
  probeGateCoverageViolations,
  probeOrphanedTasks,
  probePlanEnhancementNeeds,
  probeRoleBoundaryAdherence,
  probeScopeCollisionHazards,
  probeStaleLeases,
  probeWorkSpanParallelizationHealth,
  recoverStaleTasks,
  type AgentRegistryAccuracyAudit,
  type BlockedTaskInfo,
  type CircularDependenciesProbeResult,
  type DoctorErrorResolutionAudit,
  type GateCoverageProbeResult,
  type GraphHealthAuditReport,
  type GraphHealthIssue,
  type OrphanedTasksProbeResult,
  type PlanEnhancementAudit,
  type RoleBoundaryAdherenceAudit,
  type ScheduledTaskDispatch,
  type ScheduledWaveResult,
  type SchedulerEngineOptions,
  type ScopeCollisionHazard,
  type ScopeCollisionProbeResult,
  type StaleLeaseInfo,
  type StaleLeasesProbeResult,
  type Supervisory5PointHealthReport,
  type Supervisory5PointOptions,
  type SupervisoryProbeDispatchResult,
  type SupervisoryTopLeader,
  type SupervisoryWatchdogAuditReport,
  type TaskRecoveryRecord,
  type TaskRecoveryResult,
  type WorkSpanHealthAudit,
} from "./core-engine.ts";
export {
  executePulseTick,
  runPulseLoop,
  type PulseLoopOptions,
  type PulseLoopResult,
  type PulseTickOptions,
  type PulseTickResult,
} from "./pulse.ts";
export {
  deriveCounterfactualRequirement,
  normalizeCriticFinding,
  selectImplementerValidatorPair,
  detectDeterministicRepeat,
  compileRepairDag,
  routeCriticFeedback,
  evaluateRepairCycleConvergence,
  type ReviewerRole,
  type CriticFindingInput,
  type CriticFindingDetail,
  type ImplementerValidatorBinding,
  type PairAssignmentStrategy,
  type ClosedLoopRepairPayload,
  type CompiledRepairDagNode,
  type CompiledRepairDag,
  type RouteCriticFeedbackOptions,
  type RouteCriticFeedbackResult,
} from "./critic-feedback.ts";
export {
  classifyTaskDomain,
  derivePrimaryValidatorDomain,
  dispatchMultiDomainValidators,
  evaluateMultiDomainBatch,
  isMultiDomainDispatchEligible,
  MULTI_DOMAIN_PARALLELISM_THRESHOLD,
  proposeMultiDomainWave,
  resolveParallelismFactor,
  type MultiDomainBatchOptions,
  type MultiDomainBatchResult,
  type MultiDomainBlockedTaskInfo,
  type MultiDomainTaskDispatch,
  type MultiDomainValidatorDispatchOptions,
  type MultiDomainValidatorDispatchResult,
  type MultiDomainWaveOptions,
  type MultiDomainWaveResult,
  type TaskDomain,
} from "./multi-domain-dispatch.ts";

