import { HarnessError } from "../core/errors/harness-error.ts";

/**
 * Task specification input for topology synthesis.
 */
export interface SynthesizedTaskSpec {
  readonly id: string;
  readonly label?: string | undefined;
  readonly writeScope: readonly string[];
  readonly dependencies?: readonly string[] | undefined;
  readonly priority?: number | undefined;
  readonly effort?: number | undefined;
  readonly requirementIds?: readonly string[] | undefined;
  readonly requiredSkills?: readonly string[] | undefined;
  readonly cognitiveFlavor?: string | undefined;
}

/**
 * Explicit dependency or serialization rule between tasks.
 */
export interface DependencyRule {
  readonly from: string;
  readonly to: string;
  readonly reason?: string | undefined;
}

/**
 * Specification to synthesize a complete DAG topology.
 */
export interface TopologySynthesisSpec {
  readonly objective?: string | undefined;
  readonly prompt?: string | undefined;
  readonly tasks: readonly SynthesizedTaskSpec[];
  readonly maxParallel?: number | undefined;
  readonly dependencyRules?: readonly DependencyRule[] | undefined;
  readonly enforceScopeIsolation?: boolean | undefined;
  readonly targetSkillQuality?: number | undefined;
  readonly enforceZeroAny?: boolean | undefined;
  readonly enforceZeroSuppressions?: boolean | undefined;
  readonly codeSnippets?:
    | readonly { readonly path: string; readonly content: string }[]
    | undefined;
}

/**
 * Represents a concurrent wave plan containing tasks that execute simultaneously.
 */
export interface TopologyWavePlan {
  readonly wave: number;
  readonly taskIds: readonly string[];
  readonly capacity: number;
  readonly writeScopes: readonly string[];
  readonly dependenciesSatisfied: readonly string[];
  readonly estimatedEffort: number;
}

/**
 * Placement decision record for an individual task.
 */
export interface TopologyDecisionRecord {
  readonly taskId: string;
  readonly wave: number;
  readonly parallelWith: readonly string[];
  readonly serializedAfter: readonly string[];
  readonly reason: "dependency" | "write_scope_conflict" | "priority_capacity";
  readonly rationale: string;
}

/**
 * Fully synthesized and validated DAG topology.
 */
export interface SynthesizedTopology {
  readonly schema: "orchestrator.synthesized_topology";
  readonly version: number;
  readonly revision: number;
  readonly tasks: readonly SynthesizedTaskSpec[];
  readonly waves: readonly TopologyWavePlan[];
  readonly decisions: readonly TopologyDecisionRecord[];
  readonly maxParallel: number;
  readonly criticalPath: readonly string[];
  readonly criticalDepth: number;
  readonly totalEffort: number;
  readonly qualityScore: number;
  readonly isAcyclic: boolean;
  readonly metadata?: Record<string, unknown> | undefined;
}

/**
 * Decomposition of a parent task into finer-grained sub-tasks.
 */
export interface TaskDecomposition {
  readonly parentTaskId: string;
  readonly subTasks: readonly SynthesizedTaskSpec[];
}

/**
 * Skill requirement adjustment for a task.
 */
export interface SkillRequirementAdjustment {
  readonly taskId: string;
  readonly requiredSkill: string;
  readonly minimumQuality: number;
}

/**
 * Reordering rule enforcing serialization between tasks.
 */
export interface SerializationRule {
  readonly taskId: string;
  readonly serializeAfter: readonly string[];
  readonly reason: string;
}

/**
 * Critic feedback adjustment payload for adapting existing topologies.
 */
export interface CriticFeedbackAdjustment {
  readonly feedbackId: string;
  readonly roundNumber: number;
  readonly criticDecision: "approve" | "request_changes" | "rejected" | "escalated";
  readonly feedbackSummary: string;
  readonly blockingFindingIds?: readonly string[] | undefined;
  readonly remediatedTaskIds?: readonly string[] | undefined;
  readonly newTasks?: readonly SynthesizedTaskSpec[] | undefined;
  readonly reorderRules?: readonly SerializationRule[] | undefined;
  readonly skillEnhancements?: readonly SkillRequirementAdjustment[] | undefined;
  readonly splitTasks?: readonly TaskDecomposition[] | undefined;
}

/**
 * Result of acyclicity validation over a graph.
 */
export interface AcyclicityValidationResult {
  readonly isAcyclic: boolean;
  readonly topologicalOrder: readonly string[];
  readonly cycle?: readonly string[] | undefined;
  readonly issues: readonly string[];
}

/**
 * Report generated by dominating skill quality assertion.
 */
export interface DominatingSkillQualityReport {
  readonly passed: boolean;
  readonly score: number;
  readonly metrics: {
    readonly anyTypeCount: number;
    readonly suppressionCount: number;
    readonly typeCoverageScore: number;
    readonly errorHandlingScore: number;
    readonly modularityScore: number;
  };
  readonly issues: readonly string[];
}

/**
 * Normalizes a file path for scope comparison.
 */
export function normalizeScope(path: string): string {
  let normalized = path.trim().replace(/\\/g, "/");
  if (normalized.startsWith("./")) {
    normalized = normalized.slice(2);
  }
  while (normalized.endsWith("/") && normalized.length > 1) {
    normalized = normalized.slice(0, -1);
  }
  return normalized;
}

/**
 * Determines whether two write scopes overlap (exact match or ancestor-descendant relationship).
 */
export function doScopesOverlap(scopeA: string, scopeB: string): boolean {
  const normA = normalizeScope(scopeA);
  const normB = normalizeScope(scopeB);

  if (normA === normB) {
    return true;
  }

  const slashA = normA.endsWith("/") ? normA : `${normA}/`;
  const slashB = normB.endsWith("/") ? normB : `${normB}/`;

  return normB.startsWith(slashA) || normA.startsWith(slashB);
}

/**
 * Determines whether two sets of write scopes share any overlapping file path or directory.
 */
export function checkScopeListOverlap(
  scopesA: readonly string[],
  scopesB: readonly string[],
): { overlap: boolean; pathA?: string | undefined; pathB?: string | undefined } {
  for (const a of scopesA) {
    for (const b of scopesB) {
      if (doScopesOverlap(a, b)) {
        return { overlap: true, pathA: a, pathB: b };
      }
    }
  }
  return { overlap: false };
}

/**
 * Validates acyclicity and computes topological ordering for a set of nodes.
 */
export function validateTopologyAcyclicity(
  tasks: readonly { readonly id: string; readonly dependencies?: readonly string[] | undefined }[],
  options?: { readonly strict?: boolean | undefined },
): AcyclicityValidationResult {
  const strict =
    options !== undefined && typeof options.strict === "boolean" ? options.strict : false;
  const issues: string[] = [];

  const taskIds = new Set<string>();
  for (const t of tasks) {
    const id = t.id.trim();
    if (!id) {
      const msg = "Task ID must be a non-empty string";
      if (strict) throw new HarnessError("INVALID_ARGUMENT", msg);
      issues.push(msg);
      return { isAcyclic: false, topologicalOrder: [], issues };
    }
    if (taskIds.has(id)) {
      const msg = `Duplicate task ID detected: ${id}`;
      if (strict) throw new HarnessError("INVALID_ARGUMENT", msg);
      issues.push(msg);
      return { isAcyclic: false, topologicalOrder: [], issues };
    }
    taskIds.add(id);
  }

  const adjacency = new Map<string, Set<string>>();
  const inDegree = new Map<string, number>();

  for (const id of taskIds) {
    adjacency.set(id, new Set());
    inDegree.set(id, 0);
  }

  for (const t of tasks) {
    const dependentId = t.id.trim();
    const deps = t.dependencies !== undefined ? t.dependencies : [];
    for (const rawPrereq of deps) {
      const prereq = rawPrereq.trim();
      if (!prereq) continue;

      if (!taskIds.has(prereq)) {
        const msg = `Task '${dependentId}' references unknown dependency '${prereq}'`;
        if (strict) throw new HarnessError("INVALID_ARGUMENT", msg);
        issues.push(msg);
        continue;
      }

      if (prereq === dependentId) {
        const msg = `Self-referential dependency: task '${dependentId}' cannot depend on itself`;
        if (strict) throw new HarnessError("INVALID_ARGUMENT", msg);
        issues.push(msg);
        return {
          isAcyclic: false,
          topologicalOrder: [],
          cycle: [dependentId, dependentId],
          issues,
        };
      }

      const currentDeps = adjacency.get(prereq);
      if (currentDeps && !currentDeps.has(dependentId)) {
        currentDeps.add(dependentId);
        const currentDeg = inDegree.get(dependentId);
        inDegree.set(dependentId, (currentDeg !== undefined ? currentDeg : 0) + 1);
      }
    }
  }

  // Kahn's algorithm with deterministic priority queue (alphabetical)
  const ready: string[] = [];
  for (const [id, deg] of inDegree.entries()) {
    if (deg === 0) {
      ready.push(id);
    }
  }
  ready.sort();

  const topologicalOrder: string[] = [];
  while (ready.length > 0) {
    const current = ready.shift()!;
    topologicalOrder.push(current);

    const neighbors = adjacency.get(current);
    if (neighbors) {
      for (const neighbor of neighbors) {
        const currentNeighborDeg = inDegree.get(neighbor);
        const remaining = (currentNeighborDeg !== undefined ? currentNeighborDeg : 1) - 1;
        inDegree.set(neighbor, remaining);
        if (remaining === 0) {
          // Insert in sorted order to maintain determinism
          const pos = ready.findIndex((id) => id > neighbor);
          if (pos < 0) {
            ready.push(neighbor);
          } else {
            ready.splice(pos, 0, neighbor);
          }
        }
      }
    }
  }

  if (topologicalOrder.length !== taskIds.size) {
    const remainingTasks = Array.from(taskIds).filter((id) => !topologicalOrder.includes(id));
    const cycle = findCyclePath(remainingTasks, tasks);
    const cycleDesc = cycle.length > 0 ? cycle.join(" -> ") : remainingTasks.join(", ");
    const msg = `Cycle detected in task dependencies involving: ${cycleDesc}`;

    if (strict) {
      throw new HarnessError("INVALID_ARGUMENT", msg);
    }

    issues.push(msg);
    return {
      isAcyclic: false,
      topologicalOrder: [],
      cycle: cycle.length > 0 ? cycle : remainingTasks,
      issues,
    };
  }

  return {
    isAcyclic: true,
    topologicalOrder,
    issues,
  };
}

/**
 * Helper to trace a specific cycle path for diagnostic reports.
 */
function findCyclePath(
  unresolvedIds: readonly string[],
  tasks: readonly { readonly id: string; readonly dependencies?: readonly string[] | undefined }[],
): string[] {
  const unresolvedSet = new Set(unresolvedIds);
  const taskMap = new Map<string, readonly string[]>();
  for (const t of tasks) {
    if (unresolvedSet.has(t.id)) {
      const taskDeps = t.dependencies !== undefined ? t.dependencies : [];
      taskMap.set(
        t.id,
        taskDeps.filter((d) => unresolvedSet.has(d)),
      );
    }
  }

  const visited = new Set<string>();
  const recStack = new Set<string>();
  const path: string[] = [];

  function dfs(node: string): string[] | null {
    visited.add(node);
    recStack.add(node);
    path.push(node);

    const rawDeps = taskMap.get(node);
    const deps = rawDeps !== undefined ? rawDeps : [];
    for (const dep of deps) {
      if (!visited.has(dep)) {
        const found = dfs(dep);
        if (found) return found;
      } else if (recStack.has(dep)) {
        const cycleStartIdx = path.indexOf(dep);
        return [...path.slice(cycleStartIdx), dep];
      }
    }

    recStack.delete(node);
    path.pop();
    return null;
  }

  for (const start of unresolvedIds) {
    if (!visited.has(start)) {
      const cycle = dfs(start);
      if (cycle) return cycle;
    }
  }

  return [];
}

/**
 * Partitions tasks into sequential waves respecting explicit dependencies,
 * write scope isolation, and max parallel concurrency capacity.
 */
export function partitionTopologyWaves(
  tasks: readonly SynthesizedTaskSpec[],
  maxParallel = 4,
): TopologyWavePlan[] {
  if (tasks.length === 0) {
    return [];
  }

  const effectiveMaxParallel = Math.max(1, maxParallel);

  // Validate acyclicity first
  const acyclicCheck = validateTopologyAcyclicity(tasks, { strict: true });
  const sortedIds = acyclicCheck.topologicalOrder;

  const taskById = new Map<string, SynthesizedTaskSpec>();
  for (const t of tasks) {
    taskById.set(t.id, t);
  }

  // Track assigned wave for each task
  const assignedWave = new Map<string, number>();
  const waveTaskMap = new Map<number, string[]>();

  // Map to store write scopes per wave
  const waveScopeMap = new Map<number, string[]>();

  for (const taskId of sortedIds) {
    const task = taskById.get(taskId)!;
    const rawDeps = task.dependencies !== undefined ? task.dependencies : [];
    const taskDeps = rawDeps.map((d) => d.trim()).filter(Boolean);

    // Calculate earliest wave based on prerequisite task waves
    let earliestWave = 1;
    for (const depId of taskDeps) {
      const depWave = assignedWave.get(depId);
      if (depWave !== undefined && depWave >= earliestWave) {
        earliestWave = depWave + 1;
      }
    }

    let targetWave = earliestWave;
    for (;;) {
      const existingWaveTasks = waveTaskMap.get(targetWave);
      const tasksInWave = existingWaveTasks !== undefined ? existingWaveTasks : [];
      const existingWaveScopes = waveScopeMap.get(targetWave);
      const scopesInWave = existingWaveScopes !== undefined ? existingWaveScopes : [];

      // Check capacity limit
      const hasCapacity = tasksInWave.length < effectiveMaxParallel;

      // Check write scope collisions with tasks already in this wave
      const scopeOverlap = checkScopeListOverlap(task.writeScope, scopesInWave);

      if (hasCapacity && !scopeOverlap.overlap) {
        // Suitable wave found
        assignedWave.set(taskId, targetWave);

        if (!waveTaskMap.has(targetWave)) {
          waveTaskMap.set(targetWave, []);
          waveScopeMap.set(targetWave, []);
        }

        waveTaskMap.get(targetWave)!.push(taskId);
        waveScopeMap.get(targetWave)!.push(...task.writeScope);
        break;
      }

      targetWave += 1;
    }
  }

  // Construct TopologyWavePlan objects
  const totalWaves = Math.max(...Array.from(waveTaskMap.keys()), 0);
  const wavePlans: TopologyWavePlan[] = [];

  const satisfiedDepsSet = new Set<string>();

  for (let w = 1; w <= totalWaves; w++) {
    const existingWaveTasks = waveTaskMap.get(w);
    const waveTasks = existingWaveTasks !== undefined ? existingWaveTasks : [];
    if (waveTasks.length === 0) continue;

    const waveScopes = Array.from(
      new Set(
        waveTasks.flatMap((id) => {
          const t = taskById.get(id);
          return t !== undefined && t.writeScope !== undefined ? t.writeScope : [];
        }),
      ),
    ).sort();

    const estimatedEffort = waveTasks.reduce((sum, id) => {
      const t = taskById.get(id);
      const eff = t !== undefined ? t.effort : undefined;
      return sum + (typeof eff === "number" && eff > 0 ? eff : 1);
    }, 0);

    wavePlans.push({
      wave: w,
      taskIds: waveTasks,
      capacity: effectiveMaxParallel,
      writeScopes: waveScopes,
      dependenciesSatisfied: Array.from(satisfiedDepsSet).sort(),
      estimatedEffort,
    });

    for (const id of waveTasks) {
      satisfiedDepsSet.add(id);
    }
  }

  return wavePlans;
}

/**
 * Asserts Tier 3 Dominating Skill Quality rules (zero `any` types, zero suppressions,
 * strict error handling, and modular structure).
 */
export function assertDominatingSkillQuality(options: {
  readonly skills?: readonly string[] | undefined;
  readonly codeSnippets?:
    | readonly { readonly path: string; readonly content: string }[]
    | undefined;
  readonly qualityThreshold?: number | undefined;
  readonly strict?: boolean | undefined;
}): DominatingSkillQualityReport {
  const threshold = typeof options.qualityThreshold === "number" ? options.qualityThreshold : 0.8;
  const strict =
    options.strict !== undefined && typeof options.strict === "boolean" ? options.strict : false;
  const snippets = options.codeSnippets !== undefined ? options.codeSnippets : [];
  const issues: string[] = [];

  let anyTypeCount = 0;
  let suppressionCount = 0;
  let totalLines = 0;
  let typedConstructCount = 0;
  let structuredErrorCount = 0;
  let genericThrowCount = 0;

  // Search patterns for detecting forbidden `any` usages
  const anyRegexes = [
    /:\s*any\b/g,
    /as\s+any\b/g,
    /<\s*any\s*>/g,
    /\bArray<\s*any\s*>/g,
    /\bPromise<\s*any\s*>/g,
    /\bRecord<\s*string\s*,\s*any\s*>/g,
    /\bRecord<\s*any\s*,/g,
    /\bany\[\]/g,
  ];

  // Search patterns for detecting forbidden compiler / linter suppression comments
  const suppressionRegexes = [
    /@ts-ignore/g,
    /@ts-expect-error/g,
    /@ts-nocheck/g,
    /eslint-disable/g,
    /biome-ignore/g,
    /\/\*\s*istanbul\s+ignore/g,
    /\/\*\s*c8\s+ignore/g,
  ];

  for (const snippet of snippets) {
    const lines = snippet.content.split("\n");
    totalLines += lines.length;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]!;
      const lineNum = i + 1;

      // Count all any occurrences in this line
      for (const rx of anyRegexes) {
        const matches = line.match(rx);
        if (matches && matches.length > 0) {
          anyTypeCount += matches.length;
          issues.push(`Forbidden 'any' type in ${snippet.path}:${lineNum} - "${line.trim()}"`);
        }
      }

      // Count all suppression occurrences in this line
      for (const rx of suppressionRegexes) {
        const matches = line.match(rx);
        if (matches && matches.length > 0) {
          suppressionCount += matches.length;
          issues.push(
            `Forbidden suppression comment in ${snippet.path}:${lineNum} - "${line.trim()}"`,
          );
        }
      }

      // Check structured errors
      if (/new\s+HarnessError\b/.test(line) || /throw\s+new\s+HarnessError\b/.test(line)) {
        structuredErrorCount += 1;
      } else if (/throw\s+["'`]/.test(line) || /throw\s+new\s+Error\b/.test(line)) {
        genericThrowCount += 1;
        issues.push(
          `Unstructured error thrown in ${snippet.path}:${lineNum} - use HarnessError instead`,
        );
      }

      // Count typed constructs
      if (
        /interface\s+\w+|type\s+\w+\s*=|function\s+\w+\s*\(|:\s*(string|number|boolean|readonly)/.test(
          line,
        )
      ) {
        typedConstructCount += 1;
      }
    }
  }

  // Calculate sub-scores
  const typeCoverageScore = anyTypeCount === 0 ? 1.0 : Math.max(0, 1.0 - anyTypeCount * 0.25);
  const suppressionScore =
    suppressionCount === 0 ? 1.0 : Math.max(0, 1.0 - suppressionCount * 0.35);
  const errorHandlingScore =
    genericThrowCount === 0
      ? 1.0
      : structuredErrorCount / (structuredErrorCount + genericThrowCount);
  const modularityScore = 1.0;

  // Composite quality score
  let score: number;
  if (anyTypeCount === 0 && suppressionCount === 0 && genericThrowCount === 0) {
    score = 1.0;
  } else {
    score =
      typeCoverageScore * 0.4 +
      suppressionScore * 0.3 +
      errorHandlingScore * 0.2 +
      modularityScore * 0.1;
    score = Math.max(0, Math.min(1, Math.round(score * 100) / 100));
  }

  const passed = anyTypeCount === 0 && suppressionCount === 0 && score >= threshold;

  if (!passed && strict) {
    throw new HarnessError(
      "INTEGRITY",
      `Dominating skill quality assertion failed (score: ${score}, threshold: ${threshold}): ${issues.join("; ")}`,
      issues,
    );
  }

  return {
    passed,
    score,
    metrics: {
      anyTypeCount,
      suppressionCount,
      typeCoverageScore,
      errorHandlingScore,
      modularityScore,
    },
    issues,
  };
}

/**
 * Computes the critical path and depth of a DAG topology.
 */
function computeCriticalPath(
  tasks: readonly SynthesizedTaskSpec[],
  order: readonly string[],
): { criticalPath: string[]; criticalDepth: number } {
  if (tasks.length === 0) {
    return { criticalPath: [], criticalDepth: 0 };
  }

  const taskMap = new Map<string, SynthesizedTaskSpec>();
  for (const t of tasks) {
    taskMap.set(t.id, t);
  }

  const longestPathTo = new Map<string, { path: string[]; depth: number }>();

  for (const id of order) {
    const task = taskMap.get(id);
    const rawDeps = task !== undefined && task.dependencies !== undefined ? task.dependencies : [];
    const deps = rawDeps.map((d) => d.trim()).filter(Boolean);

    let maxPrereqDepth = 0;
    let bestPrereqPath: string[] = [];

    for (const dep of deps) {
      const prereqInfo = longestPathTo.get(dep);
      if (prereqInfo && prereqInfo.depth > maxPrereqDepth) {
        maxPrereqDepth = prereqInfo.depth;
        bestPrereqPath = prereqInfo.path;
      }
    }

    const currentDepth = maxPrereqDepth + 1;
    const currentPath = [...bestPrereqPath, id];
    longestPathTo.set(id, { path: currentPath, depth: currentDepth });
  }

  let criticalDepth = 0;
  let criticalPath: string[] = [];

  for (const info of longestPathTo.values()) {
    if (info.depth > criticalDepth) {
      criticalDepth = info.depth;
      criticalPath = info.path;
    }
  }

  return { criticalPath, criticalDepth };
}

/**
 * Synthesizes a full DAG topology from task specifications and constraints.
 */
export function synthesizeDAGTopology(spec: TopologySynthesisSpec): SynthesizedTopology {
  if (!spec.tasks || spec.tasks.length === 0) {
    throw new HarnessError(
      "INVALID_ARGUMENT",
      "TopologySynthesisSpec must contain at least one task",
    );
  }

  const taskMap = new Map<string, SynthesizedTaskSpec>();
  for (const t of spec.tasks) {
    const id = t.id.trim();
    if (!id) {
      throw new HarnessError("INVALID_ARGUMENT", "Task ID must be non-empty");
    }
    if (taskMap.has(id)) {
      throw new HarnessError("INVALID_ARGUMENT", `Duplicate task ID: ${id}`);
    }
    const rawDeps = t.dependencies !== undefined ? t.dependencies : [];
    taskMap.set(id, {
      ...t,
      id,
      writeScope: t.writeScope.map(normalizeScope),
      dependencies: rawDeps.map((d) => d.trim()).filter(Boolean),
    });
  }

  // Incorporate explicit dependency rules
  if (spec.dependencyRules) {
    for (const rule of spec.dependencyRules) {
      const fromId = rule.from.trim();
      const toId = rule.to.trim();

      if (!taskMap.has(fromId)) {
        throw new HarnessError(
          "INVALID_ARGUMENT",
          `Dependency rule references unknown task '${fromId}'`,
        );
      }
      if (!taskMap.has(toId)) {
        throw new HarnessError(
          "INVALID_ARGUMENT",
          `Dependency rule references unknown task '${toId}'`,
        );
      }

      const targetTask = taskMap.get(toId)!;
      const targetDeps = targetTask.dependencies !== undefined ? targetTask.dependencies : [];
      const currentDeps = new Set(targetDeps);
      currentDeps.add(fromId);

      taskMap.set(toId, {
        ...targetTask,
        dependencies: Array.from(currentDeps),
      });
    }
  }

  const resolvedTasks = Array.from(taskMap.values());

  // Validate graph acyclicity
  const acyclicity = validateTopologyAcyclicity(resolvedTasks, { strict: true });

  // Partition into waves
  const maxParallel =
    typeof spec.maxParallel === "number" && spec.maxParallel > 0 ? spec.maxParallel : 4;
  const waves = partitionTopologyWaves(resolvedTasks, maxParallel);

  // Compute critical path & depth
  const { criticalPath, criticalDepth } = computeCriticalPath(
    resolvedTasks,
    acyclicity.topologicalOrder,
  );

  // Total effort
  const totalEffort = resolvedTasks.reduce((sum, t) => {
    const effort = typeof t.effort === "number" && t.effort > 0 ? t.effort : 1;
    return sum + effort;
  }, 0);

  // Quality check if snippets or strictness flags provided
  const qualityReport = assertDominatingSkillQuality({
    codeSnippets: spec.codeSnippets,
    strict: spec.enforceZeroAny === true || spec.enforceZeroSuppressions === true,
    qualityThreshold: spec.targetSkillQuality,
  });

  // Build decision records
  const taskWaveMap = new Map<string, number>();
  for (const w of waves) {
    for (const tid of w.taskIds) {
      taskWaveMap.set(tid, w.wave);
    }
  }

  const decisions: TopologyDecisionRecord[] = [];
  for (const t of resolvedTasks) {
    const assignedWave = taskWaveMap.get(t.id);
    const wave = assignedWave !== undefined ? assignedWave : 1;
    const wavePlan = waves.find((w) => w.wave === wave);
    const waveTaskIds = wavePlan !== undefined ? wavePlan.taskIds : [];
    const parallelWith = waveTaskIds.filter((id) => id !== t.id);

    const deps = t.dependencies !== undefined ? t.dependencies : [];
    let reason: TopologyDecisionRecord["reason"] = "priority_capacity";
    let rationale = `Placed in wave ${wave} with ${parallelWith.length} concurrent task(s)`;

    if (deps.length > 0) {
      reason = "dependency";
      rationale = `Serialized after prerequisites [${deps.join(", ")}]`;
    } else if (wave > 1) {
      // Check if earlier wave had overlapping write scopes
      let hadScopeConflict = false;
      let conflictingTaskId = "";
      for (let prevWave = 1; prevWave < wave; prevWave++) {
        const prevWavePlan = waves.find((w) => w.wave === prevWave);
        const prevTaskIds = prevWavePlan !== undefined ? prevWavePlan.taskIds : [];
        for (const prevId of prevTaskIds) {
          const prevTask = taskMap.get(prevId);
          if (prevTask && checkScopeListOverlap(t.writeScope, prevTask.writeScope).overlap) {
            hadScopeConflict = true;
            conflictingTaskId = prevId;
            break;
          }
        }
        if (hadScopeConflict) break;
      }

      if (hadScopeConflict) {
        reason = "write_scope_conflict";
        rationale = `Serialized into wave ${wave} due to write scope overlap with [${conflictingTaskId}]`;
      }
    }

    decisions.push({
      taskId: t.id,
      wave,
      parallelWith,
      serializedAfter: deps,
      reason,
      rationale,
    });
  }

  return {
    schema: "orchestrator.synthesized_topology",
    version: 1,
    revision: 1,
    tasks: resolvedTasks,
    waves,
    decisions,
    maxParallel,
    criticalPath,
    criticalDepth,
    totalEffort,
    qualityScore: qualityReport.score,
    isAcyclic: true,
    metadata: {
      objective: spec.objective,
      prompt: spec.prompt,
    },
  };
}

/**
 * Adapts an existing synthesized topology based on recursive critic feedback adjustments.
 */
export function adaptTopologyWithCriticFeedback(
  currentTopology: SynthesizedTopology,
  feedback: CriticFeedbackAdjustment,
): SynthesizedTopology {
  if (feedback.criticDecision === "escalated") {
    throw new HarnessError(
      "INVALID_STATE",
      `Critic escalated feedback [${feedback.feedbackId}]: ${feedback.feedbackSummary}`,
    );
  }

  if (feedback.criticDecision === "approve") {
    // Return existing topology with incremented revision and approval metadata
    return {
      ...currentTopology,
      revision: currentTopology.revision + 1,
      metadata: {
        ...currentTopology.metadata,
        lastCriticDecision: "approve",
        lastFeedbackId: feedback.feedbackId,
        approvedRound: feedback.roundNumber,
      },
    };
  }

  // Handle task splits
  let updatedTasks: SynthesizedTaskSpec[] = [...currentTopology.tasks];

  if (feedback.splitTasks && feedback.splitTasks.length > 0) {
    for (const split of feedback.splitTasks) {
      const parentIdx = updatedTasks.findIndex((t) => t.id === split.parentTaskId);
      if (parentIdx >= 0) {
        const parentTask = updatedTasks[parentIdx]!;
        // Replace parent task with decomposed subtasks
        const subTasksWithDeps = split.subTasks.map((st) => {
          const stDeps = st.dependencies !== undefined ? st.dependencies : [];
          const parentDeps = parentTask.dependencies !== undefined ? parentTask.dependencies : [];
          return {
            ...st,
            dependencies: [...stDeps, ...parentDeps],
          };
        });

        updatedTasks.splice(parentIdx, 1, ...subTasksWithDeps);

        // Update downstream tasks that depended on parentTask to depend on subtasks
        const subTaskIds = split.subTasks.map((st) => st.id);
        updatedTasks = updatedTasks.map((t) => {
          const tDeps = t.dependencies !== undefined ? t.dependencies : [];
          if (tDeps.includes(split.parentTaskId)) {
            const newDeps = t.dependencies!.filter((d) => d !== split.parentTaskId);
            newDeps.push(...subTaskIds);
            return { ...t, dependencies: Array.from(new Set(newDeps)) };
          }
          return t;
        });
      }
    }
  }

  // Handle new remediation tasks
  if (feedback.newTasks && feedback.newTasks.length > 0) {
    const existingIds = new Set(updatedTasks.map((t) => t.id));
    for (const nt of feedback.newTasks) {
      if (!existingIds.has(nt.id)) {
        updatedTasks.push(nt);
        existingIds.add(nt.id);
      }
    }
  }

  // Handle reorder / serialization rules
  const extraRules: DependencyRule[] = [];
  if (feedback.reorderRules && feedback.reorderRules.length > 0) {
    for (const rule of feedback.reorderRules) {
      for (const afterId of rule.serializeAfter) {
        extraRules.push({
          from: afterId,
          to: rule.taskId,
          reason: rule.reason,
        });
      }
    }
  }

  // Handle skill enhancements
  if (feedback.skillEnhancements && feedback.skillEnhancements.length > 0) {
    const skillMap = new Map(feedback.skillEnhancements.map((se) => [se.taskId, se]));

    updatedTasks = updatedTasks.map((t) => {
      const enhancement = skillMap.get(t.id);
      if (enhancement) {
        const tSkills = t.requiredSkills !== undefined ? t.requiredSkills : [];
        const currentSkills = new Set(tSkills);
        currentSkills.add(enhancement.requiredSkill);
        return {
          ...t,
          requiredSkills: Array.from(currentSkills),
        };
      }
      return t;
    });
  }

  // Re-synthesize DAG topology with adapted tasks and extra rules
  const metaObj =
    currentTopology.metadata !== undefined ? currentTopology.metadata.objective : undefined;
  const objective = typeof metaObj === "string" ? metaObj : "Adapted Topology";
  const metaPrompt =
    currentTopology.metadata !== undefined ? currentTopology.metadata.prompt : undefined;
  const prompt = typeof metaPrompt === "string" ? metaPrompt : "";

  const newSpec: TopologySynthesisSpec = {
    objective,
    prompt,
    tasks: updatedTasks,
    maxParallel: currentTopology.maxParallel,
    dependencyRules: extraRules,
  };

  const adapted = synthesizeDAGTopology(newSpec);

  return {
    ...adapted,
    version: currentTopology.version,
    revision: currentTopology.revision + 1,
    metadata: {
      ...currentTopology.metadata,
      lastCriticDecision: feedback.criticDecision,
      lastFeedbackId: feedback.feedbackId,
      feedbackRound: feedback.roundNumber,
      feedbackSummary: feedback.feedbackSummary,
    },
  };
}
