export {
  flagPositions,
  nearestFlagNames,
  parseArguments,
  splitCommandLine,
  suggestCommand,
  suggestFlag,
} from "./arguments.ts";
export type { FlagSuggestion, ParsedArguments } from "./arguments.ts";
export { assertFlags, boolFlag, intFlag, integerFlag, listFlag, textFlag } from "./options.ts";
export { formatCommandHelp, helpRequest, renderHelp } from "./help.ts";
export type { HelpRequest } from "./help.ts";
export { executeCommand } from "./execute.ts";
export type {
  CommandContext,
  CommandFlagSpec,
  CommandHandler,
  CommandSpec,
  ExitCodeSpec,
  FlagShape,
  FlagShapes,
  FlagSpec,
  FlagType,
  FlagValue,
  FlagValues,
  Flags,
} from "./registry/index.ts";
export {
  CHAT_COMMANDS,
  CliError,
  DEFAULT_EXIT_CODES,
  ackSpec,
  allCommands,
  briefSpec,
  commandInvocations,
  daemonSpec,
  doctorSpec,
  findCommand,
  flagShapes,
  initSpec,
  inspectSpec,
  inviteSpec,
  joinSpec,
  mineSpec,
  offSpec,
  onSpec,
  optionalFlag,
  readSpec,
  repeatableFlag,
  requiredFlag,
  roomsSpec,
  saySpec,
  taskSpec,
  topicSpec,
  watchSpec,
} from "./registry/index.ts";
export {
  CommandExecutionError,
  ackCommand,
  briefCommand,
  chatBriefCommand,
  daemonCommand,
  doctorCommand,
  initCommand,
  inspectCommand,
  inviteCommand,
  joinCommand,
  mineCommand,
  offCommand,
  onCommand,
  readCommand,
  roomsCommand,
  sayCommand,
  taskCommand,
  topicCommand,
  watchCommand,
} from "./commands/index.ts";
