export type {
  MilestoneLockStatus,
  UnlockRecord,
  ImmutabilityManifest,
  SealMilestoneInput,
  EmpiricalRegressionProof,
  OpticalRegressionUnlockToken,
  ManifestIntegrityResult,
  LockSystemIntegrityReport,
  ScopeMutationRequest,
} from "./locks/index.ts";

export {
  ROUND_SCOPES,
  DEFAULT_UNLOCK_TOKEN_EXPIRATION_MS,
  MIN_ROOT_CAUSE_ANALYSIS_LENGTH,
  canonicalJsonStringify,
  computeSha256,
  computeManifestSignature,
  requestOpticalRegressionUnlock,
  verifyRegressionProof,
  resealMilestone,
  verifyManifestIntegrity,
  verifyAllMilestoneLocks,
  assertIntegrity,
  MilestoneLockEngine,
  getDefaultMilestoneLockEngine,
  setDefaultMilestoneLockEngine,
  resetDefaultMilestoneLockEngine,
} from "./locks/index.ts";

export type {
  SocraticRoundNumber,
  SocraticRoundId,
  SocraticRoundDefinition,
  CognitiveChallengeSeverity,
  CognitiveChallengeStatus,
  DefenseRecord,
  CognitiveChallenge,
  CreateChallengeInput,
  DefenseSubmission,
  DefenseEvaluationResult,
  CollateralDefect,
  InterRoundAuditResult,
  CompetingForce,
  CandidateResolution,
  ParetoArbitrationInput,
  ParetoArbitrationDecision,
  RoundGateEvaluation,
  RoundAdvanceResult,
  SocraticSessionSummary,
  DialecticSessionOptions,
} from "./dialectic/index.ts";

export {
  MANDATORY_CHALLENGE_QUOTA_R1_R4,
  MAX_CONVERGENCE_CYCLES_PER_GATE,
  MIN_SUBSTANTIVE_DEFENSE_LENGTH,
  SOCRATIC_ROUNDS,
  SOCRATIC_ROUND_MAP,
  TRIVIAL_DEFENSE_PATTERNS,
  evaluateSubstantiveDefense,
  InterRoundRegressionAuditor,
  ParetoArbitrationEngine,
  raiseChallenge,
  submitDefense,
  escalateToParetoArbitration,
  evaluateRoundReadiness,
  auditInterRoundState,
  advanceRound,
  SocraticDialecticEngine,
  getDefaultSocraticDialecticEngine,
  setDefaultSocraticDialecticEngine,
  resetDefaultSocraticDialecticEngine,
} from "./dialectic/index.ts";
