export {
  completionArtifactRequirements,
  validateCompletionArtifactVerification,
  type CompletionArtifactRequirements,
  executeAutoSyncAndCommit,
  type AutoSyncOptions,
  type AutoSyncResult,
  type GitRunner,
  type GitRunnerResult,
  type SyncRunner,
  type SyncRunnerResult,
  completeRun,
  type CompletionArtifactVerifier,
  completionIssues,
  gateTally,
  mandatoryRunGateCommands,
  type GateTally,
  recordCompletionRemediation,
  recordCompletionReview,
} from "./verification/index.ts";

export {
  beginCompletenessCritic,
  type BeginCriticOptions,
  assertCriticIndependent,
  loadCriticRolePacket,
  resolveCriticToken,
  saveCriticPacket,
  deriveTaskTwoKeyPairing,
  taskTwoKeyValidatorPairingIssues,
  verifyTwoKeyValidatorPairing,
  type TwoKeyValidatorPairing,
  type ValidatorReceipt,
  generateStructuredFindingsFromCritic,
  isDeterministicFindingRepeat,
  routeCriticReviewFindings,
  trackTaskRepairBudget,
  type RouteCriticFindingsOptions,
  type RouteCriticFindingsResult,
  type TaskRepairBudgetStatus,
  type TaskRepairSummary,
} from "./critic/index.ts";

export {
  parseRawFindings,
  parseRawProofs,
  completionReadinessIssues,
  completionReviewIssues,
  transitionSummaryIssues,
} from "./issues/index.ts";

export {
  completionHistoryIssues,
  completionReviewDigest,
  jsonDigest,
  observeCapsuleIntegrity,
  type CapsuleIntegrityEvidence,
  commandIsSuccessfulGate,
  completionReadinessSnapshot,
  type CompletionReadinessSnapshot,
  currentRepositoryBinding,
  repositoryBindingIsValid,
  sameRepositoryBinding,
  validateRepositoryBinding,
  verifyRepositoryBinding,
  type RepositoryBindingVerifier,
  authoritativeRepositoryCommand,
  parseCompletionAssessment,
} from "./provenance/index.ts";

export type {
  CompletionArtifactPacket,
  CompletionArtifactVerification,
  CompletionCriticAuthorization,
  CompletionEvidenceItem,
  CompletionFinding,
  CompletionFindingResolution,
  CompletionRemediation,
  CompletionRequirementProof,
  CompletionResidualRisk,
  CompletionResult,
  CompletionReview,
} from "./contracts/index.ts";
