export type { VirtualFSSpyState } from "./core/index.ts";

export {
  NOOP_FALSE,
  checkParentExec,
  checkRmPermissions,
  copyDirRecursive,
  fsErr,
  getInode,
  isVirtualPath,
  makeFsStats,
  mockCp,
  mockExists,
  mockLink,
  mockLstat,
  mockMkdir,
  mockOpendir,
  mockReadFile,
  mockReaddir,
  mockRename,
  mockStat,
  mockWriteFile,
  normPath,
  origClose,
  origCopyFile,
  origExists,
  origFstat,
  origLstat,
  origOpendir,
  origRead,
  origReaddir,
  origRealpath,
  origStat,
  remapPrefix,
} from "./core/index.ts";
