export { CHAT_ERROR_CODES, ChatError, ERROR_CODES, isChatError, type ErrorCode } from "./errors.ts";

export {
  canonicalJson,
  canonicalJsonBytes,
  safeJsonParse,
  timingSafeEqualBuffers,
  timingSafeEqualStrings,
} from "./json.ts";

export {
  ID_REGEX,
  isBoolean,
  isEnvelope,
  isEnvelopeBody,
  isEnvelopeKind,
  isEnvelopeSender,
  isHeldLease,
  isInteger,
  isInviteRecord,
  isLockPayload,
  isLogIndex,
  isMemberRecord,
  isNonNegativeInteger,
  isNumber,
  isPositiveInteger,
  isReaderCursor,
  isRecord,
  isRepoBinding,
  isRoomManifest,
  isRoomSettings,
  isRoomVisibility,
  isString,
  isStringArray,
  isUnsignedEnvelope,
  isValidId,
  type Envelope,
  type EnvelopeBody,
  type EnvelopeKind,
  type EnvelopeSender,
  type HeldLease,
  type InviteRecord,
  type LockPayload,
  type LogIndex,
  type MemberRecord,
  type ReaderCursor,
  type RepoBinding,
  type RoomManifest,
  type RoomSettings,
  type RoomVisibility,
  type UnsignedEnvelope,
} from "./guards.ts";

export {
  acquireLock,
  appendAtomic,
  delay,
  isProcessAlive,
  releaseLock,
  safeFsync,
  withLock,
  writeAtomic,
  type AppendAtomicResult,
  type LockOptions,
  type WriteAtomicOptions,
} from "./atomic.ts";

export {
  assertValidIdentity,
  assertValidRoomId,
  chatroomHomeDir,
  daemonHealthPath,
  daemonLockPath,
  daemonOutSpoolPath,
  daemonReclaimPath,
  daemonRespawnPath,
  globalIdentityPath,
  globalPolicyPath,
  keysDir,
  readerCursorPath,
  readerLockPath,
  readerSpoolCursorPath,
  repoBindingPath,
  repoChatroomDir,
  repoPolicyPath,
  resolveActiveConsumerCursorPath,
  roomAppendLockPath,
  roomConsumedInvitePath,
  roomConsumedInvitesDir,
  roomDaemonDir,
  roomDir,
  roomHandshakeDir,
  roomInvitePath,
  roomInvitesDir,
  roomKeyPath,
  roomLocksDir,
  roomLogDir,
  roomLogIndexPath,
  roomLogSegmentPath,
  roomManifestPath,
  roomMemberPath,
  roomMembersDir,
  roomProvisionDir,
  roomProvisionReceiptPath,
  roomQuarantineDir,
  roomQuarantinePath,
  roomReadersDir,
  roomsDir,
  spoolLockPath,
} from "./paths.ts";
