export {
  ContinuousDefectFeedbackLoop,
  executeDomainTask,
  validateResolutionProof,
  verifyResolutionProofEmpirical,
  resolveDefect,
  formulateDefectHypotheses,
  synthesizeRemediationActions,
  synthesizeDeliberationRound,
  createDefectDeliberationRound,
  advanceDeliberationRound,
  DefectDeliberationPipeline,
} from "./loop/index.ts";
export type {
  DomainExecutionStatus,
  DomainExecutionContext,
  DomainExecutionTask,
  DomainTaskResult,
  DomainMetrics,
  DefectFeedbackCycle,
  DefectLoopOptions,
  DefectLoopMetrics,
  QueuedTaskEntry,
  DeliberationSynthesis,
  DefectDeliberationRound,
} from "./loop/index.ts";
