export type {
  DefectSeverity,
  DefectStatus,
  DefectCategory,
  DefectResolutionProof,
  DefectOccurrence,
  DefectRecordInput,
  DefectEntry,
  AggregatedDefect,
  ParseDefectLogOptions,
  LiveDeduplicationOptions,
  DefectKeyOptions,
  DefectHypothesis,
  DefectRemediationAction,
} from "./core/types.ts";

export {
  normalizeObservationSignature,
  createFnv1aHash,
  createSha256Hash,
  createDefectContentHash,
  computeDefectDiscriminator,
  extractDefectKeywords,
  calculateDefectSimilarity,
} from "./core/discriminator.ts";

export {
  isRecord,
  normalizeText,
  categorizeDefect,
  parseDefectLog,
  serializeDefectLog,
} from "./core/sanitizer.ts";

export {
  pickHigherSeverity,
  toAggregatedDefect,
  aggregateDefectEntries,
  withinDeduplicationWindow,
  mergeDefectSets,
  calculateDefectAggregateMetrics,
  clusterDefectsBySimilarity,
} from "./aggregator/index.ts";

export {
  LiveDefectDeduplicator,
  deduplicateDefectLog,
  parseAndDeduplicateDefectJsonl,
  serializeAggregatedDefectLog,
  streamDeduplicateDefects,
  createDefectDedupTransformStream,
  filterDefectStream,
} from "./dedup/index.ts";

export {
  ContinuousDefectFeedbackLoop,
  executeDomainTask,
  validateResolutionProof,
  verifyResolutionProofEmpirical,
  resolveDefect,
  formulateDefectHypotheses,
  synthesizeBoundaryRemediationActions,
  synthesizeRemediationActions,
  synthesizeDeliberationRound,
  createDefectDeliberationRound,
  advanceDeliberationRound,
  DefectDeliberationPipeline,
  formatDeliberationReport,
  generateDefectRegressionTest,
  generateRegressionTestSuite,
  isDefectEligibleForPromotion,
  validateRegressionTest,
  promoteResolvedDefects,
  autoPromoteDefect,
  formulateDefectCandidates,
  auditDefectLog,
  executeDefectAudit,
  formatDefectAuditBrief,
  logBoundaryViolationDefect,
  DEFAULT_DEFECTS_FILE,
  CANONICAL_DEFECTS_FILE,
  DEFAULT_COMPLETED_DEFECTS_FILE,
  CANONICAL_COMPLETED_DEFECTS_FILE,
  requireDistinctLedgerPaths,
  resolveCanonicalDefectLogPath,
  resolveDefectLogPath,
  resolveCanonicalCompletedDefectsPath,
  resolveCompletedDefectsPath,
  readExistingDefectLog,
  readCompletedDefectsLog,
  writeCompletedDefectsLog,
  atomicWriteDefectLog,
  appendDefectLogEntry,
  appendCompletedDefectLogEntry,
  mergeDefectsById,
  formulateBoundaryViolationHypothesis,
} from "./loop/index.ts";

export {
  syncDoctorFindingsToDefects,
  parseDefectsJsonl,
  serializeDefectsJsonl,
  resolveDefectsJsonlPath,
  cleanupVestigialDefectsFile,
  LIFECYCLE_PHASES,
  validatePhaseTransition,
  enforceSequentialLifecycleOrdering,
  VALID_DEFECT_STATE_TRANSITIONS,
  validateDefectStateTransition,
  transitionDefectState,
} from "./sync/index.ts";

export type { DoctorFindingInput } from "./sync/index.ts";

export type {
  DomainExecutionStatus,
  DomainExecutionContext,
  DomainExecutionTask,
  DomainTaskResult,
  DomainMetrics,
  DefectFeedbackCycle,
  DefectLoopOptions,
  DefectLoopMetrics,
  QueuedTaskEntry,
  DeliberationSynthesis,
  DefectDeliberationRound,
  GeneratedRegressionTest,
  DefectPromotionOptions,
  DefectPromotionResult,
  MindCandidateProposal,
  DefectAuditReport,
  LogBoundaryViolationOptions,
} from "./loop/index.ts";

export {
  DEFICIT_CRITICALITY_CLASSES,
  DEFICIT_CRITICALITY_WEIGHTS,
  DIAGNOSTIC_ERROR_KINDS,
  DEFAULT_KNOWN_SUBSYSTEMS,
  inferSubsystemFromPath,
  extractStackFrames,
  computeStackSignature,
  parseRawDiagnostics,
  clusterDiagnosticErrors,
  runEmpiricalBaselineProbes,
  formatDeficitTopologyMatrixMarkdown,
  DiagnosticClusteringEngine,
} from "./diagnostic-clustering.ts";

export type {
  DeficitCriticalityClass,
  DiagnosticErrorKind,
  ParsedDiagnosticError,
  DeficitClusterNode,
  DeficitTopologySummary,
  RecommendedRoadmapAllocation,
  DeficitTopologyMatrix,
  ProbeExecutionOutput,
  ProbeDefinition,
  SingleProbeResult,
  BaselineProbeOptions,
  BaselineProbeResult,
  ClusteringOptions,
  RawDiagnosticEntryInput,
  RawDiagnosticInput,
  DiagnosticEngineConfig,
  ProbeKind,
} from "./diagnostic-clustering.ts";
