export type {
  DefectSeverity,
  DefectStatus,
  DefectCategory,
  DefectResolutionProof,
  DefectOccurrence,
  DefectRecordInput,
  DefectEntry,
  AggregatedDefect,
  ParseDefectLogOptions,
  LiveDeduplicationOptions,
  DefectKeyOptions,
  DefectHypothesis,
  DefectRemediationAction,
} from "./core/types.ts";
