export {
  DynamicRoleRegistry,
  getGlobalRoleRegistry,
  resetGlobalRoleRegistry,
  validateDynamicRoleSpec,
  synthesizeDynamicRole,
  parseDynamicRoleContract,
  synthesizeRoleFromTaskRequirements,
  synthesizeRoleFromDefectRemediation,
  mutateRoleWithFeedback,
  generateDynamicRoleCheatSheet,
  renderDynamicRolesAsciiTable,
  ARCHETYPE_TIER_MAP,
  ARCHETYPE_DEFAULT_COMMANDS,
  ARCHETYPE_DEFAULT_SPAWNS,
  ARCHETYPE_DEFAULT_WRITE_POLICY,
  FORBIDDEN_COMMANDS,
  ROLE_NAME_PATTERN,
  formatDynamicRoleFrontmatter,
  formatDynamicRoleBody,
  formatDynamicRoleMarkdown,
  type DynamicRoleSpec,
  type DynamicRoleContract,
  type DynamicRoleValidationResult,
  type SynthesizeRoleOptions,
  type RoleArchetype,
  type RoleSpecializationDomain,
  type WriteScopePolicy,
  type RoleLineageEntry,
  type TaskRoleSynthesisParams,
  type DynamicRoleSynthesisPlan,
  type DefectRoleSynthesisParams,
  type RoleMutationFeedback,
  type DynamicRoleCatalogExport,
  type DynamicRoleFilter,
} from "./dynamic/index.ts";

export {
  ABSTRACT_PROFILES,
  ABSTRACT_PROFILE_SET,
  ROLE_PROFILE_MAP,
  isAbstractProfile,
  roleToProfile,
  resolveProfile,
  resolveRoleArchetype,
  formatHostDegradation,
  isPerAgentModelSelectionSupported,
  resolveAgentProfile,
  type AbstractProfile,
  type ProfileBinding,
  type ProfileBindings,
  type ResolvedProfile,
  type AgentProfileResolution,
} from "../../roles/index.ts";
