export {
  buildDataReferenceIndex,
  CODE_FILE_PATTERN,
  collectBindings,
  collectDataReferences,
  DEFAULT_MAX_PREFIX_SHARE,
  extractCallArguments,
  extractPathCandidates,
  isDataFile,
  isSelectablePrefix,
  normalizePrefix,
  resolvePathExpression,
  selectTestsForDataFile,
  splitTopLevelArguments,
  TEST_FILE_PATTERN,
  type DataReferenceIndex,
  type DataReferenceOptions,
  type DataReferencePorts,
  type ExpressionScope,
} from "./data-references.ts";
