export {
  ActivityTracker,
  AdaptiveTimerController,
  AutonomicWatchdog,
  HealthAuditor,
  WatchdogEventEmitter,
  defaultProcessLivenessChecker,
  formatCliStatusReport,
  normalizeReactiveTrigger,
  resolveTimestampMs,
  type AdaptiveAdjustmentReason,
  type AdaptiveTimerConfig,
  type AdaptiveTimerState,
  type AgentActivityState,
  type AutonomicWatchdogConfig,
  type HealthAuditorOptions,
  type IntervalAdjustmentResult,
  type LiveCliProof,
  type ProcessHealthStatus,
  type ReactiveEvent,
  type ReactiveWakeupTrigger,
  type SubagentBootGateRecord,
  type SubagentRegistrationOptions,
  type WatchdogEvent,
  type WatchdogEventListener,
  type WatchdogFinding,
  type WatchdogHealthAuditReport,
  type WatchdogTickReport,
} from "./autonomic-watchdog/index.ts";
