export {
  BootGateEnforcer,
  applyDoctorExecution,
  applyWhoamiExecution,
  assertBootGatesPassed,
  auditBootGatesFromState,
  auditFindings,
  createSpawnedSubagentRecord,
  renderAsciiBootGateTable,
  verifyBootGates,
  type BootGateVerificationResult,
  type LiveCliProof,
  type MandatoryBootGate,
  type ProcessHealthStatus,
  type SubagentBootGateRecord,
  type SubagentRegistrationOptions,
  type WatchdogFinding,
} from "./boot-gate-enforcer/index.ts";
