export {
  DEFAULT_ACTIVITY_BOOST,
  DEFAULT_ADAPTIVE_ACTIVITY_BOOST,
  DEFAULT_ADAPTIVE_BACKOFF_FACTOR,
  DEFAULT_ADAPTIVE_MAX_INTERVAL_MS,
  DEFAULT_ADAPTIVE_MIN_INTERVAL_MS,
  DEFAULT_BACKOFF_FACTOR,
  DEFAULT_HEALTH_AUDIT_INTERVAL_MS,
  DEFAULT_MAX_HEARTBEAT_INTERVAL_MS,
  DEFAULT_MIN_HEARTBEAT_INTERVAL_MS,
  DEFAULT_PROCESS_HEALTH_CHECK_INTERVAL_MS,
  DEFAULT_WATCHDOG_HEARTBEAT_INTERVAL_MS,
  DEFAULT_WATCHDOG_TIMEOUT_MS,
  MANDATORY_BOOT_GATES,
  WATCHDOG_SEVERITIES,
  WATCHDOG_VIOLATION_TYPES,
  type MandatoryBootGate,
  type WatchdogSeverity,
  type WatchdogViolationType,
} from "./constants.ts";

export type {
  AdaptiveAdjustmentReason,
  AdaptiveTimerConfig,
  AdaptiveTimerState,
  AutonomicWatchdogConfig,
  BootGateVerificationResult,
  LiveCliProof,
  ProcessHealthStatus,
  ReactiveEvent,
  ReactiveWakeupTrigger,
  SubagentBootGateRecord,
  SubagentRegistrationOptions,
  WatchdogEvent,
  WatchdogEventListener,
  WatchdogFinding,
  WatchdogHealthAuditReport,
  WatchdogTickReport,
} from "./types.ts";

export {
  BootGateEnforcer,
  applyDoctorExecution,
  applyWhoamiExecution,
  assertBootGatesPassed,
  auditBootGatesFromState,
  auditFindings,
  createSpawnedSubagentRecord,
  renderAsciiBootGateTable,
  verifyBootGates,
} from "./boot-gate-enforcer.ts";

export {
  ActivityTracker,
  AdaptiveTimerController,
  AutonomicWatchdog,
  HealthAuditor,
  WatchdogEventEmitter,
  defaultProcessLivenessChecker,
  formatCliStatusReport,
  normalizeReactiveTrigger,
  resolveTimestampMs,
  type AgentActivityState,
  type HealthAuditorOptions,
  type IntervalAdjustmentResult,
} from "./autonomic-watchdog.ts";

export {
  DEFAULT_DIAGNOSTIC_TAIL_BYTES,
  DEFAULT_GRACE_PERIOD_MS,
  DEFAULT_HEARTBEAT_INTERVAL_MS,
  DEFAULT_STALL_PROGRESS_THRESHOLD_MS,
  DEFAULT_TEST_IDLE_TIMEOUT_MS,
  DEFAULT_TEST_WALL_TIMEOUT_MS,
  ERROR_CLASS_IDLE_TIMEOUT,
  ERROR_CLASS_PROCESS_HANG,
  ERROR_CLASS_STALL_TIMEOUT,
  ERROR_CLASS_WALL_TIMEOUT,
  ERROR_CLASS_ZOMBIE_PROCESS,
  EXIT_STATUS_EXIT_FAILURE,
  EXIT_STATUS_EXIT_SUCCESS,
  EXIT_STATUS_SIGKILL_MANUAL,
  EXIT_STATUS_SIGKILL_TIMEOUT,
  EXIT_STATUS_SIGTERM_TIMEOUT,
  HierarchicalStallProbe,
  ProcessTimeoutWatchdog,
  buildProcessDiagnostics,
  buildRemediationGuidance,
  createHierarchicalStallProbe,
  createProcessTimeoutWatchdog,
  defaultKillProcessTree,
  evaluateProcessLiveness,
  executeSignalEscalation,
  monitorSubprocessLoop,
  trimChunks,
  type BunSubprocess,
  type ChildNodeInfo,
  type ErrorClassification,
  type ExitStatus,
  type HierarchicalRole,
  type HierarchicalStallProbeOptions,
  type ProbeResult,
  type ProcessDiagnostics,
  type ProcessWatchdogOptions,
  type RemediationGuidance,
  type StructuredFailurePayload,
  type SupervisorTier,
  type WatchdogLivenessReport,
  type WatchdogMonitorResult,
  type WatchdogTimeoutKind,
} from "./process-timeout.ts";
