export { dynamicWaveDecoupling } from "./parallel-decoupler.ts";

export {
  DEFAULT_TASK_EFFORT,
  DEFAULT_TASK_PRIORITY,
  DISCRIMINATING_ASSERTION_TYPES,
  FORBIDDEN_SYNTAX_RULES,
  MAX_READINESS_SCORE,
  MIN_READINESS_SCORE,
  PASSING_READINESS_THRESHOLD,
  PRE_ENHANCER_VERSION,
  STANDARD_TASK_INVARIANTS,
  calculateTaskReadinessScore,
  compileAgpCounterfactualProbes,
  compileDiscriminatingAssertions,
  compileDiscriminatingGate,
  compileTaskInvariantChecklist,
  isStringArray,
  parseGateCommand,
  preEnhancePlan,
  preEnhanceTask,
  renderPreEnhancedPlanMarkdown,
  renderTaskPreEnhancementMarkdown,
  synthesizeProactiveTestTemplate,
  validatePreEnhancedPlan,
  validatePreEnhancedTask,
  verifyAstBoundaries,
  verifyScopeDisjointness,
  type AgpCounterfactualProbeTemplate,
  type AssertionCompilationOptions,
  type AssertionSeverity,
  type AstBoundaryFinding,
  type AstBoundaryVerificationResult,
  type DiscriminatingAssertion,
  type DiscriminatingAssertionType,
  type ForbiddenSyntaxRule,
  type PreEnhancePlanOptions,
  type PreEnhanceTaskOptions,
  type PreEnhancedPlanResult,
  type PreEnhancedTaskResult,
  type PreEnhancementTaskInput,
  type ProbeCategory,
  type ScopeDisjointnessResult,
  type StrictTypingRules,
  type TaskInvariantChecklist,
  type TaskInvariantItem,
  type WriteScopeBoundary,
} from "./pre-enhancer.ts";

export { optimizeScopeCollisionDetection } from "./scope-analyzer.ts";
