export type {
  DecideProposalOptions,
  GeneratePlanRevisionOptions,
  InitiativeActionType,
  InitiativeEvaluationInput,
  InitiativeEvaluationResult,
  MindProposal,
  PlanRevisionApplicationResult,
  PlanRevisionProposal,
  PlanRevisionSignal,
  PlanRevisionSignalType,
  PlanRevisionTaskSpec,
  PlanRevisionType,
  ProposalAuthorityDecisionInput,
  ProposalRateLimitCheckResult,
  ProposalStatus,
  RecordProposalOptions,
  TransitionProposalOptions,
} from "./proposal/index.ts";

export {
  DEFAULT_INITIATIVE_CONFIDENCE_THRESHOLD,
  DEFAULT_MAX_OPEN_PROPOSALS,
  DEFAULT_PROPOSAL_MIN_INTERVAL_MS,
  PROPOSAL_WITNESS_AUTONOMOUS_INITIATIVE,
  PROPOSAL_WITNESS_OWNER_DECISION,
  VALID_PROPOSAL_TRANSITIONS,
  admitProposalInState,
  advanceProposalWithInitiative,
  applyPlanRevisionInState,
  assertRoleMayDecideProposal,
  calculateProposalFingerprint,
  calculateRemainingCooldownMs,
  canTransitionProposal,
  checkProposalRateLimits,
  completeProposalInState,
  decideProposal,
  decideProposalInState,
  evaluateInitiativeTriggers,
  findDeclinedProposalConflict,
  formatPlanRevisionBrief,
  formatProposalBrief,
  generatePlanRevisionFromSignals,
  getAllProposals,
  getDeclinedProposals,
  getGrantedProposals,
  getOpenProposals,
  isDuplicateProposal,
  isProposalAdmissible,
  isProposalGranted,
  normalizeText,
  parseNowIso,
  parseNowMs,
  recordProposal,
  recordProposalInState,
  transitionProposalStatusInState,
} from "./proposal/index.ts";
