export type {
  BuildWakeBriefOptions,
  CharterStatus,
  HealthObservationSummary,
  IntegrityStatus,
  LiveRunSummary,
  MindBriefFacts,
  MindLane,
  MindMode,
  RuntimeStatus,
  WakeBriefResult,
} from "./brief/index.ts";

export {
  buildWakeBrief,
  computeFullWakeBrief,
  deriveLane,
  formatDuration,
  formatNumber,
  formatShortSha,
  renderCharterLine,
  renderGapLine,
  renderHealthLine,
  renderIntegrityLine,
  renderRuntimeLine,
} from "./brief/index.ts";

export type {
  AnchorOptions,
  AnchorSymbol,
  AnchorSymbolKind,
  ExactAnchor,
  ExactAnchorBriefing,
  ExactAnchorBriefingOptions,
} from "./builder/index.ts";

export {
  buildExactAnchorBriefing,
  createDropInAnchor,
  deriveRecommendedTestCommands,
  extractFileAnchors,
  extractFileSymbols,
  extractSymbolsFromSource,
  findAnchorByPattern,
  formatExactAnchorBriefingMarkdown,
} from "./builder/index.ts";

export type {
  AdmissionEvaluationResult,
  AdmissionGateVerdict,
  CandidateRecord,
  CommandRecordCandidate,
  GateEvaluationContext,
} from "./gates/index.ts";

export {
  evaluateAdmissionGates,
  evaluateGate1Witnessed,
  evaluateGate2InCharter,
  evaluateGate3Falsifiable,
  evaluateGate4Scoped,
  evaluateGate5Affordable,
  evaluateGate6NotADuplicate,
  executeFalsifier,
  findCommandRecord,
  isPathInRepoRoots,
  outputContainsDefect,
  parseFalsifierArgv,
  readCandidateCommandOutput,
} from "./gates/index.ts";

export type {
  DecideProposalOptions,
  GeneratePlanRevisionOptions,
  InitiativeActionType,
  InitiativeEvaluationInput,
  InitiativeEvaluationResult,
  MindProposal,
  PlanRevisionApplicationResult,
  PlanRevisionProposal,
  PlanRevisionSignal,
  PlanRevisionSignalType,
  PlanRevisionTaskSpec,
  PlanRevisionType,
  ProposalAuthorityDecisionInput,
  ProposalRateLimitCheckResult,
  ProposalStatus,
  RecordProposalOptions,
  TransitionProposalOptions,
} from "./proposal/index.ts";

export {
  DEFAULT_INITIATIVE_CONFIDENCE_THRESHOLD,
  DEFAULT_MAX_OPEN_PROPOSALS,
  DEFAULT_PROPOSAL_MIN_INTERVAL_MS,
  PROPOSAL_WITNESS_AUTONOMOUS_INITIATIVE,
  PROPOSAL_WITNESS_OWNER_DECISION,
  VALID_PROPOSAL_TRANSITIONS,
  admitProposalInState,
  advanceProposalWithInitiative,
  applyPlanRevisionInState,
  assertRoleMayDecideProposal,
  calculateProposalFingerprint,
  calculateRemainingCooldownMs,
  canTransitionProposal,
  checkProposalRateLimits,
  completeProposalInState,
  decideProposal,
  decideProposalInState,
  evaluateInitiativeTriggers,
  findDeclinedProposalConflict,
  formatPlanRevisionBrief,
  formatProposalBrief,
  generatePlanRevisionFromSignals,
  getAllProposals,
  getDeclinedProposals,
  getGrantedProposals,
  getOpenProposals,
  isDuplicateProposal,
  isProposalAdmissible,
  isProposalGranted,
  normalizeText,
  parseNowIso,
  parseNowMs,
  recordProposal,
  recordProposalInState,
  transitionProposalStatusInState,
} from "./proposal/index.ts";
