export type {
  AssemblyStation,
  AssemblyStationStatus,
  BacklogItemStatus,
  BrentConcurrencyPlan,
  BrentPartition,
  ClusterOptions,
  ConcurrencyAuditResult,
  DefectStatus,
  DomainCategory,
  GitStagingInvariantRecord,
  HostSchedulerConfig,
  HostSchedulerId,
  MindAuditorStagnationReport,
  MultiOrchestratorDispatchPlan,
  OrchestratorAllocationMetadata,
  OrchestratorWorktreeAllocation,
  PlanGenerationOptions,
  PreplanningRunResult,
  ProvisionedCluster,
  RawBacklogItem,
  RawDefectItem,
  StagnationAuditResult,
  StragglerAssessment,
  TaskCluster,
  ThematicCluster,
  ThinkingLevel,
} from "./types.ts";

export {
  CANONICAL_DOMAINS,
  classifyDomain,
  clusterBacklogAndDefects,
  computeClusterId,
  filterEligibleBacklogItems,
  filterEligibleDefects,
  generateClusterId,
  generatePlanPath,
  loadBacklogItems,
  loadDefectItems,
} from "./backlog-clusterer.ts";

export {
  DEFAULT_SINGLE_ORCHESTRATOR_CAPACITY,
  assertDisjointClusters,
  partitionDisjointClusters,
  shardClusterByCapacity,
  type ProvisioningOptions,
  dispatchMultiOrchestratorClusters,
  mapClustersToOrchestrators,
  triggerOrchestratorWorktreeProvisioning,
  assertValidBlueprintStructure,
  deriveDisjointTaskScope,
  generateAndWritePlan,
  generatePlanBlueprint,
  generatePlanMarkdown,
  writePlanFile,
} from "./orchestration/index.ts";

export {
  resolveLedgerPath,
  transitionBacklogItemsToPlanned,
  transitionDefectsToPlanned,
  updateBridgeState,
  updateBridgeStateBatch,
} from "./bridge-state.ts";

export {
  type DaemonOptions,
  type PreplannerOptions,
  clusterBacklogTasks,
  extractPlanTasksFromBacklog,
  isPreplanningNeeded,
  provisionBacklogTracks,
  runContinuousPreplanningTick,
  runPreplanningTick,
  startPreplanningDaemon,
} from "./continuous-preplanner.ts";

export type { ClusterAndProvisionOptions } from "../planning/index.ts";
export { clusterTasks, provisionTaskClusters } from "../planning/index.ts";

export type {
  DiffSummary,
  FileChangeStatus,
  GitStashEntry,
  InFlightEngineOptions,
  InFlightSnapshot,
  InFlightSnapshotOptions,
  InFlightSnapshotSummary,
  InFlightWorkInspection,
  LoadSnapshotOptions,
  SaveSnapshotOptions,
  UncommittedFileEntry,
  BacklogOptions,
  IntentCategory,
  IntentDomain,
  IntentExtractionOptions,
  PriorityOneDeliverable,
  RoadmapAction,
  UserIntentRecord,
  UserIntentRoadmapIntegration,
} from "./inflight/index.ts";

export {
  InFlightIngestionEngine,
  createInFlightSnapshot,
  inspectInFlightWork,
  listInFlightSnapshots,
  loadInFlightSnapshot,
  parseDiffSummary,
  parseGitStashes,
  parseGitStatusOutput,
  saveInFlightSnapshot,
  UserIntentExtractionEngine,
  extractUserIntent,
  integrateUserIntentIntoRoadmap,
  structureUserIntentAsBacklogDeliverable,
  toCanonicalDomainCategory,
} from "./inflight/index.ts";
