export {
  AuditorCursorStore,
  MindAuditorEngine,
  SkillAuditorEngine,
  CognitiveChallengePromptGenerator,
  generateCognitiveChallengePrompt,
  generateZeroDeltaChallengePrompt,
  COGNITIVE_CHALLENGE_DIMENSIONS,
  type AuditorCursor,
  type MindAuditLiveResult,
  type SkillAuditLiveResult,
  type StoredAuditorCursors,
  type CognitiveChallengeDimension,
  type CognitiveChallenge,
  type CognitiveChallengeOptions,
  type ZeroDeltaChallengeOptions,
} from "./cognitive/index.ts";

export {
  CANONICAL_SELF_QUESTIONING_QUESTION,
  COGNITIVE_DIMENSIONS,
  COGNITIVE_FLAVOR_IDS,
  COGNITIVE_DIMENSION_SPECS,
  COGNITIVE_FLAVOR_PROFILES,
  evaluateCognitiveState,
  getCognitiveDimensionSpec,
  getCognitiveFlavorProfile,
  formatCognitivePromptSection,
  formatCognitiveEvaluationBrief,
  type CognitiveDimension,
  type CognitiveFlavorId,
  type CognitiveDimensionSpec,
  type CognitiveFlavorProfile,
  type CognitiveFrictionFinding,
  type BreakthroughProposal,
  type CognitiveEvaluationStateInput,
  type CognitiveDimensionScore,
  type CognitiveFlavorEvaluation,
} from "./flavor/index.ts";

export {
  runCounterfactualReAdmissionSuite,
  type CounterfactualOptions,
  type CounterfactualResult,
} from "./counterfactual/index.ts";

export {
  resolveWitnessCommand,
  readCommandOutput,
  verifyDefectWitness,
  type WitnessResolution,
  type DefectWitnessVerification,
} from "./witness/index.ts";

export {
  computePersonaSignature,
  calculatePersonaSimilarity,
  findSimilarPersonas,
  synthesizeNonDuplicatePersona,
  auditSingleRole,
  auditDynamicRoles,
  runAutonomousMindRoleAudit,
  formatRoleAuditMarkdown,
  renderRoleAuditAsciiTable,
  formatNonDuplicatePersonaSummary,
  isMindRole,
  CODE_EDIT_TOOLS,
  GRAPH_MUTATION_COMMANDS,
  VALIDATION_COMMANDS,
  isOrchestratorRole,
  isCoordinatorRole,
  isImplementerRole,
  isValidatorRole,
  isMechanicValidatorRole,
  isCognitiveValidatorRole,
  isFullTestSuiteCommand,
  roleToTier,
  PROHIBITED_COGNITIVE_TOOLS,
  PROHIBITED_COGNITIVE_TOOL_CATEGORIES,
  RoleBoundaryWatchdog,
  createRoleBoundaryWatchdog,
  verifyRoleBoundaryAction,
  auditRoleBoundaryActions,
  validateParentChildSupervision,
  assertParentChildBoundary,
  type PersonaSignature,
  type PersonaSimilarityMetrics,
  type NonDuplicateRoleSynthesisResult,
  type SynthesizeNonDuplicateRoleOptions,
  type RoleAuditOptions,
  type RoleAuditSummary,
  type RoleAuditReport,
  type RoleBoundaryAction,
  type RoleBoundaryViolation,
  type RoleBoundaryAuditResult,
  type RoleBoundaryWatchdogOptions,
  type ParentChildSupervisionResult,
} from "./roles/index.ts";

export {
  analyzeRunForensics,
  isJsonObject,
  ROOT_CAUSE_CATEGORIES,
  FORENSICS_SEVERITIES,
  READ_TOOLS,
  WRITE_TOOLS,
  POLL_TOOLS,
  safeParseJson,
  generateIncidentId,
  generateProposalId,
  isReadTool,
  isWriteTool,
  isPollTool,
  parseEventsFile,
  parseStateFile,
  parseManifestFile,
  extractToolCallsFromTranscripts,
  extractToolCallsFromEvents,
  calculateEfficiencyScore,
  formatForensicsReport,
  renderForensicsAsciiTable,
  synthesizeRemediationPlan,
  injectRemediationToFeedbackQueue,
  type RootCauseCategory,
  type ForensicsCategory,
  type ForensicsSeverity,
  type ForensicsIncident,
  type ForensicsEfficiencyMetrics,
  type ForensicsMetrics,
  type ForensicsSummary,
  type PlanInjectionProposal,
  type ForensicsAnalysisResult,
  type ForensicsAnalysisReport,
  type AnalyzeRunForensicsOptions,
  type MetaAuditAnalysisOptions,
  type FeedbackInjectionOptions,
  type ForensicsInjectionResult,
  type FeedbackInjectionResult,
  type ExtractedToolCall,
  type TaskOrderEntry,
} from "./meta/index.ts";

export {
  AUDIT_QUESTION_IDS,
  AUDIT_QUESTIONS,
  QUESTION_ID_MAP,
  normalizeQuestionId,
  AUDIT_VERDICTS,
  checkPulseGaps,
  checkAdmittedCandidateWitnesses,
  checkAdmittedCandidateGoals,
  checkValueConsistency,
  checkScopeViolations,
  PROHIBITED_COMMAND_PATTERNS,
  checkNeverUnattendedActions,
  checkDeclinedCandidates,
  checkCharterDigestIntegrity,
  validateAuditAnswers,
  checkAuditBlocksPulse,
  assertAuditAllowsPulseOpen,
  type AuditQuestionId,
  type AuditQuestionDefinition,
  type AuditVerdict,
  type AuditAnswerVerdict,
  type AuditAnswer,
  type AuditRecord,
  type PulseGapCheckResult,
  type WitnessVerificationCheckResult,
  type CharterGoalCheckResult,
  type ValueConsistencyCheckResult,
  type ScopeViolationCheckResult,
  type NeverUnattendedCheckResult,
  type DeclinedCandidateCheckResult,
  type CharterDigestCheckResult,
  type AuditBlockCheckResult,
} from "./questionnaire/index.ts";

export {
  auditOrchestratorLiveness,
  reclaimZombieOrchestrator,
  defaultIsPidAlive,
  ORCHESTRATOR_LIVENESS_DEFECT,
  DEFAULT_HEARTBEAT_THRESHOLD_SECONDS,
  DEFAULT_SINGLETON_ROLE,
  type RosterReconciliationReport,
  type AuditLivenessOptions,
  type ReclaimZombieOptions,
  type GhostOrchestratorFinding,
  type LiveSubagentInfo,
} from "./orchestrator-liveness-auditor.ts";

export {
  auditConcurrencySaturation,
  auditSkillConcurrencySaturation,
  SKILL_CONCURRENCY_UNDER_SATURATED,
  UNSTAGED_STATION_DURABILITY_RISK,
  type ConcurrencyAuditOptions,
  type ConcurrencyAuditResult,
  type ConcurrencySaturationReport,
} from "./skill-concurrency-auditor.ts";

export {
  auditMindPreplanningStagnation,
  auditMindPreplanningLiveness,
  auditMindCreativeStagnation,
  compareReportDelta,
  isZeroDeltaReport,
  suppressZeroDeltaReport,
  computeStateSignature,
  MIND_PREPLANNING_STAGNATION,
  MIND_CREATIVE_STAGNATION,
  DEFAULT_STAGNATION_THRESHOLD_SECONDS,
  DEFAULT_ZERO_DELTA_THRESHOLD_CYCLES,
  DEFAULT_MAINTENANCE_LOOP_THRESHOLD_CYCLES,
  type StagnationAuditOptions,
  type ZeroDeltaComparisonResult,
} from "./mind-stagnation-auditor.ts";

export {
  MODE_A_AUTONOMIC_DISCOVERY,
  MODE_STANDARD_PREPLAN,
  MODE_DORMANT,
  CHRONIC_STAGNATION_CYCLE_THRESHOLD,
  executeStagnationShockRecovery,
  type StagnationMode,
  type StagnationShockOptions,
  type StagnationShockResult,
} from "./stagnation-recovery-interlock.ts";

export {
  PLAN_GRANULARITY_AUDIT,
  MONOLITHIC_PLAN_DEFECT,
  EXCESSIVE_SCOPE_DEFECT,
  DEFAULT_MAX_SUBSYSTEMS_PER_PLAN,
  DEFAULT_MAX_TASKS_PER_PLAN,
  DEFAULT_MAX_FILES_PER_TASK,
  DEFAULT_MIN_FILES_FOR_TASK_SCOPE_CHECK,
  extractPlanSubsystems,
  auditPlanGranularity,
  type PlanGranularityViolationType,
  type TaskGranularityInput,
  type PlanGranularityOptions,
  type PlanGranularityFinding,
  type PlanGranularityReport,
} from "./plan-granularity-auditor.ts";

export {
  auditCharterGoals,
  auditCharterBudgetCompliance,
  auditCharterIntegrity,
  auditCharterRepoRoots,
  auditCharterProhibitions,
  auditCharterManifest,
  auditLiveCharter,
  CHARTER_AUDIT_PASSED,
  CHARTER_UNRESOLVED_GOALS,
  CHARTER_BUDGET_EXCEEDED,
  CHARTER_INTEGRITY_DRIFT,
  CHARTER_SCOPE_VIOLATION,
  CHARTER_PROHIBITION_VIOLATION,
  DEFECT_MIND_AUDITING_MISSING_STATE_CHARTER,
  CANONICAL_CHARTER_GOAL_IDS,
  STANDARD_CHARTER_GOALS,
  type CharterAuditOptions,
  type CharterBudgetUsageMetrics,
  type CharterGoalAuditResult,
  type CharterBudgetComplianceResult,
  type CharterIntegrityAuditResult,
  type CharterRepoRootsAuditResult,
  type CharterProhibitionAuditResult,
  type CharterAuditReport,
} from "./charter-auditing.ts";
