export type {
  CounterfactualEvidenceEvaluation,
  CounterfactualEvidenceItem,
  DomainBatchingDetectionResult,
  PushbackHistory,
  PushbackRoundRecord,
  RepairProgressionEvaluation,
  ScepticismAuditOptions,
  ScepticismViolation,
  ScepticismViolationType,
  SuperficialityDetectionResult,
  TaskVerificationAuditResult,
  TaskVerificationCheckInput,
  TaskVerificationEvidenceInput,
  TaskVerificationEvidenceItem,
  ValidatedReviewPushback,
} from "./review/index.ts";

export {
  SUPERFICIAL_PATTERNS,
  appendPushbackRound,
  auditTaskVerificationEvidence,
  createPushbackHistory,
  detectDomainBatching,
  evaluateCounterfactualEvidence,
  evaluateRepairProgression,
  generateCorrectiveGuidance,
  isRepairExhausted,
  rejectSuperficialClaims,
  validateReviewPushbackCriteria,
  validateReviewPushbackInput,
} from "./review/index.ts";
