export {
  assertNoRepositoryBoundaryCrossed,
  assertSafeToDelete,
  refuse,
  assertNotDenylisted,
  assertWithinAllowedRoots,
  MIN_PATH_SEGMENTS,
  canonicalizeTarget,
  isSelfOrStrictAncestor,
  pathExists,
  realpathOfExistingAncestor,
  segmentCount,
  emitAudit,
  safeCpSync,
  safeMkdirSync,
  safeRenameSync,
  safeRmSync,
  safeWriteFileSync,
} from "./safe-fs/index.ts";

export type {
  AuditSink,
  DestructiveAuditEvent,
  SafeDeleteOptions,
  SafeFsRefusalRule,
  SafeCopyOptions,
  SafeMkdirOptions,
  SafeRenameOptions,
  SafeWriteOptions,
} from "./safe-fs/index.ts";
