export { assignWorktrees, type AssignableTask } from "./assign.ts";
export {
  commitSubphase,
  recordWorktreeCommit,
  type CommitSubphaseInput,
  type CommitSubphaseOutcome,
} from "./commit.ts";
export {
  consolidateWorktrees,
  recordConsolidation,
  reclaimOrphanedWorktrees,
  recordReclaim,
  type ConsolidateWorktreesInput,
  type ReclaimWorktreesInput,
  type ReclaimWorktreesResult,
} from "./consolidate.ts";
export {
  headSha,
  branchExists,
  createBranch,
  addWorktree,
  addWorktreeForBranch,
  currentBranch,
  mergeBranch,
  rebaseOnto,
  removeWorktree,
  deleteBranch,
  pruneWorktrees,
  diffStat,
  stageAndCommit,
  commitChangedLines,
  commitProvenance,
  type CommitProvenanceRecord,
  type MergeOutcome,
} from "./git-ops.ts";
export {
  worktreeGitEnvironment,
  createGitRunner,
  setGitRunnerForTesting,
  runGit,
  git,
  type GitResult,
  type GitRunner,
  type GitSpawn,
} from "./git.ts";
export {
  WORKTREE_LEDGER_KEY,
  readWorktreeLedger,
  writeWorktreeLedger,
  findAssignedWorktree,
} from "./ledger.ts";
export {
  createTrackWorktree,
  destroyTrackWorktree,
  cleanupTrackWorktree,
  listTrackWorktrees,
  createWorktree,
  destroyWorktree,
  cleanupWorktree,
  listWorktrees,
  createOrchestratorWorktree,
  destroyOrchestratorWorktree,
  listOrchestratorWorktrees,
  acquireWorktreeLock,
  acquireTrackLock,
  acquireOrchestratorLock,
  releaseWorktreeLock,
  releaseTrackLock,
  releaseOrchestratorLock,
  isProcessAlive,
  resolveRepo,
  type TrackWorktreeInfo,
  type OrchestratorWorktreeInfo,
  type CreateWorktreeOptions,
  type CreateOrchestratorWorktreeOptions,
  type CleanupWorktreeOptions,
  type CleanupOrchestratorWorktreeOptions,
  type ListWorktreesOptions,
  type LockPayload,
  type ReleaseWorktreeLockOptions,
} from "./manager.ts";
export { landTrackToMain, type LandTrackOptions, type LandTrackResult } from "./landing.ts";
export {
  provisionWorktrees,
  type ProvisionWorktreesConfig,
  type ProvisionWorktreesInput,
  type ProvisionWorktreesResult,
} from "./provision.ts";
