// @ts-nocheck
export type {
  OpticalDimension,
  OpticalDimensionMeta,
  IndustryProfileId,
  AestheticProfile,
  UiElementDescriptor,
  UiDescriptor,
  OpticalViolation,
  SocraticCritiqueChallenge,
  AestheticEvaluationReport,
} from "./profiles/index.ts";

export {
  OPTICAL_DIMENSIONS,
  OPTICAL_DIMENSION_METADATA,
  ENTERPRISE_ACCOUNTING_PROFILE,
  LUXURY_HOSPITALITY_PROFILE,
  FLEET_TELEMATICS_PROFILE,
  STANDARD_AESTHETIC_PROFILES,
  AestheticProfileEvaluator,
  getDefaultAestheticProfileEvaluator,
  setDefaultAestheticProfileEvaluator,
  resetDefaultAestheticProfileEvaluator,
} from "./profiles/index.ts";

export type {
  SpacingTokenName,
  SpacingTokenValue,
  FontFamilyToken,
  FontSizeToken,
  FontWeightToken,
  LineHeightToken,
  LetterSpacingToken,
  ThemeMode,
  ColorRoleTokens,
  ColorRole,
  ShadowElevationToken,
  BorderRadiiToken,
  TransitionDurationToken,
  TransitionEasingToken,
  RawValueViolation,
  RawValueValidationResult,
  StyleAdjustmentRequest,
  TokenImmunityDefense,
  TokenCompositionDescriptor,
  CompositionRecommendation,
  CompositionEvaluationResult,
  TokenProposalStatus,
  TokenEvolutionProposal,
  TokenRegistrySnapshot,
} from "./authority/index.ts";

export {
  SPACING_TOKENS,
  VALID_SPACING_VALUES,
  TYPOGRAPHY_TOKENS,
  VALID_FONT_SIZES,
  VALID_FONT_WEIGHTS,
  VALID_LINE_HEIGHTS,
  COLOR_PALETTES,
  SHADOW_ELEVATIONS,
  BORDER_RADII,
  VALID_BORDER_RADII_VALUES,
  TRANSITION_TOKENS,
  VALID_TRANSITION_DURATIONS,
  RawValuePolicyValidator,
  validateZeroRawValues,
  TokenComplianceImmunity,
  CompositionalDialecticEngine,
  TokenEvolutionManager,
  TokenAuthorityEngine,
  getDefaultTokenAuthorityEngine,
  setDefaultTokenAuthorityEngine,
  resetDefaultTokenAuthorityEngine,
} from "./authority/index.ts";
