export {
  allocateParallelLanes,
  analyzeQueueStalls,
  breakCycles,
  calculateBrentsTheorem,
  computeCriticalPathDrag,
  computeTaskSlack,
  computeTopologicalWaves,
  computeWorkSpan,
  detectArtificialSerialization,
  detectFanOutBottlenecks,
  findCycles,
  isAcyclic,
  renderForensicUnicodeReport,
  renderMermaidDag,
  type ArtificialSerializationWarning,
  type BrentsBoundResult,
  type CriticalPathDrag,
  type CycleBreakCandidate,
  type DependencyEdge,
  type FanOutBottleneck,
  type ForensicTaskNode,
  type ForensicWave,
  type ParallelLaneAssignment,
  type QueueStallAnalysis,
  type TaskSlack,
  type WorkSpanMetrics,
} from "./forensics/index.ts";
export { describeCycle, downstreamMap, topologicalOrder, type DependencyMap } from "./topology.ts";
