export {
  createImplementerValidatorPair,
  detectTransitiveBypasses,
  expandDeeper,
  expandDynamicPlan,
  expandWider,
  type BypassViolation,
  type CognitiveGuidance,
  type DeeperExpansionRequest,
  type DynamicExpansionOptions,
  type DynamicExpansionPlan,
  type DynamicExpansionResult,
  type ImplementerValidatorConfig,
  type SubtaskDecomposition,
  type SuggestedEdge,
  type TaskRolePair,
  type TransitiveBypassCheckResult,
  type WiderExpansionRequest,
} from "./dynamic-expansion.ts";

export {
  compileUnifiedHighLeveragePlan,
  detectCapsuleContext,
  expandDynamicPlanUnified,
  type CapsuleContext,
  type ExecutableTopology,
  type UnifiedPlanInput,
  type UnifiedPlanResult,
} from "./unified-plan.ts";

export {
  computeDagCriticalPath,
  computeConcurrencyMetrics,
  formatDynamicDagAscii,
  reconstructDynamicDagState,
  replanFromFindings,
  type ActiveAgentState,
  type ConcurrencyMetricsResult,
  type DagCriticalPathResult,
  type DynamicDagState,
  type DynamicTaskOrigin,
  type DynamicTaskState,
  type ReplanFindingInput,
  type ReplanFromFindingsInput,
  type ReplanFromFindingsResult,
} from "./dag-state/index.ts";
