export {
  ARTIFICIAL_SERIALIZATION_WARNING,
  FALSE_SERIALIZATION_DEFECT,
  FAST_PATH_TASK_COUNT,
  MAX_LANES_PER_COORDINATOR,
  allocateParallelLanes,
  assertAntiSerializationInterlock,
  computeWorkSpanMetrics,
  decoupleDisjointTasks,
  detectArtificialSerialization,
  evaluateHierarchyScaling,
  formatParallelSubagentsDispatchArray,
  inferStackOrDomain,
  isFastPathCompactionEligible,
  partitionDynamicLanes,
  partitionWaveCoordinators,
  verifyAntiSerializationInterlock,
  type AntiSerializationInterlockResult,
  type ArtificialSerializationWarning,
  type CoordinatorPartition,
  type DecoupleOptions,
  type DecoupledGraphResult,
  type DynamicLanePartitioningResult,
  type DynamicLaneTaskInput,
  type HierarchyScalingPath,
  type HierarchyScalingResult,
  type MultiCoordinatorPartitionOptions,
  type MultiCoordinatorWavePartitionResult,
  type ParallelLaneAssignment,
  type ParallelMetrics,
  type ParsedEdgeInfo,
  type ParsedTaskInfo,
  type SubagentDispatchFormatOptions,
  type SubagentDispatchItem,
} from "./parallel-decoupler/index.ts";
