export { deriveTestSuite, discoverTests, type DeriveTestSuiteOptions } from "./derivation.ts";
export {
  ChatVirtualFS,
  normalizePosixPath,
  SyntheticClock,
  SyntheticPidTable,
  VirtualDirent,
  VirtualFSError,
  VirtualStats,
  VirtualWatcher,
} from "./virtual-fs/index.ts";
export type {
  ChatFSDirent,
  ChatFSStats,
  ChatVirtualFSSnapshot,
  IVirtualFSWatcher,
  MkdirOptions,
  ProcessRecord,
  ProcessSpawnOptions,
  ReadFileOptions,
  ReaddirOptions,
  RmOptions,
  StatOptions,
  VirtualDirNode,
  VirtualFileNode,
  VirtualFSNode,
  VirtualStatsOptions,
  WatchEventType,
  WatchListener,
  WatchOptions,
  WriteFileOptions,
} from "./virtual-fs/index.ts";
